### ISSUE TITLE
SolrCloud configsets and collections should be consistently managed using pul_solr

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#1037]
Currently there is at least one role (`pulibrary.plantain`) which does not rely upon `pul_solr` to manage the ConfigSets and Collections in SolrCloud. This should be consistently used in all cases where feasible (and, ideally, documented where it is not). Please see https://github.com/pulibrary/pul_solr/blob/master/config/deploy.rb#L110 for reference.

Derived from some observations found while addressing https://github.com/pulibrary/princeton_ansible/issues/1036

**Comment by acozine** [comment]
Plantain role no longer exists. Closing as obsolete.
