### ISSUE TITLE
hosts: vagrant doesn't work when spinning up on Vagrant host

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/princeton_ansible#110]
When you set `hosts: vagrant` in one of the playbook config files (bibdata.yml for instance), ansible won't provision the machine using vagrant. It returns this error: `[WARNING]: Could not match supplied host pattern, ignoring: vagrant`. However, setting `hosts: all` does work.

**Comment by kayiwa** [comment]
if one adds
```
config.vm.define "libwwwstage" # needed by ansible hosts
```
this will work. Got the answer in a shade under a year.

**Comment by kayiwa** [comment]
Example here. https://github.com/pulibrary/princeton_ansible/blob/9cb71158c9b2338240ca6b540eed69162c2175ee/Vagrant/libwebVagrantfile#L12
