### ISSUE TITLE
creating a solr directory

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#1119]

**Comment by kayiwa** [comment]
the solr role needs to allow the deploy user to create the `/solr` directory on the end point

**Comment by carolyncole** [comment]
I think we might also need this task: https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.solrcloud/tasks/config.yml#L38-L43

@tampakis we are trying to run the pul-solr capistrano task on a single solr server to get the core configurations.  Anything you think we might need from the cloud role?
