### ISSUE TITLE
DSS Role Needs Device Guest Maintenance Rake Task in Cron

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#1141]
Command that needs to run:

```cd /opt/dss-blacklight/current; RAILS_ENV=production ./bin/bundle exec ./bin/rake devise_guests:delete_old_guest_users[1]```

Probably would go with 1 day or longer.

**Comment by acozine** [comment]
Fixed by https://github.com/pulibrary/DSS/pull/187.
