### ISSUE TITLE
upgrade node version on figgy machines

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/princeton_ansible#1154]
At least 10.16. Higher?

**Comment by christinach** [comment]
Based on the error I had in circleci when I upgraded lux to 2.13.1 I think 10.16 version is ok.https://circleci.com/gh/pulibrary/figgy/22938?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by hackmastera** [comment]
@sdellis suggests 12.14
