### ISSUE TITLE
geolite no longer allows anonymous download

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1157]
See https://dev.maxmind.com/geoip/geoip2/geolite2/

Current URL being used is not available: http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.tar.gz

I currently changed the task to just not run in docker, because it was bombing the builds.

Here: https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.ezproxy/tasks/main.yml#L123

**Comment by kayiwa** [comment]
Is this a viable alternative? @carolyncole https://lite.ip2location.com/database/ip-country
