### ISSUE TITLE
How should developers get access to tnsnames.ora?

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#1160]
`tnsnames.ora` is a configuration file that developers need to setup their Oracle clients. We have it (encrypted) in the `pulibrary.oracle.client` role:
https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.oracle.client/files/tnsnames.ora

Is there an easy way for a developer setting up a new machine to get this file and decrypt it?

**Comment by escowles** [comment]
This may be a documentation task to make it clear how to do that, if you haven't used ansible for anything else yet. i.e., what is the minimal path to decrypting that file and knowing where to put it?

**Comment by kayiwa** [comment]
Does this work @escowles https://github.com/jedisct1/piknik
