### ISSUE TITLE
A previous bibdata playbook run changed the permissions of `/data/marc_liberation_files` away from being by deploy.

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/princeton_ansible#1207]
This broke stuff.

**Comment by christinach** [comment]
This was reported in the `#orangelight` channel:
``in bibdata-worker2 I keep seeing `Permission denied @ rb_sysopen - /data/marc_liberation_files/1579273813  in the cron_log. also the root  sambashare 73728 Jan 9 14:14 marc_liberation_files is under root. `` when @tampakis and I ran the index on 01/17/2020.

**Comment by christinach** [comment]
To fix this we had to manually update the user and group permissions to be under deploy for `/data/marc_liberation_files/` and for  `/data/marc_liberation_files/scsb_update_files`
