### ISSUE TITLE
make group vars comply with ADR 2

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#1241]

**Comment by kayiwa** [comment]
- [ ] dpul

- [ ] orangelight

- [ ] figgy

**Comment by acozine** [comment]
See https://github.com/pulibrary/princeton_ansible/blob/main/architecture-decisions/0002-group-vars.md for the spec.

**Comment by acozine** [comment]
All projects listed above now have `vault.yml` files except for geoserver and zookeeper.

**Comment by acozine** [comment]
Looking at the `group_vars/all/vault.yml` file, there are only 24 variables defined there, they all look shared, and none of them relate to zookeeper or geoserver. On the whole this project is done. If we have specific areas where we need to clean up, we can open new tickets.
