### ISSUE TITLE
svn server playbook should install an svn hook and an XML schema

### ISSUE THREAD

**Issue by cwulfman** [pulibrary/princeton_ansible#1254]
On the old server, @sdellis and @regineheberlein had implemented a pre-commit hook to catch mal-formed XML documents.  The hook entails validating a document against the Library of Congress's EAD schema using the xmllint utility.

The schema should be be stored in `/usr/local/share/xml/schema`.

The code for the hook can be found on the old server (where?).

@kayiwa asked that the various components be installed manually on "staging" (which staging machine) to test, and then that he be provided with instructions for modifying the Ansible playbook.

**Comment by regineheberlein** [comment]
http://lib-svn-staging1.princeton.edu ?


Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by cwulfman** [comment]
Here's the hook code to be installed as `/svn/pulfa/hooks/pre-commit`:

```sh
#!/bin/bash

REPOS="$1"
TXN="$2"
AWK=/usr/bin/awk
XMLLINT=/usr/bin/xmllint
EADSCHEMA='/usr/local/share/xml/schema/ead.xsd'

# Make sure that the log message contains some text.
SVNLOOK=/usr/bin/svnlook
$SVNLOOK log -t "$TXN" "$REPOS" | \
   grep "[a-zA-Z0-9]" > /dev/null || exit 1

# Exit on all errors.
set -e

for FILE in $($SVNLOOK changed $REPOS -t $TXN | $AWK -F '   ' '{IGNORECASE = 1; if (($1 ~ /^A|U/) && ($2 ~ /\.(EAD.xml)$/)) print $2};')
do
    $XMLLINT -schema $EADSCHEMA <($SVNLOOK cat -t $TXN $REPOS $FILE)
done

# All checks passed, so allow the commit.
exit 0
```

**Comment by cwulfman** [comment]
The ead schema is at `https://www.loc.gov/ead/ead.xsd`

**Comment by kayiwa** [comment]
thanks @cwulfman
