### ISSUE TITLE
Reintroduce post upstream config for solr8

### ISSUE THREAD

**Issue by tampakis** [pulibrary/princeton_ansible#1275]
There was a conflicting version of the post upstream variable in the solr8 staging [nginx config](https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.nginxplus/files/conf/http/lib-solr8-staging.conf) that we removed in order to allow lib-solr-staging traffic to work correctly. Add this config back with a non-conflicting $upstream variable name

**Comment by acozine** [comment]
Seems to have been fixed. If this is still a problem, let's open a new ticket.
