### ISSUE TITLE
possible network error at Mudd

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/princeton_ansible#1290]
Mudd processing staff is reporting intermittent ability to commit to SVN. Failed attempts result in the hook reporting a blocked commit. First observed 2/11 in the pm. I went over there on 2/12. During my visit, staff demonstrated the issue with two different files on their respective machines. Each time, their attempts failed, with the pre-commit hook blocking the commit with output 1. When I tried, with no edits to the file, it subsequently worked. 

The sequence of events was: 
1) failed attempt on file 1. 
2) successful attempt on file 1. 
3) failed attempt on file 2. 
4) successful attempt on file 2.

> 19038 svn:log=test svn:author=vj2 svn:date=2020-02-12T16:19:27.306060Z M /trunk/eads/mudd/univarchives/AC122.EAD.xml
> 19037 svn:log=undoing test svn:author=wrc3 svn:date=2020-02-12T16:13:32.298959Z M /trunk/eads/mudd/publicpolicy/MC279.EAD.xml
> 19036 svn:log=test svn:author=wrc3 svn:date=2020-02-12T16:10:49.488212Z M /trunk/eads/mudd/publicpolicy/MC279.EAD.xml

In between 19037 and 19038 there was an unsuccessful attempt that i don't have a timestamp for.

As of 02/13 am, there have been no successful commit; all attempts are being blocked by the pre-commit hook with output 1.

From what I can tell, the following are true:

- [x] the files are in fact valid
- [x] this happened from a wired connection
- [x] subsequent attempts to commit from a laptop failed with the same error
- [x] SVN authentication is correct
- [x] this is happening on the correct server
- [x] the commit sometimes works, with no changes to the file that was blocked just seconds before

**Comment by regineheberlein** [comment]
(This is urgent as it's preventing Mudd processing staff to push out edits.)

**Comment by regineheberlein** [comment]
Attempts made 02-13, reported via Slack:
```Valencia  9:26 AM
At 9:25 I tried to commit AC122 and got the pre-hook error.
...
Valencia  9:29 AM
Same error.
...
Regine  9:31 AM
(were these from the laptop?)

Valencia  9:31 AM
Yes. ltopmudd003```

```Will Clements  11:29 AM
had another of the same error at 11:27 if that is information you are still collecting (on my desktop)
...
Will Clements  11:30 AM
it was my only attempt today. thanks for looking into it!
```

**Comment by regineheberlein** [comment]
IP addresses from which these attempts were made:
128.112.140.34/22

**Comment by kayiwa** [comment]
this is log forwarding on the Firewall wasn't done to Mudd.
