### ISSUE TITLE
NodeJS apt cache update failed

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1294]
while running converge in the recap-www role the following error occurs.  This happens in the master branch.
```
    TASK [pulibrary.nodejs : Add upstream Yarn APT repository] *********************
    fatal: [instance]: FAILED! => {"changed": false, "msg": "apt cache update failed"}
    
```

**Comment by carolyncole** [comment]
@kayiwa I'm not sure if we can apply the fix below to the ansible role.  I do not really understand what it is doing...
```
ansibled master % ansible -m apt -a "update_cache=yes" -b -u pulsys yarned
maps1.princeton.edu | CHANGED => {
    "cache_update_time": 1546878138,
    "cache_updated": true,
    "changed": true
```

**Comment by kayiwa** [comment]
this is cleaner @carolyncole 
```
ansible pulmap -u pulsys -m shell -a "curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -"
```

**Comment by kayiwa** [comment]
> @kayiwa I'm not sure if we can apply the fix below to the ansible role. I do not really understand what it is doing...
> 
> ```
> ansibled master % ansible -m apt -a "update_cache=yes" -b -u pulsys yarned
> maps1.princeton.edu | CHANGED => {
>     "cache_update_time": 1546878138,
>     "cache_updated": true,
>     "changed": true
> ```

this would have run `apt-get update` which is useless if the debian keys had expired.

**Comment by acozine** [comment]
Fixed.
