### ISSUE TITLE
sneakers cannot be started by deploy user

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#1296]
The ansible sneakers-worker role has a task to allow deploy user to restart sneakers workers. But the attempt fails on lib-orange-prod2:

```
deploy@lib-orange-prod2:~$ service orangelight-sneakers start
Failed to start orangelight-sneakers.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
```

I'm not sure what the use case is for deploy having this permission. But it doesn't seem to be working. The restart went fine using a permissioned user.

**Comment by acozine** [comment]
This vm does not exist any more. Closing as irrelevant.

**Comment by hackartisan** [comment]
The use case was capistrano -- see https://github.com/pulibrary/orangelight/blob/4cd055fe22558d0e3d56f89e321522b6209698f0/config/deploy.rb#L99-L105

I checked one of the new catalog boxes and the service is running under the deploy user.
