### ISSUE TITLE
default running_on_server true for the whole repo

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/princeton_ansible#1297]
If you leave this out of a new playbook you could get burned in a way that's difficult to detect.

**Comment by carolyncole** [comment]
@hackmastera are you planning on adding it to https://github.com/pulibrary/princeton_ansible/blob/master/group_vars/all/vars.yml?

**Comment by hackmastera** [comment]
@carolyncole I hadn't really gotten as far as to think about it. That seems like a good place, though!
