### ISSUE TITLE
The mysqld log on mariadb1-prod and maria-staging1 are getting huge

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1300]
There is just a singular log.  I'm guessing this should be rotated daily or weekly.
 ```
ls -lh /var/log/mysqld.log*
-rw-r----- 1 mysql adm 12M Feb 25 13:15 /var/log/mysqld.log
```

**Comment by kayiwa** [comment]
the percona logrotate script points to a wrong file. 
`/var/log/mysql.log` instead of `/var/log/mysqld.log`

I've changed this manually and will create a PR with this change and filed a report upstream.
