### ISSUE TITLE
Postgres version update

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1301]
Postgres 12 has been released.  The postgres cluster is on version 10.  We should think about updating the cluster before 10 becomes EOL, but that is not until November 10, 2022.

**Comment by kayiwa** [comment]
Heya @carolyncole I have a draft PR https://github.com/pulibrary/princeton_ansible/pull/1286 for staging that will bring us to 12 and we can talk about production on the other side of the impact of that.

**Comment by kayiwa** [comment]
closed by #1285
