### ISSUE TITLE
Update the ruby on the lib jobs server

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1311]
Add `ruby_version_override: "ruby2.6"` to the vars and rerun the playbook like: https://github.com/pulibrary/princeton_ansible/blob/572625f009daa8256b3226f66bf0e98ea67964f7/group_vars/approvals/approvals_staging.yml#L21

**Comment by kayiwa** [comment]
https://github.com/pulibrary/princeton_ansible/pull/1337 (is an example)

**Comment by acozine** [comment]
Currently set to https://github.com/pulibrary/princeton_ansible/blob/dc2c2934d0c3b9d828caae241d5d6e896a4a03e1/group_vars/lib_jobs/prod.yml#L6
Fixed.
