### ISSUE TITLE
Mount a solr8 backup share

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/princeton_ansible#1319]
@kayiwa will get the new share on the ops side.

Then we need to add the `lib-solr` role back into the solr8 production playbook.

Do this before going live with solr8 in production!

**Comment by kayiwa** [comment]
prod5 and prod6 are set up but 4 is failing because that how computers work.

**Comment by kayiwa** [comment]
firewall rules are updated and all machines can have shared mounted drive.
