### ISSUE TITLE
lib-orangelight-prod6 returns an error for /nginx_status

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#1322]
@carolyncole and I noticed these errors when we were trying to diagnose another problem. 
https://app.datadoghq.com/logs?cols=core_host%2Ccore_service&from_ts=1582897066553&index=main&live=true&messageDisplay=inline&query=nginx_status&stream_sort=desc&to_ts=1582897966553

{
	"id": "AQAAAXCMEipUrqxpsAAAAABBWENNRWlwWVl6Rno4cjlja3hNaQ",
	"content": {
		"timestamp": "2020-02-28T13:52:45.652Z",
		"tags": [
			"application:orangelight",
			"environment:production",
			"filename:access.log",
			"service:orangelight",
			"source:nginx",
			"sourcecategory:http_web_access",
			"type:webserverj",
			"vcenter_server:lib-vmctr",
			"vsphere_datacenter:diglib",
			"vsphere_folder:datacenters",
			"vsphere_folder:discovered_virtual_machine",
			"vsphere_folder:vm",
			"vsphere_host:lib-vm-diglib3.princeton.edu",
			"vsphere_type:vm"
		],
		"host": "lib-orange-prod6",
		"service": "orangelight",
		"message": "127.0.0.1 (-) - - [28/Feb/2020:13:52:45 +0000] \"GET /nginx_status/ HTTP/1.1\" 404 5205 \"-\" \"Sysdig Agent/1.0\"",
		"attributes": {}
	}
}

**Comment by kayiwa** [comment]
I was testing [sysdig](https://sysdig.com/products/monitor/) thanks for the reminder to turn it off.
