### ISSUE TITLE
Add new solr prod boxes to load balancer

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/princeton_ansible#1326]
What to call it? Current prod cloud is `lib-solr`. solr 8 staging cloud is called `lib-solr8-staging`. We could call it  `lib-solr8-prod` or maybe just `lib-solr-prod`. Perhaps it's better to use the version number, with the knowledge that the solr7 cloud will stick around for a bit?

**Comment by kayiwa** [comment]
it's an internal name really so I feel like having a version number isn't problematic.
