### ISSUE TITLE
Create Servers and certs for preservation-tracking application

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1333]
Move the existing preservation site off of lib-dbserver to a virtual machine behind the load balancer.
The new site url will be https://preservation-tracking.princeton.edu/  and https://preservation-tracking-staging.princeton.edu/.

Since this is a small site we will only want one server for staging and one server for production.

We will need the two virtual machines, and the https Certs.  This will be a rails application on postgres.

**Comment by kayiwa** [comment]
VMS are ready
