### ISSUE TITLE
figgy staging playbook needs group vars for geo server

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#1339]

**Comment by kayiwa** [comment]
also `figgy_stream_derivatives_mount`

**Comment by acozine** [comment]
Done:
https://github.com/pulibrary/princeton_ansible/blob/dc2c2934d0c3b9d828caae241d5d6e896a4a03e1/group_vars/figgy/staging.yml#L89-L92
https://github.com/pulibrary/princeton_ansible/blob/dc2c2934d0c3b9d828caae241d5d6e896a4a03e1/group_vars/figgy/staging.yml#L14
