### ISSUE TITLE
Ruby release management

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#134]
Ubuntu 16.06 LTS (Xenial) only supports the 2.3.1 release of `ruby` as of the creation of this issue:

- https://packages.ubuntu.com/xenial/ruby
- https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.ruby/tasks/main.yml#L9

As a consequence, more recent releases of Ruby cannot be supported using the current pulibrary.ruby Role as it is structured.

Using an external Role (such as https://galaxy.ansible.com/rvm_io/ruby/), restructuring the Role to compile Ruby from source (as suggested by @tpendragon), or using an alternative package repository (such as https://www.brightbox.com/docs/ruby/ubuntu/ by @escowles) are potential solutions to this situation.

**Comment by kayiwa** [comment]
heya. Are there any non-obvious benefits (to a ruby novice) to using the rvm based one on a production system? I'm inclined to otherwise create branch with the ppa one.

**Comment by jrgriffiniii** [comment]
@kayiwa RVM offers certain Ruby interpreters which are not available via the ppa solution:
https://rvm.io/interpreters

But if there aren't any existing use cases requiring these (for instance, the Brightbox ppa doesn't offer [JRuby](http://jruby.org/2017/12/07/jruby-9-1-15-0)), then I would also agree with the ppa-based approach.  To the best of my knowledge, [marc_liberation](https://github.com/pulibrary/marc_liberation/blob/0c945be3215c6ecb9025a1edad268604f9a219e6/marc_to_solr/README.md) *does* require that a release of JRuby be installed.

Also worth noting is that [there is a standard package for JRuby 1.7.22](https://packages.ubuntu.com/xenial/jruby), so any alternatives to the ppa approach might also be unnecessary if this is satisfactory.

**Comment by jrgriffiniii** [comment]
JRuby should be supported by the current approach to provisioning as https://packages.ubuntu.com/xenial/jruby matches the release needed to run https://github.com/pulibrary/marc_liberation

**Comment by escowles** [comment]
@jrgriffiniii It looks like the JRuby in Xenial is what we're using now — but we've had a request to upgrade to a later version so that support for this very old version can be dropped.  Traject currently tests JRuby 1.9 and 9.0 (https://github.com/traject/traject/blob/master/.travis.yml)

**Comment by jrgriffiniii** [comment]
Thank you for identifying this @escowles , I will be certain to address this also
