### ISSUE TITLE
cdh error page

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#1340]

**Comment by acozine** [comment]
Add custom 404 error page that directs users to CDH when the service is down.

**Comment by acozine** [comment]
Addressed in staging by #4179.

**Comment by acozine** [comment]
Most production sites have been updated, but we missed [Shakespeare and Co](https://github.com/pulibrary/princeton_ansible/blob/a775ea43ba14d06556a08c4c98cba9c986b99024/roles/nginxplus/files/conf/http/cdh_prod_shakespeareandco.conf#L73). Once that's fixed I think we can close this.

**Comment by acozine** [comment]
Strangely, the custom 404 from the shxco Django app was already working fine, we are not sure how. However, we have now updated the nginx config to use the custom CDH rules, and I'm comfortable closing this ticket.
