### ISSUE TITLE
Reconcile python releases on Ubuntu 18.04 LTS releases

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#1342]
Currently I encounter the following deprecation warning on Ubuntu Bionic server environments:

```
[DEPRECATION WARNING]: Distribution Ubuntu 18.04 on host figgy-staging2.princeton.edu should use /usr/bin/python3, but is using /usr/bin/python for backward compatibility with prior Ansible
releases. A future Ansible release will default to using the discovered platform python for this host. See https://docs.ansible.com/ansible/2.9/reference_appendices/interpreter_discovery.html for
 more information. This feature will be removed in version 2.12. Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.
```

My understanding of this is that `python3` should explicitly be used in Ansible Roles and Playbooks.

**Comment by acozine** [comment]
See https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html

**Comment by jrgriffiniii** [comment]
As this was a deprecation warning issued in 2020, this would have triggered a breaking change if this had obstructed virtualization or provisioning.
