### ISSUE TITLE
Implement a pulibrary.thesis-central Role

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#1347]
This should automate much of the work which has been undertaken for https://princeton.service-now.com/snap?id=ticket&table=sc_req_item&sys_id=b7e8911e1b9704148c9ebbb21a4bcb3a&view=sp, as well as look to improve some of the process which is undertaken for building Shibboleth support, installing Play, and utilizing Ansible Vault for application credentials.

**Comment by acozine** [comment]
Closed by #2593.
