### ISSUE TITLE
We should have an env for SCSB_PARTNER_UPDATE_DIRECTORY on bibdata

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#1400]
I don't know yet what the path should be. It came up while looking with @hackmastera through https://github.com/pulibrary/marc_liberation/blob/master/app/models/concerns/scsb_partner_updates.rb#L9

**Comment by acozine** [comment]
Closing this ticket, since the bibdata ticket was closed. If we still need to do this work, open a fresh ticket.
