### ISSUE TITLE
ruby2.4 no longer available

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#1445]
we get this on circle now for lib-jobs

```
 TASK [pulibrary.ruby : install Ruby "ruby2.4"] *********************************
    fatal: [instance]: FAILED! => {"changed": false, "msg": "No package matching 'ruby2.4' is available"}
```

**Comment by hackmastera** [comment]
DRDS has 2 projects that still need to be moved to 2.6 https://github.com/pulibrary/orangelight/issues/1944
https://github.com/pulibrary/cicognara-rails/issues/445

**Comment by kayiwa** [comment]
thanks for letting me know @hackmastera

**Comment by hackmastera** [comment]
update: OL is done provisioning; cicognara is the only one left and it's slated for attention a month from now so we should be good.
