### ISSUE TITLE
VMs needed for catalog-on-alma infrastructure

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#1459]
Checklist extracted from https://github.com/pulibrary/bibdata/issues/983; see that issue for more context

- [x] `bibdata-alma1`
- [x] `bibdata-alma2`
- [x] `bibdata-alma-worker1` (was `bibdata-alma-worker-qa1`)
- [x] `bibdata-alma-staging1`
- [x] `catalog1`
- [x] `catalog2`
- [x] `catalog-qa1` (was `lib-orange-alma-qa1`)
- [x] `catalog-staging1`
- [x] `catalog-staging2`
- [x] `catalog-indexer1`
- [x] `catalog-indexer2`
- [x] `catalog-indexer3`

**Comment by hackartisan** [comment]
All these VMs have been created; provisioning is covered by pulibrary/bibdata#983
