### ISSUE TITLE
[lib_smb_serve] Samba configuration should be 775 instead of 551

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1469]
551 in smb.conf made it so the user could create files, but not edit them. 775 is the more appropriate permissions for the files.

This was change on the server by hand.

**Comment by acozine** [comment]
Addressed by either #2289 or #2294.

**Comment by acozine** [comment]
Hm, well, not those PRs, but it is fixed: https://github.com/pulibrary/princeton_ansible/blob/dc2c2934d0c3b9d828caae241d5d6e896a4a03e1/roles/samba/tasks/samba_server.yml#L19.
