### ISSUE TITLE
[Percona] Update the values for wait_timeout max_allowed_packet #610

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1471]
mistakenly put in special collections see: https://github.com/pulibrary/special_collections/issues/610

**Comment by kayiwa** [comment]
```
pulsys@library-staging1:/tmp/wrk$ wrk -t12 -c800 -d60s "http://localhost/research/databases"
Running 1m test @ http://localhost/research/databases
  12 threads and 800 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   614.80ms  162.36ms   1.98s    74.58%
    Req/Sec    61.72     45.71   343.00     61.19%
  14504 requests in 1.00m, 1.99GB read
  Socket errors: connect 0, read 0, write 0, timeout 63
Requests/sec:    241.44
Transfer/sec:     33.86MB
```

**Comment by carolyncole** [comment]
We tried changing the options above, but that did not solve the issue.
Found that if we point the database directly to maria-staging1 the errors stopped.  We ran above to verify that the 500 errors stopped.

We ned to update the library website, special collections, and any other place we used `mariadb-staging` to be mariadb-staging1` and `mariadb-prod` to be `mariadb-prod1`
