### ISSUE TITLE
psql is not found on orangelight-staging

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#1477]
postgres is not installed on orangelight-staging even though the orangelight role includes the postgresql role. 
https://github.com/pulibrary/princeton_ansible/blob/72d4b7c97f505404ae12ef24a5d8399043375921/playbooks/orangelight_staging.yml#L9
https://github.com/pulibrary/princeton_ansible/blob/72d4b7c97f505404ae12ef24a5d8399043375921/roles/pulibrary.orangelight/meta/main.yml#L5

**Comment by kayiwa** [comment]
- [ ] create pul-indexer-staging1

**Comment by christinach** [comment]
@kayiwa you were right there is no playbook for the lib-pulindexer. I'll open an issue to create one.

**Comment by acozine** [comment]
All this infrastructure has been rebuilt. Closing as obsolete.
