### ISSUE TITLE
[LIBWWW] Why does discoveryutils not show up in Data dog apms?

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1485]
In the data dog service discovery utils does not seem to show up: https://app.datadoghq.com/apm/service/web.request/web.request?end=1588346090999&env=none&maxPercentile=50&paused=false&start=1588342490999

It should be configured...

**Comment by kayiwa** [comment]
https://app.datadoghq.com/apm/traces?from_ts=1588343810079&index=apm-search&live=true&query=service%3Asymfony+env%3Anone+operation_name%3Asymfony.request&to_ts=1588347410079
