### ISSUE TITLE
Extend the pulibrary.dspace Role for deploying DSpace 6.3 installations for remote hosts

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#1490]
I've found that a number of adjustments need to be introduced to the pulibrary.dspace Role in order to get this running on a Vagrant Box for development. This should mostly just consist of porting what I am introducing in https://github.com/jrgriffiniii/dspace-vagrant/pull/6/files for https://github.com/jrgriffiniii/dspace-vagrant.

**Comment by acozine** [comment]
We no longer have a DSpace role. Closing as obsolete.
