### ISSUE TITLE
Configure a read-write SVN user for Figgy export to PULFA

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#1543]
Figgy runs a rake task weekly to add DAOs to PULFA EADs, which are checked out using SVN. In order to publish the changes, Figgy needs to be configured with a SVN user account that can read  from and write to the SVN server (svn://lib-svn.princeton.edu/libsvn/trunk/eads).

**Comment by escowles** [comment]
We probably need to add a new user for this in https://github.com/pulibrary/princeton_ansible/blob/master/group_vars/lib-svn/production.yml

**Comment by kelynch** [comment]
This is addressed with #1555

**Comment by hackmastera** [comment]
Playbook was run
