### ISSUE TITLE
create elucidate annotation service

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#1584]

**Comment by christinach** [comment]
I found this information very useful regarding the JWT.:
 https://dzone.com/articles/add-secure-token-authentication-to-your-java-app
https://www.jsonwebtoken.io/
https://tools.ietf.org/html/rfc7519#section-4.1
https://github.com/jwtk/jjwt

**Comment by kayiwa** [comment]
this project hasn't been supported since 2018. I really feel we are setting ourselves up for pain trying to investigate these.
