### ISSUE TITLE
Old Digital Library of Islamic MSS static HTML site needs to be redirected to new DPUL Collection URL

### ISSUE THREAD

**Issue by kelea99** [pulibrary/princeton_ansible#1597]
@kevinreiss the old website: https://library.princeton.edu/projects/islamic/index.html. needs to be redirected to the new DPUL collection URL: https://dpul.princeton.edu/islamicmss.  @escowles has been alerted to this as well. Thank you so much!

**Comment by carolyncole** [comment]
We will need to add a rule above https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.nginxplus/files/conf/http/templates/libwww-proxy-pass.conf#L67
