### ISSUE TITLE
Create fresh checkout of SVN repo on Figgy?

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#1606]
For the weekly Figgy rake task to add DAOs to PULFA EADs, the PULFA EAD SVN repository on figgy1 is only recreated by hand, if needed in response to a disruption of the syncing service (that is, if the values of non-login-related $SVN_* variables change).

Would it be relatively uncomplicated to hand this off to Ansible?  In the event that a change is needed, the existing SVN working repository would be moved and a fresh checkout to the working directory "pulfa" would be added to the $SVN_DIR.

I'm not sure if this would be worthwhile given our plans to move away from this model for EAD in the near term and the fact that we don't have to do this very often.

**Comment by kelynch** [comment]
Current workflow for troubleshooting/recreating the working copy is described here - https://github.com/pulibrary/figgy/wiki/Updating-PULFA-from-Figgy-with-SVN.

**Comment by acozine** [comment]
We are not using Subversion in Figgy any more. Closing as irrelevant.
