### ISSUE TITLE
Security review

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#1614]
https://docs.google.com/document/d/1S58JHi4Ugabt3q7A-CB05fyfR-cwfk7vLC6O_PbHguY/edit#bookmark=id.vebsdleammp9

**Comment by acozine** [comment]
Related to https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy.

**Comment by acozine** [comment]
Closing in favor of an issue in https://github.com/PrincetonUniversityLibrary/security/issues.
