### ISSUE TITLE
Remove Redirect from research.princeton.edu, point at prds-prod1

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#1722]
When the PRDS staff signs off, remove redirect to library.princeton.edu from https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.nginxplus/files/conf/http/researchdata_prod.conf and point the domain to serve up content from backend prds-prod1.

**Comment by carolyncole** [comment]
fixed by https://github.com/pulibrary/princeton_ansible/pull/1770
