### ISSUE TITLE
Enable SAML session expiration for Shibboleth on DSpace

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#1736]
Enable expiration in SAML for Shibboleth sessions in DSpace to prevent the following:

<img width="966" alt="Screenshot of stale request error" src="https://user-images.githubusercontent.com/7795797/94033347-de00d000-fd8e-11ea-809f-aa27a50e2c11.png">

**Comment by acozine** [comment]
Resolved.
