### ISSUE TITLE
When trying to connect to marc_liberation_staging DB from bibdata-staging2 I get an error

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#1746]
psql: error: could not connect to server: FATAL:  password authentication failed for user "marc_liberation_staging"
FATAL:  password authentication failed for user "marc_liberation_staging"

**Comment by acozine** [comment]
The infrastructure has been rebuilt since this ticket was opened. If there are new challenges, let's open a new ticket.
