### ISSUE TITLE
[bibdata staging] Warning when running the bibdata_staging playbook

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#1753]
TASK [pulibrary.samba : Create samba users]
....
[WARNING]: The input password appears not to have been hashed. The 'password' argument must be encrypted for this module to work properly.
...

**Comment by acozine** [comment]
@christinach is this still an issue?

**Comment by christinach** [comment]
@acozine no it is not. I just run the playbook to confirm.
