### ISSUE TITLE
Create a role fro libruby-prod

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1774]
Multiple ruby projects are hosted on libruby-prod.  At this point I am uncertain how we maintain the box and the code that runs on it...

One of the code repos is very very out of date...

https://github.com/pulibrary/repecwp/blob/main/config/deploy.rb

**Comment by acozine** [comment]
@carolyncole is this still relevant?

**Comment by acozine** [comment]
Ah, @kayiwa confirms that libruby-prod has been deleted. Closing as obsolete.
