### ISSUE TITLE
Ruby version should be configurable

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/princeton_ansible#178]
currently hard-coded in the role. Not every app is on 2.4.

**Comment by escowles** [comment]
Maybe we should have different roles for different versions, so each playbook could pick what version it wanted?

**Comment by escowles** [comment]
A variable should work for everything from the same PPA — I was thinking that not every version of ruby would install the same way, so it might be complicated.  But now that I think about it, we could just create a separate role if we wanted to install something that wasn't in the Brightbox PPA.

**Comment by kayiwa** [comment]
fixed by this commit bd7e875
