### ISSUE TITLE
Move Capping Liberty to Lib Static

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1792]
https://github.com/pulibrary/capping-liberty

update https://github.com/pulibrary/princeton_ansible/blob/9dd10f3629a72e53a3def753590a7dc10c4911bb/roles/pulibrary.libstatic/tasks/main.yml#L4 to install the new static capping liberty site
Update nginx redirects to point at the new location

**Comment by axamei** [comment]
https://github.com/pulibrary/pathebaby_drupal
