### ISSUE TITLE
Need to use the IP address for the HR share on bibdata instead of the host name

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1794]
'10.6.49.226' - works in the /etc/fstab file
`dms-smbserve` which works on other hosts does not work on bibdata2 or bibdata-worker2

The role tries to use the name, but that causes the hr-share role to fail.

Bibdata-staging2 works just fine with the name

**Comment by christinach** [comment]
TASK [pulibrary.bind9 : Remove other nameservers] ****************************************************************************************************************************************************************************
--- before: /etc/resolv.conf (content)
+++ after: /etc/resolv.conf (content)
@@ -1,4 +1,3 @@
 # Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
 #     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
 search princeton.edu
-nameserver 128.112.200.253
