### ISSUE TITLE
Create new VMs for cdh website (test and production)

### ISSUE THREAD

**Issue by rlskoeser** [pulibrary/princeton_ansible#1798]
Please create two new VMs with the names:
- cdh-test-web1 
- cdh-web1

Both should be on the allow list for lib-ponyexpress 

They will need access to postgres servers.

For the test server, we'd like the temporary public name of test-mgr-web.cdh and eventual public name test-web.cdh (once the migration is complete and we can move the old test-web name to the new vm).

The test site should only be accessible on campus or vpn

**Comment by rlskoeser** [comment]
@kayiwa what's the status of this?

**Comment by acozine** [comment]
Done.
