### ISSUE TITLE
refactor host names

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#181]
In several cases there are hosts with name patterns like `X` and `X_production`. It's confusing because if you see `X` first you might (as I did) assume it's the production configuration. I think we should rename them to be `X_staging` and `X_production`.

hosts with both entries, in which only one has the appended string:

- [x] bibdata
- [ ] pulmap
- [x] archivesspace
- [x] orangelight
- [ ] zookeeper
- [ ] solrcloud

Probably should document this policy either in an ADR or in the README, as well

**Comment by escowles** [comment]
👍 `X_staging` and `X_production` seems much clearer
