### ISSUE TITLE
Ensure that the BASH environment for DSpace installations (as the `dspace` system user) has `rvm` loaded

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#1830]
Currently as the user `dspace`, I cannot modify `$HOME/.bashrc` in order to ensure that the command `source $HOME/.rvm/scripts/rvm` is invoked. This must be updated within the Role on Ansible in order to ensure that this is never overridden during provisionings.

**Comment by acozine** [comment]
Closing as obsolete in the hosted NWO.
