### ISSUE TITLE
delete mariadbserver server role

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#1850]
Once matomo has been shut down we can delete this role.  Do not bother upgrading it to molecule 3

**Comment by kayiwa** [comment]
we no longer use mariadbserver any place. This could be deleted.

**Comment by carolyncole** [comment]
@kayiwa the only pace I see it is matomo.  Since that server is still running I'll wait to delete it.

**Comment by acozine** [comment]
Matomo is gone. The mariadbserver role can be deleted now.

**Comment by carolyncole** [comment]
It seems that now that we are no longer utilizing percona this role should stay up until we have a substitute maria(mysql) role
