### ISSUE TITLE
Ruby should be built (rather than installed using a system package)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#186]
As proposed by @hackmastera , Ruby should be compiled using a source code distribution and built on the local environment.  The Science History Institute has developed an Ansible Role in response to these needs: https://github.com/curationexperts/ansible-hydra/blob/master/roles/ruby/tasks/main.yml

**Comment by hackmastera** [comment]
well, we paid DCE to do it for us ;)
