### ISSUE TITLE
Create staging & prod server for Friends of Princeton Library

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2022]
refs #1930

- [x] Create vm fpul-staging1.princeton.edu
- [x] Create vm fpul-prod1.princeton.edu
- [x] Generate certificate for fpul-staging.princeton.edu
- [x] Generate certificate for fpul-prod.princeton.edu

Do we need a new certificate for fpul.princeton.edu (it currently is served off of lib-ruby-prod)

**Comment by kayiwa** [comment]
I will create a SAN cert for fpul.princeton.edu (that will have fpul-prod.princeton.edu) so they can co-exist. That work @carolyncole ?
