### ISSUE TITLE
Remove redundant `nodejs` Role dependencies for Roles and Playbooks

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#2024]
As discovered on 12/14/20 by @christinach and @kayiwa, there are cases where `nodejs` is specified twice for certain roles. For an example, please see https://github.com/pulibrary/princeton_ansible/blob/main/roles/rails_app/meta/main.yml#L21 and https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/orangelight_production.yml#L10

**Comment by kayiwa** [comment]
fixed by https://github.com/pulibrary/princeton_ansible/commit/2c62125dc04c0a0ad23a3a5ceb62debc93bb1108
