### ISSUE TITLE
Change approvals to use the staging postgres

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2084]
Currently it is working on the main postgres, because the vault had bad data in it for the host.  We will need to create the database and then transfer the data from the main sql server.

**Comment by kayiwa** [comment]
heya mind if @hectorcorrea takes a stab at this? It has enough good complexity to talk ansible.

**Comment by carolyncole** [comment]
@kayiwa sure!

**Comment by acozine** [comment]
Looks like approvals is using staging postgres: https://github.com/pulibrary/princeton_ansible/blob/0870016bde6c5f1db4e5004006aa14835442e187/group_vars/approvals/approvals_staging.yml#L10. If we need to do more, let's open a new ticket.
