### ISSUE TITLE
Add datadog role to production playbook for fpul

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2088]

**Comment by acozine** [comment]
Looks like datadog is running on fpul: https://github.com/pulibrary/princeton_ansible/blob/0870016bde6c5f1db4e5004006aa14835442e187/group_vars/friends_of_pul/friends_of_pul_prod.yml#L28

**Comment by acozine** [comment]
Oops, re-opening. Looks like we added the variables, but the Datadog role is not getting run.

**Comment by acozine** [comment]
Closed by #2711.
