### ISSUE TITLE
lib-statistics production site

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2115]
We need:

- [x] A virtual machine lib-statistics-prod1
- [x] A DNS entry for lib-statistics-prod1 (to the machine) & lib-statistics (to the load balancer)
- [x] A SSL certificate for lib-statistics-prod
- [ ] A load balancer config for lib-statistics-prod

**Comment by carolyncole** [comment]
Certificate PR #2116

**Comment by kayiwa** [comment]
this looks like a good candidate for a SAN name of lib-statistics.princeton.edu cert and lib-statistics-prod.princeton.edu @carolyncole
