### ISSUE TITLE
Move Research DData to the new Postgres 12 production server

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2123]
Once #2122 is completed, move the Researchdata site from the postgres 10 server to postgres 12.

I believe we should:

1.  backup the database using drush `drush sql-dump --structure-tables-list='watchdog,sessions,cas_data_login,history,captcha_sessions,cache,cache_*' --result-file=/tmp/dump.sql`
1.  Import the backup into the new server using postgres
1.  Update the ansible variables to point at the new database
1.  run the research data playbook
    
🎉  It works ???

**Comment by kayiwa** [comment]
moved to postgresql https://github.com/pulibrary/princeton_ansible/blob/main/group_vars/researchdata/researchdata_prod.yml#L5
