### ISSUE TITLE
[LIBWWW] DataDog APM for the library website is not reporting

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2131]
I do not see the library site in the APM services even though it should be reporting.

The configuration seems to be gone...

**Comment by carolyncole** [comment]
I believe this got broken during the php upgrade.  Although the package was installed for ddtrace it was not enabled in php.  So I had to reinstall it on each server using the following commands
```
wget https://github.com/DataDog/dd-trace-php/releases/download/0.44.1/datadog-php-tracer_0.44.1_amd64.deb
sudo dpkg -i datadog-php-tracer_0.44.1_amd64.deb
sudo service apache2 restart
```

This seems to work, except it only sends traces when apache is restarted

**Comment by acozine** [comment]
Done, see https://github.com/pulibrary/princeton_ansible/blob/a9fd4052ec38e86e871d0aefed6af04a2b185697/group_vars/libwww/libwww-prod.yml#L51.
