### ISSUE TITLE
Capture 400 error or change nginx config

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2135]
Users occasionally get the following error message:
```
I keep getting this error message when trying to access various Princeton websites/ pages:
400 Bad Request
Request Header Or Cookie Too Large
nginx/1.14.0 (Ubuntu)
```
Is there a way to capture it at the load balancer and give the user more information?

https://websiteforstudents.com/resolved-400-bad-request-request-header-or-cookie-too-large-via-nginx/

**Comment by acozine** [comment]
Related to #2227?
