### ISSUE TITLE
support scheduled backups of arbitrary directories on disk 

### ISSUE THREAD

**Issue by thatbudakguy** [pulibrary/princeton_ansible#2148]
# background
cdh-built apps using Django store media files uploaded by users (images, PDFs, word docs most commonly) in a single directory on disk. for apps like the CDH website, we have in excess of 1GB of files for everything from profile pictures to PDFs of CDH documentation.

when setting up the QA environment, we often need to replicate production data in QA, which involves copying over a database sqldump and loading it into the QA database. we also need to copy over the media, so we usually .zip it and then transfer and unzip in QA. the latter part takes awhile, since so many files are involved.
# how it could work
an ansible role is created that installs a cron or other scheduled task that compresses a single directory, names the resulting archive something sensible with a timestamp, and moves it to another place on disk or uploads to the cloud.

the same role could have a task to restore the archive to a target path on disk by repeating the process in reverse. this way when doing a QA deploy, we could have it automatically restore the latest media backup from production.

**Comment by acozine** [comment]
Probably belongs in https://github.com/Princeton-CDH/cdh-ansible.

**Comment by acozine** [comment]
@rlskoeser ^^^
