### ISSUE TITLE
Re-provision everything

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#217]

**Comment by escowles** [comment]
Step 1: make a checklist from hosts file or list of playbooks.

**Comment by jrgriffiniii** [comment]
As of 03/23/18, the following hosts must be (re)provisioned using Ansible:

- [ ] bibdata-staging1.princeton.edu
- [ ] bibdata1.princeton.edu
- [ ] bibdata2.princeton.edu
- [ ] bibdata-worker2.princeton.edu
- [ ] lib-proc4.princeton.edu
- [ ] maps1.princeton.edu
- [ ] maps2.princeton.edu
- [ ] maps-staging1.princeton.edu
- [ ] mariadb1.princeton.edu
- [ ] mariadb2.princeton.edu
- [ ] lib-postgres1.princeton.edu
- [ ] lib-postgres2.princeton.edu
- [ ] figgy-staging1.princeton.edu
- [ ] figgy1.princeton.edu
- [ ] figgy2.princeton.edu
- [ ] lib-proc2.princeton.edu
- [ ] lib-proc3.princeton.edu
- [ ] lib-proc5.princeton.edu
- [ ] lib-proc6.princeton.edu
- [ ] lib-aspace-prod1.Princeton.EDU
- [ ] lae1.princeton.edu
- [ ] lae-staging1.princeton.edu
- [ ] dss-prod1.princeton.edu
- [ ] dss-staging1.princeton.edu
- [ ] lib-orange-prod2.princeton.edu
- [ ] lib-orange-prod3.princeton.edu
- [ ] lib-orange-prod4.princeton.edu
- [ ] lib-orange-prod6.princeton.edu
- [x] catalog-staging1.princeton.edu
- [ ] lib-redis.princeton.edu
- [ ] dpul1.princeton.edu
- [ ] dpul-staging1.princeton.edu
- [ ] geoserv1.princeton.edu
