### ISSUE TITLE
[BIBDATA] Remove SCSB_S3_USER_NAME (it is unused)

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2177]

**Comment by acozine** [comment]
It's still there: 
in prod: https://github.com/pulibrary/princeton_ansible/blob/dddf857afea989488734e2bb9481bb997373db09/group_vars/bibdata/production.yml#L72
in staging: 
https://github.com/pulibrary/princeton_ansible/blob/dddf857afea989488734e2bb9481bb997373db09/group_vars/bibdata/staging.yml#L71
