### ISSUE TITLE
499 errors and connection timeout problems with nginx

### ISSUE THREAD

**Issue by rlskoeser** [pulibrary/princeton_ansible#2246]
search engines (google bot, bing bot) are failing to load sitemaps on the [cdh website](https://cdh.princeton.edu), and we've lost the very good page rank we had before moving to PUL infrastructure behind nginx.  I recently switched from apache+wsgi to nginx+passenger hoping that using a setup more like other PUL applications would help resolve this problem.

Logs in datadog for requests by these bots show both 499 errors (apparently an nginx specific error) and this one:

>  (110: Connection timed out) while reading response header from upstream

There is no log entry for these requests on the vm hosting the cdh website — the request doesn't seem to get that far, somehow.

I noticed today in datadog that there are 499 errors for other sites as well; perhaps it isn't happening consistently or isn't blocking crucial functionality like search indexing for those sites, so it may not be as noticeable a problem.

I've tried temporarily increasing proxy timeouts in the nginx conf for the cdh web production site per this [stackoverflow posts](https://stackoverflow.com/questions/18740635/nginx-upstream-timed-out-110-connection-timed-out-while-reading-response-hea) but it hasn't resolved the problem.

**Comment by kelynch** [comment]
Related error in Figgy https://github.com/pulibrary/figgy/issues/4531
