### ISSUE TITLE
create a bibdata-worker1

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#2258]
Create a new bionic VM for bibdata

copy /data from bibdata-worker2 to bibdata-worker1

**Comment by kayiwa** [comment]
I agree with @carolyncole the value of https://github.com/pulibrary/princeton_ansible/blob/main/roles/bibdata/tasks/samba_server.yml is unclear.

**Comment by christinach** [comment]
We dont need this anymore. It was in voyager days.
