### ISSUE TITLE
Fix bibdata machine permissions so deploy can read/write in /data/marc_liberation_files/

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#2274]
[Bibdata/production] Errno::EACCES: Permission denied @ rb_sysopen - /data/marc_liberation_files/scsb_update_files/fixes_2021_05_21.json

@christinach commented on [Fri May 21 2021](https://github.com/pulibrary/bibdata/issues/1349)

## Backtrace

    line 149 of [PROJECT_ROOT]/app/models/concerns/scsb_partner_updates.rb: write
    line 149 of [PROJECT_ROOT]/app/models/concerns/scsb_partner_updates.rb: log_record_fixes
    line 23 of [PROJECT_ROOT]/app/models/concerns/scsb_partner_updates.rb: process_partner_files

[View full backtrace and more info at honeybadger.io](https://app.honeybadger.io/projects/54497/faults/79477042)

---

@christinach commented on [Fri May 21 2021](https://github.com/pulibrary/bibdata/issues/1349#issuecomment-846017551)

This is a permission error. We should handle this in ansible.

**Comment by hackartisan** [comment]
@christinach @kayiwa should this have been fixed in https://github.com/pulibrary/princeton_ansible/pull/2256/files and https://github.com/pulibrary/princeton_ansible/pull/2264/files? I just provisioned the bibdata-alma-staging box so maybe it will be resolved?

**Comment by hackartisan** [comment]
There was a conflict with the samba shares created in the bibdata role and the samba share logic coming out of the samba role via hr_share, which made the dir owned by root.
