### ISSUE TITLE
automate postgres update

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#2356]
make sure all db servers have access to GCE mounts
`gcsfuse pul-postgresql-backup /var/lib/postgresql/postgres_backup`
- [ ] run a database dump (or retrieve)
  - [ ] [Use community.postgresql.postgresql_db](https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_db_module.html#ansible-collections-community-postgresql-postgresql-db-module)
- [ ] confirm db name where applicable
  - [ ] practice should lean to same name because they are on separate servers
  - [ ] otherwise massage database dump accordingly 
- [ ] create the db_user where applicable
- [ ] create new db name where applicable `psql -f /path/to/dumped_file.sql` 
`grant all on database db_name to  db_user;`

**Comment by acozine** [comment]
Done.
