### ISSUE TITLE
Redirect(s) for getit.princeton.edu

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#2371]
For deployment on 8/4/2021: 

We can test with getit-dev.princeton.edu prior to 8/4. 

Root URL: getit.princeton.edu can be sent https://catalog.princeton.edu/?f%5Bformat%5D%5B%5D=Journal
Journal List URL: geit.princeton.edu/journal_list can be sent to https://catalog.princeton.edu/?f%5Bformat%5D%5B%5D=Journal

Resolver Base URL: https://getit.princeton.edu/resolve?{copy all params} should go to
New Resolver Base URL: https://princeton.alma.exlibrisgroup.com/discovery/openurl?institution=01PRI_INST&vid=01PRI_INST:Services&{all params from original URL}

Example OpenURL menus for Alma: https://docs.google.com/document/d/1b_Wv10fX6CfB8LxynG66l4KTnIOFKSwVP-DsYNhpZqo/edit

**Comment by carolyncole** [comment]
1. go on the network configuration tool and search for the name (getit -or- getit-dev) in devices
1.  Change the configuration to rename the device
     1.  Choose wired-static
     1.  Move device name
     1.  rename to old[name] 
1. move the name to the load balancer
