### ISSUE TITLE
Remove excessive Alma API keys from bibdata ENV

### ISSUE THREAD

**Issue by mzelesky** [pulibrary/princeton_ansible#2372]
The only write permissions needed for Requests are for bibs.

Unless needed by functionality in bibdata, the following API keys for Alma should be removed:
- [x] Acquisitions Read Write Production
- [x] Bibdata discharge (we no longer need the discharge functionality) - This was removed form ansible in #2348 and from code in pulibrary/bibdata#1487
- [ ] Catalog development user read/write - I don't see this one in ansible
- [ ] Catalog production user read/write - I don't see this one in ansible

**Comment by hackartisan** [comment]
Looks like we can also remove from the bibdata vault:
bibdata_newrelic_key
bibdata_newrelic_app_name
