### ISSUE TITLE
[Bibdata] Bibdata workers don't ship logs to datadog

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#2442]

**Comment by acozine** [comment]
Done, see https://github.com/pulibrary/princeton_ansible/blob/a9fd4052ec38e86e871d0aefed6af04a2b185697/group_vars/bibdata/production.yml#L144

**Comment by acozine** [comment]
Hm, the logs for bibdata-alma-worker1/2 do not appear in Datadog. Needs more investgation.

**Comment by acozine** [comment]
Oh, wait, they are there. The default display for logs in Datadog is 15 minutes, and these logs did not show up with that setting. But if you change the default to look at a longer timescale, the logs for the bibdata workers do show up.
