### ISSUE TITLE
getit.princeton.edu/resolve path redirect not working

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#2459]
https://getit.princeton.edu/resolve?sid=google&auinit=N&aulast=Diaz-Segarra&atitle=COVID-19+ischemic+strokes+as+an+emerging+rehabilitation+population:+a+case+series&id=pmid:32675706

should send you to:

https://princeton.alma.exlibrisgroup.com/discovery/openurl?institution=01PRI_INST&vid=01PRI_INST:Services&sid=google&auinit=N&aulast=Diaz-Segarra&atitle=COVID-19%20ischemic%20strokes%20as%20an%20emerging%20rehabilitation%20population:%20a%20case%20series&id=pmid:32675706

Instead it's going to the catalog's journal facet, which was our re-direction option for the root URL of getit.princeton.edu. Anything that starts with the path /resolve should got the alma base URL of 
https://princeton.alma.exlibrisgroup.com/discovery/openurl?institution=01PRI_INST&vid=01PRI_INST:Services with the querystring of the original openURL from getit.

**Comment by kevinreiss** [comment]
Redirects look correctly defined here: https://github.com/pulibrary/princeton_ansible/blob/8245d97a75ad86943b48d123b21950438245ab61/roles/nginxplus/files/conf/http/getit_prod.conf

**Comment by carolyncole** [comment]
Http works fine.  Just updating the https section to match the http section #2460
