### ISSUE TITLE
[Freinds of PUL] 500 error on gallery page

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2478]
The 500 error occurs because the page runs out of memory.
I manually updated production so that  Stephanie could do her work.
The Friends of Pul should update the /etc/php/7.4/apache/php.ini automatically to set the memory limit to 265M

**Comment by acozine** [comment]
Hm, right now we have Friends of PUL playbooks, and Friends of PUL group variables, but as far a I can see the role itself doesn't do anything. There are no tasks in the role. The playbooks currently run the `datadog` role and the `friends_of_pul` role. Should they also run the `drupal` role? This looks like a drupal-based project. 

I'm not entirely sure what the role is supposed to do, but this ticket is only a small part of the work needed on it.

**Comment by kayiwa** [comment]
Migrated to OIT infrastructure
