### ISSUE TITLE
remove libraries/firestone/rbsc redirects

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2503]
libraries/firestone/rbsc redirects to libraries/special-collections somewhere.  I think this line redirecting it to libserv39 should either be removed or sent directly to libraries/special-collections
https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf#L64

**Comment by acozine** [comment]
Related to #2496 ?
Related to #1620 and #2706 ?
