### ISSUE TITLE
ealapp server

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2507]
create a new server for eal apps (https://github.com/PrincetonUniversityLibrary/ealapps) to get it off on libphpprod.

This set of applications is still being actively developed and unitized by @tventimi 

This is a php apache project.  It is currently running with PHP 5.5.9.  We should try to see if the code will run on a newer version of PHP, otherwise we will need to install this version.

**Comment by kayiwa** [comment]
superseded by #3347
