### ISSUE TITLE
Remove deprecated proxy pass

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#2529]
```
location /voyagerapps {
        proxy_pass https://lib-dbserver.princeton.edu/voyagerapps/;
    }
```

This one can go.

**Comment by acozine** [comment]
Change to https://github.com/pulibrary/princeton_ansible/blob/4cada033172642736170fc9279f5d5eeb74e2397/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf.
