### ISSUE TITLE
Move Assigned spaces application from lib-dbserver

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2539]
We are trying to clean up lib-dbserver and need to move the spaces (lockers and study spaces) application off of the windows server.

 https://library.princeton.edu/AssignedSpaceApplication/

- [x] Create lockers-and-study-spaces-staging1 vm
- [x] Ask for SSL certs for lockers-and-study-spaces-staging.princeton.edu
- [ ] Create lockers-and-study-rooms-spaces vm
- [ ] Ask for SSL certs for lockers-and-study-spaces.princeton.edu and  
- [ ] Install new rails app (https://github.com/pulibrary/locker_and_study_spacess)

**Comment by acozine** [comment]
Site is live.
