### ISSUE TITLE
Nginx playbook errors on new server

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2556]
need to manually run: `sudo mkdir /data/nginx/lockers-and-study-spaces-staging`

Sure would be nice not to have to do that on each server...

```
TASK [../roles/nginxplus : nginxplus | make sure nginx configs are valid] **************************************************************
fatal: [lib-adc2.princeton.edu]: FAILED! => {"changed": false, "cmd": ["/usr/sbin/nginx", "-t"], "delta": "0:00:00.257307", "end": "2021-11-04 11:11:12.533545", "msg": "non-zero return code", "rc": 1, "start": "2021-11-04 11:11:12.276238", "stderr": "nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size\nnginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size\nnginx: the configuration file /etc/nginx/nginx.conf syntax is ok\nnginx: [emerg] mkdir() \"/data/nginx/lockers-and-study-spaces-staging/NGINX_cache/\" failed (2: No such file or directory)\nnginx: configuration file /etc/nginx/nginx.conf test failed", "stderr_lines": ["nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size", "nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size", "nginx: the configuration file /etc/nginx/nginx.conf syntax is ok", "nginx: [emerg] mkdir() \"/data/nginx/lockers-and-study-spaces-staging/NGINX_cache/\" failed (2: No such file or directory)", "nginx: configuration file /etc/nginx/nginx.conf test failed"], "stdout": "", "stdout_lines": []}
```

**Comment by acozine** [comment]
Looks like this is an issue as we add more sites - see https://serverfault.com/questions/419847/nginx-setting-server-names-hash-max-size-and-server-names-hash-bucket-size and https://stackoverflow.com/questions/13895933/nginx-emerg-could-not-build-the-server-names-hash-you-should-increase-server. 

We do not currently set either `server_names_hash_max_size` or `server_names_hash_bucket_size` explicitly in the role, so they are both presumably using default values. Add one or both settings to https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginx/templates/nginx.conf.j2.

**Comment by acozine** [comment]
See also the nginx documentation:
https://nginx.org/en/docs/http/server_names.html
https://nginx.org/en/docs/hash.html

**Comment by acozine** [comment]
Looking at this again, I think the warning and the failure are two different things:

- The warning is related to the nginx hash table as described above.
- The failure happens on the first run because we do not have a task that creates or checks the existence of the `proxy_cache_path` on the load balancers when we add a project. Many of our projects have these configured. The pattern is `/data/nginx/{{ project-name }}-{{ env }}/NGINX_cache/`.
