### ISSUE TITLE
apt module is not idempotent

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#2570]
the postgresql role fails idempotency 

https://github.com/pulibrary/princeton_ansible/blob/149cfebc8562a42ea900013b1fe83405eb3603d5/roles/postgresql/tasks/main.yml#L44

**Comment by kayiwa** [comment]
pretty sure this is the same problem here https://github.com/ansible/ansible/issues/73307

**Comment by acozine** [comment]
Fixed by https://github.com/pulibrary/princeton_ansible/commit/d6ae49a76b5e2cf08592615b7013622aff232874.
