### ISSUE TITLE
Increase Confluence memory to 4GB

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#2576]
I manually edited the Tomcat environment variable script to allocate 4GB of memory to Tomcat:

`/opt/atlassian/confluence/bin/setenv.sh`:
```CATALINA_OPTS="-Xms1024m -Xmx4g ${CATALINA_OPTS}"```

The default was `-Xmx1024m`, and we were seeing frequent OutOfMemoryErrors. Increasing to 4GB seems to have fixed this problem. So we should make sure that change is performed in Ansible instead of directly on the server, so it survives the playbook being run in the future.

**Comment by acozine** [comment]
Two notes:
1. I don't think the Confluence role configures tomcat/catalina options now. At least, I don't see a file or a template for `setenv.sh` anywhere, and searching the repo for `xmx` doesn't turn up anything in the confluence role.
2. It would be great to express `Xms` and `Xmx` in the same units - either `1024m` and `4096m` or `1g` and `4g`.

**Comment by acozine** [comment]
Confluence is currently running Java 11.0.12 and Tomcat 9. Both are embedded - Tomcat is in /opt/atlassian/confluence/bin/ and Java is in /opt/atlassian/confluence/jre/bin/.

**Comment by escowles** [comment]
Yes, I assume that the Ansible role runs the Confluence installer, so we'd need to add a step somewhere to update the `setenv.sh` script after that is run.

**Comment by acozine** [comment]
Moving to a hosted solution for Confluence, so we should not be working on an Ansible role for this.
