### ISSUE TITLE
Resolve or remove disk space monitors on datadog

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#2584]
There are a lot of active alerts on the disk space monitor what we have not acted on although they have been red for some time. We should either resolve the disk space issues on these machines or remove these mounts or machines from the monitor if possible.

Active alerts (note the status chart is paginated -- there are 77 at the time of this writing)
https://app.datadoghq.com/monitors/4301126?q=group_status%3AAlert&groupsPerPage=25&from_ts=1638196838393&to_ts=1638283238393&eval_ts=1638283238393

40 of the alerts are from `lib-dbs-server` mounts on figgy boxes. A bunch more are on host `lib-dbs-server`.

Limiting those, the remaining 15 are: https://app.datadoghq.com/monitors/4301126?q=-device%3A%2F%2Flib-dps-server.princeton.edu%2F%2A%20group_status%3AAlert%20-host%3Alib-dps-server&groupsPerPage=25&from_ts=1638196838393&to_ts=1638283238393&eval_ts=1638283238393&live=1d

**Comment by tpendragon** [comment]
I updated the monitor to ignore `loop*` - it may take a bit to take effect.

**Comment by acozine** [comment]
Currently there are only 4 active alerts in this section. They are probably legit.
