### ISSUE TITLE
Install shibboleth via ansible

### ISSUE THREAD

**Issue by bess** [pulibrary/princeton_ansible#2585]
The shibboleth role should:
- [x] Install all needed software and configuration files
- [x] Provide instructions for how to request access from OIT
- [x] Provide instructions for how to test the connection
- [x] Document and provide to OIT which shibboleth attributes are required for Vireo
- [x] Get our installation authorized by OIT 

Dec 8 update:
Our shibboleth installation is working and we've asked OIT to authorize it. Awaiting a response from them right now.

Dec 10 update: 
Jay at OIT says this last batch of attributes was the list he was looking for. He is working on this today.

**Comment by bess** [comment]
My response to OIT (copied here for reference):

Hi, Jay.

1) These are the shibboleth attributes we need:
"SHIB_netid"
"SHIB_mail"
"SHIB_uin"
"SHIB_givenname"
"SHIB_initials"
"SHIB_sn"
"SHIB_dateOfBirth"
"SHIB_eduPersonAffilation"
"SHIB_phone"
"SHIB_postal"
"SHIB_mail"
"SHIB_permanentPhone"
"SHIB_permanentPostal"
"SHIB_permanentMail"
"SHIB_degree"
"SHIB_department"
"SHIB_college"
"SHIB_major"
"SHIB_gradYear"
"SHIB_gradMonth"
"SHIB_orcid"

2) We are already using SSL for connection, so I don't think we need to further encrypt the traffic, but I am happy to follow OIT's guidance here.

3) The Login can be tested at https://vireo-staging.princeton.edu/Shibboleth.sso/Login

Thank you!
Bess Sadler

**Comment by bess** [comment]
As of 14 Dec, we are able to do a *partial* authentication to shibboleth. However, it is returning the user to the wrong url. After troubleshooting with @kayiwa and Jay at OIT, here is the diagnosis:

```
using this URL https://vireo-staging.princeton.edu/Shibboleth.sso/Login
I was able to see the application hit our IDP

Within the SAML request: the ACS URL is: https://vireo-staging/Shibboleth.sso/SAML2/POST

To fix this, you need to update your application to use the correct ACS URL of https://vireo-staging.princeton.edu/Shibboleth.sso/SAML2/POST which is within your metadata file.

Thanks, Jay
```

That metadata file is being generated by `mod_shib`, our shibboleth plugin for apache2. I have been trying to figure out how to get it to alter what it creates. I may need to create it the first time manually, and then hand-edit the file and put it into ansible. I'm going to try that next.

**Comment by bess** [comment]
As of December 17 we are still unable to get this working. Next, Francis and I are going to set up a totally clean ubuntu system on google cloud, which is not behind a load balancer. Then we'll attempt to ONLY install our shibboleth ansible role on it and try to get that working. That should tell us whether the problem is with our base shibboleth installation or whether some issue is being introduced by the load balancer or our proxy setup.

**Comment by acozine** [comment]
The last piece of the puzzle turned out to be in the Apache config. In the VirtualHost definition, Shibboleth requires `UseCanonicalName On` to be set. This is reflected in the [template](https://github.com/pulibrary/princeton_ansible/blob/main/roles/vireo/templates/vireo.conf.j2) in the vireo role.
