### ISSUE TITLE
migrate additional shakespeare and company project aliases to library

### ISSUE THREAD

**Issue by rlskoeser** [pulibrary/princeton_ansible#2590]
When we migrated s&co project from research computing / OIT to PUL (see #2458 ) we missed some aliases.

Please migrate the following additional aliases for the site:
- [x] shakespeareandcompany.princeton.edu
- [x] scp.princeton.edu 
- [x] mep.princeton.edu

They should all exist as aliases that redirect to the canonical site name, shakespeareandco

In addition, please add the following redirects for the **mep** hostname only (this is from the current apache config):
```apache
RedirectMatch permanent "^/+$" "https://shakespeareandco.princeton.edu/"
RedirectMatch permanent "^/cards/*$" "https://shakespeareandco.princeton.edu/sources/cards/"
RedirectMatch permanent "^/logbooks/*$" "https://shakespeareandco.princeton.edu/sources/logbooks/"
RedirectMatch seeother "^/.*" "https://shakespeareandco.princeton.edu/"
```

**Comment by kayiwa** [comment]
shakespeareandcompany.princeton.edu --> shakespeareandco.princeton.edu
scp.princeton.edu --> shakespeareandco.princeton.edu
mep.princeton.edu --> shakespeareandco.princeton.edu
