### ISSUE TITLE
Guessing Drupal 9 is failing idempotence because postgres is install a different version of the client

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2596]
Postgres uses 
`postgresql-client-{{ postgres_version }}`

Drupal 9: https://github.com/pulibrary/princeton_ansible/blob/7aea93d9da020c1ec4739e62bf5368f6ef3bfdab/roles/drupal9/tasks/main.yml#L101

**Comment by acozine** [comment]
This was a good guess. Turned out that the issue was that the `apt` module is not idempotent. The drupal9 tests are passing now - fixed by https://github.com/pulibrary/princeton_ansible/commit/d6ae49a76b5e2cf08592615b7013622aff232874. I'm going to close this.
