### ISSUE TITLE
Audit Ansible Vault usage

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#260]
Unless it's an actual secret, it's much more convenient to have them in plaintext where it's easier to check, update, review, etc.

**Comment by acozine** [comment]
Original title was: Move Solr URLs (and basically everything that's not a password) out of the vault

**Comment by acozine** [comment]
Addressed by #3284 and the other PRs for the Great Password Reshuffle. Our vault files are fairly tidy now.
