### ISSUE TITLE
Figgy playbook fails to mount shared resources

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#2654]
The figgy task `[roles/figgy : Create mount to plum binaries]` fails with `mount error: could not resolve address for (name redacted).princeton.edu: Unknown error`. 

The bind9 role currently sets the nameserver [here](https://github.com/pulibrary/princeton_ansible/blob/94c20cde60b5ef0e2b855838f1d7e1e4eacf517d/roles/bind9/tasks/main.yml#L27) but with that setting, nslookup returns:

```
$ nslookup (name redacted)
Server:		xxx.xxx.xxx.xxx
Address:	xxx.xxx.xxx.xxx#xx

** server can't find (name redacted): NXDOMAIN
```

Changing the nameserver to 127.0.0.53 fixes the problem.

**Comment by jrgriffiniii** [comment]
As @kayiwa was describing, this may well be related to the potential issues which arise due to perceived DDOS attacks upon the OIT DNS servers (this is due to the number of requests made, frequently, by `figgy` servers).

**Comment by acozine** [comment]
Ah, thanks @jrgriffiniii and @kayiwa for the background. Since the existing figgy machines are set to 127.0.0.53, we're clearly not mimicking DDOS attacks on OIT any more. I'll open a PR to update the bind9 role for future VM builds.
