### ISSUE TITLE
bibdata-qa machine to match catalog-qa

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2703]
We have a catalog-qa machine, but no bibdata-qa.  It would make sense to have a complete set.

**Comment by kayiwa** [comment]
VM built and DNS registered. Waiting for Hardware FW rules.

**Comment by kayiwa** [comment]
`bibdata-qa1` is ready. Waiting for FW rules for `bibdata-worker-qa1`

**Comment by kayiwa** [comment]
all VMs are ready.
