### ISSUE TITLE
lockers is not showing up in datadog

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2721]
April just had an issue and I noted that lockers is not showing up in datadog.  I thought I configured it, but I did not check...

**Comment by acozine** [comment]
The datadog role is included in the production playbook, see https://github.com/pulibrary/princeton_ansible/blob/0751637888caae46cb9024f6696f78ebc5eec61b/playbooks/lockers_and_study_rooms_prod.yml#L9. When I SSH to the production server, I see datadog config. And when I log into our datadog instance, I see logs: https://app.datadoghq.com/logs?query=service%3Alockers-and-study-spaces&cols=host%2Cservice&index=%2A&messageDisplay=inline&stream_sort=desc&from_ts=1645128053726&to_ts=1645128953726&live=false. 

All the entries in the logs today are labelled `info`, so maybe they are too boring to show up on the default views . . . but my guess is that someone fixed this and forgot to close the ticket. If I'm wrong, and there's more to do here, please re-open it @carolyncole.
