### ISSUE TITLE
Update the MariaDB/Percona/MySQL infrastructure

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#2737]
Related to #2684 and #2698.

At one time we had quite a few applications running on MariaDB. We had a MariaDB cluster, with a "lead" database server and several other servers. The "lead" server accepted all traffic, then delegated database creation, queries, etc., to the other servers as appropriate. This infrastructure blueprint was automated by the `mariadb` and `mariadbserver` roles. At some point the MariaDB cluster broke, and each remaining application running on MariaDB was marooned on a single server.

We had already started moving applications off of MariaDB onto Postgresql. However, there are some applications still running on MariaDB. Long-term, we want to migrate those to Postgresql, but that is not possible immediately. In the meantime, we want to fix the infrastructure to make those applications easier to maintain. Those applications include anything running on Drupal 7.

We decided to retire the MariaDB cluster and create a single server running MariaDB. We are automating and documenting this architecture in a new role called `mysql`. This role is designed so it can build the database infrastructure based on mysql, on MariaDB (a fork of mysql), or on Percona (another fork of mysql). As currently implemented, it builds MariaDB, but with a change of variables it could easily build mysql or Percona. 

Once the `mysql` role is complete and tested, we can create the new MariaDB infrastructure, migrate applications onto it, retire the old cluster VMs, and delete the `percona` and `mariadb` roles.

**Comment by kayiwa** [comment]
prod-servers are here #2740
staging servers here #2720

**Comment by carolyncole** [comment]
A search of princeton ansible for mariadb_sever gives you a decent idea of who is utilizing mysql at the moment: https://github.com/pulibrary/princeton_ansible/search?p=2&q=mariadb__server

**Comment by kayiwa** [comment]
we have moved all mysql based servers to one database.
