### ISSUE TITLE
migrate mariadb production servers

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#2740]
* [x] fpul-prod (mariadb-prod1)
* [x] library-prod (mariadb-prod2)
* [x] locator_prod(mariadb-prod3)
* [x] slavery-prod (maria-prod3)
* [x] repec-prod (mariadb-prod2)
* [x] library-prod/special-collections (mariadb-prod2)

**Comment by acozine** [comment]
Related to #2737.
