### ISSUE TITLE
Load balancer should not restart if nginx -t does not pass

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#2749]
we should run `nginx -t` before the reload step. If it has a nonzero status, the reload shouldn't run and neither should the hard restart.

The way it is now we crash all sites when there's a bad config file.

**Comment by hackartisan** [comment]
There is such a task but we need to mark it as always run so that it runs under the `update_conf` tag.

**Comment by acozine** [comment]
Related to, possibly duplicate of, #3319.
