### ISSUE TITLE
Create new dpul-staging1

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#2752]
The old one is dead to us

**Comment by acozine** [comment]
VM built and request to switch the IP over to the new MAC address sent to OIT. Once that's done we'll need to update the firewall rules, decommission the old VM, rename the new VM, and run provisioning.

**Comment by acozine** [comment]
The IP for `figgy-staging1` has been switched over to the new VM. John K confirmed that the firewall rules are good to go. And Francis got everyone's keys installed. I ran the `dpul_staging` playbook against the new VM. It will need a cap deploy (or equivalent).
