### ISSUE TITLE
Drupal 9 desires the pg_trgm extension in postgres. Can we install it?

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2763]
```
POSTGRESQL PG_TRGM EXTENSIONNot created
The [pg_trgm](https://www.postgresql.org/docs/current/pgtrgm.html) PostgreSQL extension is not present. The extension will be required by Drupal 10 to improve performance when using PostgreSQL. See [Drupal database server requirements](https://www.drupal.org/docs/system-requirements/database-server-requirements) for more information.
```

**Comment by kayiwa** [comment]
we do install extensions that in the postgresql role. See postgis example [here](https://github.com/pulibrary/princeton_ansible/blob/8dd37e2250910a9eedb9d3c1e7c7c8e570d43663/group_vars/postgresql/gcp_dev.yml#L11)

Want me to add it to that PR?

**Comment by kayiwa** [comment]
https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_ext_module.html

**Comment by kevinreiss** [comment]
This is now required for Drupal 10. Created a PR that I think should add it. 

https://github.com/pulibrary/princeton_ansible/pull/4336

**Comment by kevinreiss** [comment]
We discovered the second staging server wasn't quite set up yet.

**Comment by kevinreiss** [comment]
removed the staging server for now here https://github.com/pulibrary/princeton_ansible/pull/4342. This is now deployed to staging and prod successfully.
