### ISSUE TITLE
[Orangelight] update QA variables from catalog-alma-qa to catalog-qa

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#2798]
catalog-alma-qa is no longer the name of the sever.  It is now catalog-qa.

@acozine saw that there are two references to it still in orangelight "the same construction shows up in groups_vars/orangelight/qa.yml [here](https://github.com/pulibrary/princeton_ansible/blob/519597fdfdc27853a490e2438e77769965fec4ff/group_vars/orangelight/qa.yml#L2) and also [here](https://github.com/pulibrary/princeton_ansible/blob/519597fdfdc27853a490e2438e77769965fec4ff/group_vars/orangelight/qa.yml#L45)" In a PR review.  We should remove those.

**Comment by acozine** [comment]
Orangelight production group_vars still refer to `catalog-alma` for passenger [here](https://github.com/pulibrary/princeton_ansible/blob/cf10a99d08278170b1c0e088b0ea4f6b85dd9f02/group_vars/orangelight/production.yml). Should this also be changed?

**Comment by acozine** [comment]
The Solr URLs in the production group_vars also still reference `catalog-alma-production` but this is consistent - it shows up in production vars for the [solr8cloud](https://github.com/pulibrary/princeton_ansible/blob/36af32f7070c58f6c2bc948b736f1355328111c0/group_vars/solr8cloud/production.yml#L49-L57), [bibdata](https://github.com/pulibrary/princeton_ansible/blob/cf10a99d08278170b1c0e088b0ea4f6b85dd9f02/group_vars/bibdata/production.yml#L59-L62), and [orangelight](https://github.com/pulibrary/princeton_ansible/blob/cf10a99d08278170b1c0e088b0ea4f6b85dd9f02/group_vars/orangelight/production.yml#L57) group_vars.

I think we would have to rename the existing solr index before changing these references. Is that accurate? Is it something we want to do? It would feel tidy, but mifhr require more work than it's worth.

**Comment by acozine** [comment]
We will leave all production vars as they are for now.
