### ISSUE TITLE
[Redis] Upgrade central redis server to 4.x

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/princeton_ansible#2799]
Right now it's running 3.x which isn't supported by the 6.x series of Sidekiq or by Sidekiq Pro.

**Comment by kayiwa** [comment]
heya @tpendragon is redis 6 OK?

**Comment by tpendragon** [comment]
@kayiwa I'm not sure, I think if we did that upgrade in place it would break things that don't have the gem updated yet. Might need a new box for redis 6?

**Comment by sandbergja** [comment]
@tpendragon @kayiwa we'd like to upgrade redis on the bibdata boxes to 6.2.  The bibdata role is currently using the redis role to do this.  Could we make it configurable, so that different boxes can upgrade on their own schedule?
