### ISSUE TITLE
configure pulfalight app to use solr through loadbalancer

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#2810]
it currently points directly to lib-solr-prod4

**Comment by acozine** [comment]
Change `lib-solr-prod4.princeton.edu:8983` to `lib-solr8-prod.princeton.edu` [here](https://github.com/pulibrary/princeton_ansible/blob/64de8f6c3050a8ba08a8b28a2c294c8cac18a43d/group_vars/pulfalight/production.yml#L62)
