### ISSUE TITLE
upgrade zookeeper vms

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#2817]
Our Zookeeper virtual machines have Ubuntu 16 on them. We should update these to Bionic﻿

**Comment by hackartisan** [comment]
We should think carefully about how we want to do zookeeper maintenance. I'm thinking of this recent experience one of our devops4lib friends had. https://docs.google.com/document/d/1uRPUdF9Op2TAYyIdYhcVh7CnKY2xSddHFjrN3bxcNnM/edit

**Comment by kayiwa** [comment]
I've worried about this since I saw that document, but it dawned on my after the last outage. If I solved the problem of zookeeper by bringing the new VM what would that "mean?"

**Comment by kayiwa** [comment]
Zookeeper VMs successfully upgraded to Bionic.
