### ISSUE TITLE
[Approvals] Update documentation in playbooks/approvals - playbook will not run 'staging' by default

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#2840]
When I ran the playbook I had to set the env to staging or production accordingly.

`ansible-playbook playbooks/approvals.yml -e runtime_env=staging`

`ansible-playbook playbooks/approvals.yml -e runtime_env=prod`

**Comment by acozine** [comment]
D'oh, my mistake - every time the `runtime_env` var gets mentioned, it must include the `| default('staging')` . . . including in `when:` statements.

Fixed by #2910.
