### ISSUE TITLE
common role fails on HTTPS update

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#2841]
TASK [common : common | Add apt HTTPS capabilities.] ********************************************************************************
failed: [lib-mudd-staging1.princeton.edu] (item=ca-certificates) => {"ansible_loop_var": "item", "changed": false, "item": "ca-certificates", "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' no longer has a Release file., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.2/ubuntu bionic Release' no longer has a Release file."}
failed: [lib-mudd-staging1.princeton.edu] (item=apt-transport-https) => {"ansible_loop_var": "item", "changed": false, "item": "apt-transport-https", "msg": "Failed to update apt cache: W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://oss-binaries.phusionpassenger.com/apt/passenger bionic Release' no longer has a Release file., W:Updating from such a repository can't be done securely, and is therefore disabled by default., W:See apt-secure(8) manpage for repository creation and user configuration details., E:The repository 'https://ftp.icm.edu.pl/pub/unix/database/mariadb/repo/10.2/ubuntu bionic Release' no longer has a Release file."}

**Comment by acozine** [comment]
Addressed by #2895.
