### ISSUE TITLE
Configure SMTP server on figgy workers

### ISSUE THREAD

**Issue by hackmastera** [pulibrary/princeton_ansible#286]
@kayiwa any thoughts on what this should look like? I don't see any mail servers in here. Is there a remote server somewhere that we use instead?

**Comment by hackmastera** [comment]
see pulibrary/figgy#1331

**Comment by eliotjordan** [comment]
There is a server we use for other applications( OL and Pulmap): https://github.com/pulibrary/orangelight/blob/master/config/environments/production.rb#L82

**Comment by hackmastera** [comment]
Seems we don't actually need this; can use the library smtp server remotely ala http://guides.rubyonrails.org/action_mailer_basics.html#action-mailer-configuration
