### ISSUE TITLE
use fqrn-builtins for ansible roles

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#2861]
Updating ansible and molecule has stricter linting rules. Rather than ignore them let's future proof our selves by auditing our roles.

**Comment by kayiwa** [comment]
- [ ] abid
- [ ] apache2
- [ ] apache_ant
- [ ] apache_maven
- [ ] apache_tomcat
- [ ] appdeploy
- [ ] approvals
- [ ] bibdata
- [ ] bibdata_sqs_poller
- [ ] bind9
- [ ] blacklight_app
- [ ] cantaloupe
- [ ] capistrano
- [ ] clamav
- [ ] composer
- [ ] confluence
- [ ] datadog
- [ ] dpul
- [ ] drupal
- [ ] drupal9
- [ ] drush
- [ ] dss
- [ ] elastic
- [ ] extra_path
- [ ] ezproxy
- [ ] ffmpeg
- [ ] figgy
- [ ] figgy_filewatcher

**Comment by hackartisan** [comment]
What are the fqdn builtins? Link to any documentation or release notes?

**Comment by hackartisan** [comment]
fully qualified role names
