### ISSUE TITLE
running ruby 3.0

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#2941]
We currently use brightbox ppa for our ruby installation. At the moment there's
no [ruby 3 support](https://twitter.com/brightbox/status/1346830852995608576).
Rather than wait until they are ready and to help with future upgrades. We will
be building ruby from source

**Comment by acozine** [comment]
Building ruby from source takes longer but it lets us install specific versions (like installing specific versions of nodeJS in #2809). This offers stability and predictability and independence from third-party package management. Unless a project changes ruby versions frequently (in which case RVM or ruby-switch could be useful), this is a robust approach.
