### ISSUE TITLE
Ansibilize Cicognara

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#296]

**Comment by jrgriffiniii** [comment]
Currently https://github.com/pulibrary/cicognara-rails deploys to `libruby-dev.princeton.edu` (https://github.com/pulibrary/cicognara-rails/blob/master/config/deploy/staging.rb#L1) in the staging environment, which is a Ubuntu 16.04 LTS server with environmental factors which distinguish it from other staging servers.  Should this issue also address those other issues for the purposes of consistency?
