### ISSUE TITLE
Make apt cache_update a separate playbook or create a maintenance role

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#3013]
To avoid the problem where failure to update the apt cache makes a playbook fail (see https://github.com/pulibrary/princeton_ansible/issues/3009#issuecomment-1115109833), let's rethink the way we update the cache for apt with Ansible.

- [ ] audit roles for `update_cache: true` - probably use it once per role, mark that task `ignore_failures` so playbook runs can continue (and updates do happen when they can)
- [ ] create a maintenance playbook or role where a failure in the apt-cache update WILL make the playbook fail, add tasks to repair the keys there
- [ ] run maintenance playbook across our infrastructure, possibly quarterly?

**Comment by acozine** [comment]
We can set this playbook to run on a schedule through Ansible Tower.

**Comment by acozine** [comment]
Related to #3009.

**Comment by carolyncole** [comment]
Remove #3283 changes when this is complete.

**Comment by acozine** [comment]
Related to #3269.

**Comment by acozine** [comment]
Related to #3206

**Comment by acozine** [comment]
Closed by #3024.
