### ISSUE TITLE
Set up monitoring for PDC Describe

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#3021]
Set up monitoring, configured via Ansible, for PDC Describe.

- [ ] Set up The Ops recommended monitoring for PDC Describe
- [ ] Do it in ansible so it's repeatable
- [ ] Write up the process so someone else can do it next time

**Comment by bess** [comment]
![Screen Shot 2022-05-12 at 5.16.36 PM.png](https://images.zenhubusercontent.com/5ca3a84155cfe32f2f66b74c/bf5c9c43-b94c-4993-9188-cfa9c8ccdde0)

**Comment by acozine** [comment]
Related to #3043.

**Comment by carolyncole** [comment]
Removed from the globus epic. We will utilize honey badger while sensu matures

**Comment by jrgriffiniii** [comment]
This is driven primarily by https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/sensu_agent.yml#L8

**Comment by kelynch** [comment]
Duplicate of pulibrary/princeton_ansible#4648, closing
