### ISSUE TITLE
Set playbooks/deploy_user to run serial: 1

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#3031]
Someone should check my understanding, but I think this would make it run the whole playbook on each machine one at a time, rather than running the first task on every machine, then the second, etc.

This would reduce downtime for each machine such that I think we'd be able to run the playbook whenever we want.

https://docs.ansible.com/ansible/latest/user_guide/playbooks_strategies.html

**Comment by sandbergja** [comment]
closed by #3094
