### ISSUE TITLE
Cap Deploy Fails when the "repo" directory is owned by the web server user

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3055]
A fatal deployment error https://gist.github.com/pulbot/890b030f2574c7ce94d64417af487b75  is occuring on all our drupal servers managed by ansible where capistrano is used for deployment. This includes both Drupal 7 and 9 installs. The error(s) is:

fatal: unsafe repository ('/var/www/special_collections_cap/repo' is owned by someone else)
fatal: unsafe repository ('/var/www/library_cap/repo' is owned by someone else)

This impacts the following roles:

researchdata (Drupal 9 install directory is owned by ngnix user)
recap_www (Drupal 9 install owned by www-data)
libwww, special_collections, friends_of_pul (Drupal 7 installs owned by www-data user)

If you change the owner of the repo directory the deploy user the cap deploy works again.

**Comment by kevinreiss** [comment]
The drupal 7 sites (staging and prod) have been manually "fixed" to allow for some security patches to be deployed. The two Drupal nine sites are still in the problematic state.

**Comment by carolyncole** [comment]
The playbook is setting the owner of the repo directory to www-data.  It really needs to be deploy
