### ISSUE TITLE
remove the nginx role

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#3081]

**Comment by hackartisan** [comment]
Can you say more about this?

**Comment by kayiwa** [comment]
heya @hackartisan we have an [nginxplus](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/defaults/main.yml#L17) role which has a flag that allows us to install the opensource version. We also have a [passenger](https://github.com/pulibrary/princeton_ansible/tree/main/roles/passenger) one that installs the nginx version that ships with Ubuntu. There's no reason we could think of to maintain -yet another- nginx role.
