### ISSUE TITLE
Add Amp Up the Archives Training to the lib-static Playbook

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3136]
Add new static site repository for amp up the archives training https://github.com/pulibrary/amp-up-training to the list of static sites deployed with this playbook. The content itself will be embedded in libguides where appropriate.

**Comment by carolyncole** [comment]
https://github.com/pulibrary/princeton_ansible/blob/main/roles/libstatic/defaults/main.yml#L12
