### ISSUE TITLE
Restructure the configuration for Zookeeper in pulibrary.solrcloud

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#315]
The original implementation of the pulibrary.solrcloud contained a number of `Deprecated` comments:
```
zookeeper_hosts: localhost:2181  # Deprecated
zookeeper_hosts_solr_path: solr  # Deprecated
zk_host: '{{ zookeeper_hosts }}/{{ zookeeper_hosts_solr_path }}'  # Deprecated
zookeeper_client_path: '/opt/solr/server/scripts/cloud-scripts'  # Deprecated
```
(Please see https://github.com/pulibrary/princeton_ansible/pull/314#discussion_r215694532)

These variables were passed to the Zookeeper CLI as arguments:
```
- name: Check Root Path (znode) in ZooKeeper
  command: >
    {{ solr_zookeeper_client_path }}/zkcli.sh
    -zkhost {{ solr_zookeeper_hosts }}
    -cmd list {{ solr_zookeeper_hosts_solr_path }}
  register: solr_path_check
  changed_when: false
  ignore_errors: yes
```

Did these comments indicate that this approach should be adjusted?

**Comment by acozine** [comment]
We now have `zookeeper_hosts_dict` and `solr_zookeeper_hosts_string`. If we need more restructuring, let's open a fresh ticket.
