### ISSUE TITLE
nginx logs write to wrong error.log file

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#3150]
On pulfalight prod machines the nginx errors are writing to `/var/log/nginx/error.log.1` instead of `/var/log/nginx/error.log`. Because of this the error logs never rotate (`notifempty` is configured) and `error.log.1` never compresses, simply growing until it takes up all the space on the machine.

Log rotate configuration seems fine, but we need to figure out why nginx is writing to the wrong file.

`/var/log/nginx/access.log` exhibits correct behavior.

When we delete `error.log.1` and restart nginx it writes to the correct location. However, as soon as logrotate runs it reverts to the bad state.

We tried removing the prerotate and postrotate sections of the logrotate configuration but that didn't resolve the bug.

The bug may have been introduced in June of 2022. The last error.log writes were from the 15th. and the last good rotated file on the pulfalight staging box is June 14th.

**Comment by hackartisan** [comment]
This seems potentially relevant https://github.com/phusion/passenger/issues/2259

**Comment by acozine** [comment]
This is also happening for other rails applications:
- to error.log on bibdata-alma-worker boxes
- to error.log on pdc_describe
- to error.log on orangelight
-  dpul looked okay
