### ISSUE TITLE
Pre Curation Globus Endpoint

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#3154]
Utilize the AMI in https://github.com/pulibrary/vm-builds/blob/main/scripts/globus_install.yml to create a pre curation Globus endpoint.

This will need to be connected to an S3 bucket, configured to have access on the Curation Station.

Very similar to #3155.  May need different permissions for items in this Globus.  All of these items should be in a draft state.

**Comment by kayiwa** [comment]
thanks @carolyncole
