### ISSUE TITLE
figgy-staging cert expired

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#3156]
need this cert renewed.

Also need to add this one to our alerts.

**Comment by kayiwa** [comment]
waiting for cert from OIT. Submitted that this AM.

**Comment by hackartisan** [comment]
@tpendragon how do we add it to the datadog alert?

**Comment by tpendragon** [comment]
ADd it here: https://github.com/pulibrary/princeton_ansible/blob/be896fd0e993edc4a08e17c66a8be1c6602f9f47/group_vars/dpul_production.yml#L112-L130

**Comment by hackartisan** [comment]
the PR adding staging boxes was run and figgy-staging is on the datadog monitor now: https://app.datadoghq.com/monitors/61807889?groupsPerPage=25
