### ISSUE TITLE
Set all DLS apps to use the same bundler version

### ISSUE THREAD

**Issue by m-ichelleliu** [pulibrary/princeton_ansible#3164]
DLS will work this ticket.
All apps should run the same version of bundler locally and on staging/production machines.

- [x] DPUL
- [ ] Figgy
- [x] LAE-Blacklight
- [x] Maps Portal
- [x] Finding Aids

**Comment by m-ichelleliu** [comment]
Common Bundler
- Put bundler version locked in Gemfile.
- Put the bundler version that’s on the servers.
- Check the server for each application, get the bundler version, make sure they’re the same, put the bundler version in the Gemfile, and make sure the bundler version is right on CI.

**Comment by m-ichelleliu** [comment]
- DPUL
  - Staging: 2.1.4
  - Prod: 2.1.4
- Figgy
  - Staging: 2.2.16
  - Prod: 2.2.16
- LAE-Blacklight
  - Staging: 2.1.4
  - Prod: 2.1.4
- Maps Portal
  - Staging: 2.1.4
  - Prod: 2.1.4
- Finding Aids
  - Staging: 2.1.4
  - Prod: 2.1.4

**Comment by taylor-yamashita** [comment]
- DPUL
     - Staging: 2.1.4
     - Prod: 2.1.4
     - Gemfile.lock: 2.3.17
- Figgy
     - Staging: 2.2.16
     - Prod: 2.2.16
     - Gemfile.lock: 2.3.17
- LAE-Blacklight
     - Staging: 2.1.4
     - Prod: 2.1.4
     - Gemfile.lock: 2.3.17
- Maps Portal (PULMap)
     - Staging: 2.1.4
     - Prod: 2.1.4
     - Gemfile.lock: 2.3.17
- Finding Aids (PULFALight)
     - Staging: 2.1.4
     - Prod: 2.1.4
     - Gemfile.lock: 2.3.17

**Comment by taylor-yamashita** [comment]
The most recent bundler version is [2.3.18], released July 14, 2022.

**Comment by hackartisan** [comment]
It looks like we don't need to manage bundler versions anymore, if we have different versions installed on different dev machines, bundler will just download the right version before running. See https://bundler.io/blog/2022/01/23/bundler-v2-3.html. We can probably back out these gemfile changes.
