### ISSUE TITLE
Create a post role reminder for lib-jobs

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#3179]
like https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/libwww_production.yml#L8-L11

Needs to include a reminder to deploy aspace-helpers
Does it need to have sfx deploy reminder also?

**Comment by kevinreiss** [comment]
SFX no longer needs to be there. I believe the business logic in the repo should be retained and could potentially be useful for an e-record enrichment project in Alma but it would be executed in a different way in a a future. @mzelesky is this accurate?
