### ISSUE TITLE
Add the AWS S3 credentials for the `staging` and `production` deployments of pdc-describe

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#3182]
This is necessary in order to fully resolve https://github.com/pulibrary/pdc_describe/issues/110 and demonstrate user file uploads during the next demonstration.

**Comment by kayiwa** [comment]
do you perhaps have the wrong reference file @jrgriffiniii Your link goes to a virtual box ticket from 2017.

**Comment by jrgriffiniii** [comment]
I am sorry for this @kayiwa! This should be correct now.
