### ISSUE TITLE
automate adding SSH connectivity between the postgresql boxes

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#3220]
On the staging infrastructure we saw a problem today with `playbooks/postgresql_db_migration.yml`. The SSH connection from `lib-postgres-staging3` to `lib-postgres-staging2` failed. We need to ensure this capability is baked into the postgresql builds.

- [ ] SSH keypair must exist on `lib-postgres-<env>3` in the `~/.ssh/` directory
- [ ] SSH config file must exist on `lib-postgres-<env>3`, pointing to the nonstandard keypair name
- [ ] SSH public key must be present in an `authorized_keys2` file (auxiliary file, so we can overwrite the standard SSH authorized_keys regularly) on `lib-postgres-<env>2`

**Comment by sandbergja** [comment]
Duplicate issue with example playbook output: #3246
