### ISSUE TITLE
cicognara should not have solr_cloud installed on it directory

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#3223]
https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/cicognara.yml#L19

**Comment by carolyncole** [comment]
Looks like this was just recently added: https://github.com/pulibrary/princeton_ansible/commit/6a6b93189c8ce182bb3c015d1d07c1593cb532ec#diff-77097b5a8f4ca3fa72298b5a555c610e09489db28d0c750eded5c3b61228536eR19

**Comment by acozine** [comment]
It looks like the playbook used to include the `solr` role in some circumstances - the old line was:
`{role: roles/solr, when: postgresql_is_local == true}`
@carolyncole should this revert to the way it was before? What behavior do we want?

**Comment by carolyncole** [comment]
Closing since this is moving to a static site
