### ISSUE TITLE
Should the Rails role restart nginx when the app configs change

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#3257]
The issue with SCSB was caused by NGINX not being restarted, and the manual deployment was not done.

**Comment by acozine** [comment]
When we update the configuration for a rails application without deploying new code, nginx does not get restarted. This may need to be fixed in the `passenger` role or in the `rails_app` role. Investigate more.

**Comment by hackartisan** [comment]
The apps restart on cap deploy, it's not hard to just do a deploy after provisioning.

**Comment by hackartisan** [comment]
Oh sorry I didn't see the initial description when I left my comment.
