### ISSUE TITLE
Upgrade Java and plan for frequent, rapid Java updates

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#328]
Oracle plans to start releasing new versions of Java much more frequently, and quickly retiring old versions (and charging for anyone who wants to keep using older versions).  We should make sure everything we have is running the current version (JRE 10.0.2 currently), and be prepared to rapidly deploy new updates as they happen.

**Comment by acozine** [comment]
Related to #2469.

**Comment by acozine** [comment]
Since we upgraded our Solr8 cluster (with its Zookeepers) to Jammy, I believe we are running Java 17 everywhere that we run Java. See #4944 for details about what changed from Java 8 to now.
