### ISSUE TITLE
Geoserver idempotence tests sometimes fail

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#3292]
Here's an example run, where the test suite didn't pass because it couldn't download a certain file (which seemed like a temporary blip): https://github.com/pulibrary/princeton_ansible/runs/8078285154?check_suite_focus=true

```
  TASK [geoserver : unarchive war file] ******************************************
  fatal: [instance]: FAILED! => {"changed": false, "msg": "Failure downloading http://sourceforge.net/projects/geoserver/files/GeoServer//2.15.2/geoserver-2.15.2-war.zip, Request failed: <urlopen error timed out>"}
```

I re-ran the failed test, and it was happy.

**Comment by acozine** [comment]
Best idea is to mirror geoserver to prevent our CI from failing by adding it to solr-mirror.
