### ISSUE TITLE
fix deprecrated include

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#3305]
In Ansible 2.16 this will need to be replaced with include_task or include_role

**Comment by acozine** [comment]
Way to get out ahead of things, @kayiwa!

I've done a quick audit, and there are a lot of task `name:` lines with the word "include" in them, and a lot of READMEs that feature the text "to include contact information", and a lot of config files or templates with the word "include" in them, plus a few variables called "include", but very few bare `include` Ansible directives - most already use `include_tasks` or `include_role` or `include_vars`. PR coming for the remaining few.
