### ISSUE TITLE
Run nginx -t on the inactive adc before applying a potentially destructive change

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#3319]
We should add a pre_task to the nginx plus playbook that does the following:

- Deploy the config to the inactive load balancer
- Run `nginx -t` to make sure that the config is okay
- Stop the playbook if the config is not okay

The goal is to prevent us from running the nginx plus playbook with bad config on the active lib-adc, thereby taking all of our sites down.

**Comment by acozine** [comment]
See also the documentation in the pul-it-handbook:
https://github.com/pulibrary/pul-it-handbook/blob/main/services/nginxplus.md

**Comment by acozine** [comment]
Ansible gathers the IP address(es) of all hosts during fact gathering. We can use this to control the logic of the nginxplus playbook. For example, this playbook:
```
- name: test safer nginxplus approach
  hosts: nginxplus_production
  remote_user: pulsys
  strategy: linear
  become: true
  vars_files:
    - ../group_vars/nginxplus/main.yml
  tasks:
    - name: check on IP addresses
      debug: var=ansible_all_ipv4_addresses

    - name: ping only the inactive VM
      ping:
      when: "'128.112.203.146' not in ansible_all_ipv4_addresses"
```
Runs the second task only on the inactive load balancer:
```
% ansible-playbook --ask-vault-password playbooks/nginxplus-test.yml
Vault password: 

PLAY [test safer nginxplus approach] ****************************************************************************

TASK [Gathering Facts] ****************************************************************************
ok: [lib-adc2.princeton.edu]
ok: [lib-adc1.princeton.edu]

TASK [check on IP addresses] ****************************************************************************
ok: [lib-adc1.princeton.edu] => {
    "ansible_all_ipv4_addresses": [
        "128.112.203.145",
        "128.112.203.146"
    ]
}
ok: [lib-adc2.princeton.edu] => {
    "ansible_all_ipv4_addresses": [
        "128.112.203.144"
    ]
}

TASK [ping only the inactive VM] ****************************************************************************
skipping: [lib-adc1.princeton.edu]
ok: [lib-adc2.princeton.edu]

PLAY RECAP ****************************************************************************
lib-adc1.princeton.edu     : ok=2    changed=0    unreachable=0    failed=0    skipped=1    rescued=0    ignored=0   
lib-adc2.princeton.edu     : ok=3    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
We could use this logic to ensure the playbook only runs on the inactive VM:
1. Gather facts on all hosts
2. Run the role on the inactive host and reload the new config there

We could then extend this approach to the remaining tasks:
3. Restart the active host to switch which LB is active
4. Gather facts again and confirm the active host has switched (though we need a way to "remember" which was which)
5. Run the role on the remaining host and reload the new config there

**Comment by acozine** [comment]
@sandbergja suggested we implement https://stackoverflow.com/questions/52973639/force-limit-parameter-to-be-set-in-ansible/54578930#54578930 as a first step toward bulletproofing.

**Comment by hackartisan** [comment]
I like these ideas to require a limit as a first step, and to only run on the inactive host. I think it would be good to just stay there for a while and see if we feel burdened by the step of then switching the active host and running it again. It might be nice to not have that part automated, in case something didn't go as planned.
