### ISSUE TITLE
Create Playbook for EALAPPS

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3347]
Repo: https://github.com/PrincetonUniversityLibrary/ealapps

Requirements

* PHP 8
* Mysql
* Curl

Staging and prod servers are:

eal-apps-staging1
eal-apps-production1

**Comment by kevinreiss** [comment]
Work with Tom V. on this new playbook.

**Comment by kevinreiss** [comment]
App to be deployed https://github.com/PrincetonUniversityLibrary/ealapps

**Comment by sandbergja** [comment]
Related to https://github.com/pulibrary/princeton_ansible/issues/2507, which has some good details about the apps.

**Comment by kayiwa** [comment]
**Migration steps**
1. path to app on production: `/var/www/apps/ealweb/`
2. db credentials: `/var/www/apps/ealweb/connections/connection_mysql.php`
3. mysqldump -udb_user -p db_name > ~/YYYY_MM_DD_db_name.sql

**Comment by kevinreiss** [comment]
Need to reach out to @tventimi for testing/review.
