### ISSUE TITLE
Upgrade friends_of_pul role to PHP 8.1

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3349]

**Comment by kevinreiss** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/DACS-Maintenance-5da0db919c4ddf0001b2eb92/issues/pulibrary/princeton_ansible/3349?planning-poker) with Zenhub @christinach @leefaisonr @maxkadel @regineheberlein @rladdusaw @sandbergja

**Comment by kevinreiss** [comment]
Also Drupal 7. 
- Run locally with PHP 8.1 - make sure site comes up and admin backend works
- Refresh cache locally and the drupal cron task
- Check the active "feeds" importers for libcal events. Run manually at the /import route. 
- Update ansible role to use php 8.1
- Deploy to staging
- Deploy to prod

**Comment by sandbergja** [comment]
Closed by #3392
