### ISSUE TITLE
Upgrade pas role to PHP 8.x

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3352]

**Comment by acozine** [comment]
This project is an outlier, since it does not involve Drupal at all. This project uses the craft CMS, which may require an upgrade to support PHP 8.1. 

We're running Craft 3, which [says it wants PHP 7.4](https://craftcms.com/docs/3.x/config/db-settings.html).

**Comment by christinach** [comment]
@kevinreiss will handle the public keys for the external developers to @kayiwa.
