### ISSUE TITLE
Upgrade Discoveryutils to PHP 8.1

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3356]

**Comment by kevinreiss** [comment]
This app is part of the libwww role.

**Comment by kevinreiss** [comment]
1. Run locally with PHP 8.1 with Lando
2. Run phpunit test suite. 
3. In tandem with upgrade of the main library website deploy to staging
4.  In tandem with upgrade of the main library website deploy to prod

**Comment by christinach** [comment]
Can we test this in the library-staging website?

**Comment by kevinreiss** [comment]
We will run this on php 8.0 since the main website which shares a server with this app requires it.
