### ISSUE TITLE
Delete these TLS certs

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#3397]
There is still a recap-prod name

**Comment by kayiwa** [comment]
add 

- [ ] lib-elixir-test
- [ ] ojs-dev
- [ ] cdh-beta
- [ ] lib-prod
- [ ] getit

**Comment by acozine** [comment]
lib-elixir-test was removed in #2642.
ojs-dev was removed in #3303.
cdh-beta was removed in #3405.

The last two seem to still be in the `roles/nginxplus/files/ssl/` directory.
