### ISSUE TITLE
Node 18 binaries are not compatible with Ubuntu bionic

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#3476]
The nodejs role uses the pre-built binary tarballs from the nodejs web site.  As of Node 18, [these binaries assume glibc 2.28 or later](https://nodejs.org/de/blog/announcements/v18-release-announce/#toolchain-and-compiler-upgrades), which bionic does not have (focal and higher do).

As a result, we can't use the nodejs role to upgrade to any node LTS after node 16.

### Steps to replicate

1. Edit group vars for an application to have `desired_nodejs_version: "v18.12.1"`
2. Run the playbook on a staging box
3. SSH into the box
4. Run `node -v`
5. Note that, instead of getting the expected node version, you get an error message:

``` 
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)`
```

### Create a new Staging VM
- [ ] Log into VSphere and find the jammy template
  * Right Click and Select New VM from the template
  * If  repec-staging1 one exists create a new VM called repec-staging2 and save it in discovered machines
- [ ] Create firewall Rules for your new VM
- [ ] Modify the node values at `group_vars/<project_name>/staging.yml` sometimes `group_vars/<project_name>/common.yml` or `group_vars/<project_name>/main.yml` to point to v18.17.0
- [ ] Modify the postgresql values `group_vars/<project_name>/staging.yml` to point to `lib-postgres-staging1` for the database and the `postgresql_version` to 15
- [ ] Modify `inventory/all_projects/<projectnam>` to comment out bionic vm and add new vm
- [ ] Run a database dump/restore from `lib-postgres-staging3` to `lib-postgres-staging1` using [playbooks/postgresql_db_migration.yml](playbooks/postgresql_db_migration.yml)
- [ ] run the playbook for the role
- [ ] run a deploy of the application
- [ ] modify the roles nginxplus config to point to the new VM

VM's updated to jammy

### staging

- [x] approvals
- [x] abid
- [x] bibdata
- [x] dss
- [ ] dpul
- [ ] figgy
- [x] geaccirc
- [x] lib-jobs
- [x] lockers_and_study_spaces
- [x] mudd-dbs
- [x] oawaiver-staging
- [x] orangelight
- [ ] pulfalight
- [x] repecwp
- [ ] pulmap

### production

- [x] approvals
- [ ] abid
- [x] bibdata
- [x] dss
- [ ] dpul
- [ ] figgy
- [x] geaccirc
- [x] lib-jobs
- [x] lockers_and_study_spaces
- [x] mudd-dbs
- [x] oawaiver
- [x] orangelight
- [ ] pulfalight
- [x] repecwp
- [ ] pulmap

**Comment by sandbergja** [comment]
This is only affecting me, and I suspect it is a combination of the nodejs version in the .tool-versions and my M1 mac.  Closing in favor of #839.

**Comment by sandbergja** [comment]
oops, I closed the wrong issue.  Apologies!

**Comment by acozine** [comment]
To fix this, we will move away from Bionic. We have Jammy Jellyfish (22.04 LTS) images coming soon and will prioritize migrating projects that use Node and need to be upgraded.

**Comment by hackartisan** [comment]
node 16 EOL is in September 2023. https://endoflife.date/nodejs

**Comment by sandbergja** [comment]
Confirmed that now that approvals-staging is on jammy, I can install Node 18!  Thanks! 🪼
