### ISSUE TITLE
[video_reserves] Build new video_reserves production server

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#3506]
In order to move video reserves production off the old server (libphp-dev.princeton.edu) to the new server (lib-vr-prod1.princeton.edu) we'll need to:

- [x] Get SAN TLS certs for videoreserves-prod (lib-vr-prod1)
- [x] Run the video_reserves ansible role against the new production server
- [x] Use capistrano to deploy to the new production server
- [x] Get an updated database dump from the current production system
- [x] Load the database dump to the new production system
- [x] Test the new server

**Comment by maxkadel** [comment]
Do we need a similar PR to this one first, but for videoreserves rather than videoreserves-staging? https://github.com/pulibrary/princeton_ansible/commit/eb200720db5b6ca217014a3fdbb12355b1bf7aab

**Comment by kevinreiss** [comment]
Yes, I think we do need a PR for the production hostname too.

**Comment by kayiwa** [comment]
heya @maxkadel and/or @kevinreiss do we want videoreserves.princeton.edu or the already available videoreserves-prod.princeton.edu ?

**Comment by maxkadel** [comment]
@kayiwa  - we want it to be publicly available at the same place it is now - library.princeton.edu/hrc (we can mirror the current setup on staging, where the new flavor is available at library-staging.princeton.edu/hrc)
