### ISSUE TITLE
Set-Up New Production Environment for PAS 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3549]
- [x] Create new prod server https://github.com/pulibrary/ops-catchall/issues/18
- [x] Run updated playbook on new prod server 
- [x] Seed production database with current Staging database
- [x] Deploy craft 4 application branch to new production with capistrano
- [x] Test site in new production location. 
- [x] Ask Site Manager a final look at new production
~- [ ] Move public hostname slavery.princeton.edu to new environment.~
- [x] Confirm email works after movement of domain to new environment. Visit https://slavery.princeton.edu/adminPrinceton/settings/email and utilize the "test" option. An email from the environment will be sent to the account of the user who is trying the test.

**Comment by maxkadel** [comment]
Francis & I have scheduled the build and swap for 7 am on Wednesday, January 11, 2023.

**Comment by kevinreiss** [comment]
Database file to seed to the craft four production environment can be found on slavery-staging1 at:

/home/deploy/princeton-slavery--2022-12-21-091725--v4.3.5.sql

**Comment by maxkadel** [comment]
Broke out email into its own ticket - see https://github.com/PrincetonUniversityLibrary/pas-craft3/issues/76

**Comment by kevinreiss** [comment]
We've resolved all these.
