### ISSUE TITLE
[ealapps] remote_user cannot be overridden

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#3573]
See https://github.com/pulibrary/princeton_ansible/blob/a6b486776aa8d65dde0432eaf3dd46cea16eb789/playbooks/ealapps.yml#L8 for reference. 

When trying to run the ealapps playbook with the `-u pulsys` flag, I found it did not work - my machine still tried to connect as `tventimi`. It worked fine if I either replaced the `remote_user` in the playbook with `pulsys`, or if I commented out this line entirely and passed in the `-u pulsys` flag.

Is there a way to have this a variable with a default, like runtime_env? We could keep the default as `tventimi` but make the override with a flag work?

**Comment by maxkadel** [comment]
Looks like this might be referring to the same issue - https://groups.google.com/g/ansible-project/c/_NS9ueyd0Xg/m/6lYC9HlnAwAJ

**Comment by acozine** [comment]
Ah, yes, this is a precedence issue. See https://docs.ansible.com/ansible/latest/reference_appendices/general_precedence.html for the rules of precedence for other settings besides variables.

You can pass `-e ansible_user=pulsys` to override the entry in the playbook. We could add a comment to the playbook suggesting this as a workaround.

Alternatively, we could change that line in the playbook to be `remote_user: "{{ connection_user }}"` and then set a default in the role of `tventimi`. If we did that, you'd still have to pass `-e connection_user=pulsys` to run as the `pulsys` user, though. Would that make it easier? More obvious what to do?
