### ISSUE TITLE
[ealapps] URLs that don't end in a slash give "Something went wrong" error

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#3577]
Steps to recreate:

1. Make sure you are off VPN
2. In your browser, go to https://library.princeton.edu/eastasian/shadowfigures
3. Note that it attempts to redirect to https://eal-apps-prod.princeton.edu/shadowfigures/, which gives a "Looks like something went wrong!" message

When the URL has a slash at the end (e.g. https://library.princeton.edu/eastasian/shadowfigures/), the site works as expected.

**Comment by tventimi** [comment]
The error "Looks like something went wrong!" no longer occurs, but without the final slash, URLs are still converted to eal-apps-prod and appear that way in the address bar of the browser.

**Comment by maxkadel** [comment]
Note that this also occurs the rest of the directories in the proxy-pass file:
* https://library.princeton.edu/eastasian/newtitles
* https://library.princeton.edu/eastasian/stafftools
* https://library.princeton.edu/eastasian/hishi
* https://library.princeton.edu/eastasian/oclcpinyin
* https://library.princeton.edu/eastasian/assets
* https://library.princeton.edu/eastasian/EALJ

**Comment by maxkadel** [comment]
The library-staging versions of these urls also resolve to eal-apps-prod, e.g. 
https://library-staging.princeton.edu/eastasian/shadowfigures resolves to https://eal-apps-prod.princeton.edu/shadowfigures/

**Comment by maxkadel** [comment]
Closed by #3586

You must clear your cache or go into an incognito window in order to see the fix. 

Made a separate ticket for the web application firewall for the staging environment - see https://github.com/pulibrary/princeton_ansible/issues/3589

**Comment by tventimi** [comment]
Thanks for your work on this.  I am still seeing this issue with specific sites that use CAS authentication, e.g. https://library.princeton.edu/eastasian/stafftools/officesupplies.php

Tom

**Comment by sandbergja** [comment]
@tventimi - this seems like a separate issue (not related to the slash in the URL).  Could you please confirm that the service url is being set correctly here? https://github.com/PrincetonUniversityLibrary/ealapps/blob/main/stafftools/gest_report_header.php#L12

**Comment by maxkadel** [comment]
@tventimi - the CAS issue is a separate issue - I've created a ticket for it in ealapps - see https://github.com/PrincetonUniversityLibrary/ealapps/issues/17.
