### ISSUE TITLE
Retire transcribe.princeton.edu

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#3602]
We got a reminder to renew certificates for this site. The project, which began in 2016, is no longer active. The sit should not exist, the content generated when it was active has been archived elsewhere. Can we use this to create a checklist for retiring sites?

Current the URL returns this for a home page:

![Screen Shot 2023-01-06 at 11 02 28 AM](https://user-images.githubusercontent.com/879121/211061454-1d08d069-fdd5-440e-b0ac-cdfd6beeefe2.png)

I think we can do better.

**Comment by kayiwa** [comment]
deleted the alias from libphp-prod
![Screenshot 2023-01-10 at 7 50 32 AM](https://user-images.githubusercontent.com/685884/211556785-e9018cad-bb60-4c4a-a805-c47a3dc4a0ce.png)
