### ISSUE TITLE
Upgrade Ubuntu version used for Molecule testing

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#3611]
We're still using Bionic today. GitHub is deprecating it in March. Time to upgrade!

See https://github.com/pulibrary/princeton_ansible/blob/e9432558fe9bb28d664a056fa7c48cb3d39ea954/roles/omp/meta/main.yml#L15 for an example of where to update this in our codebase.

**Comment by maxkadel** [comment]
There will be brown-outs for the Ubuntu 18.04 images prior to the full deprecation date - see https://github.com/actions/runner-images/issues/6002

**Comment by kayiwa** [comment]
Closed by this ticket https://github.com/pulibrary/princeton_ansible/pull/4651
