### ISSUE TITLE
[lib-jobs] peoplesoft mount doesn't always mount when required

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#3675]
### Expected behavior

If the peoplesoft samba share isn't mounted, these two tasks should identify that and recreate the mount: https://github.com/pulibrary/princeton_ansible/blob/94d57aa32f694a40e69e775dc2493a5dddcf0ff5/roles/lib_jobs/tasks/main.yml#L41-L60

### Actual behavior

Today on production, the mount was not behaving properly.  We did the following steps:

1.  `umount` to remove the mount
2. `rm -rf` the mount point
3. re-ran the playbook

The playbook reported "Skipped" for the task "Create mount for peoplesoft shared files", and the mount point was not created.

### Tips

1. We commented out the `mount_info.changed` check on this line: https://github.com/pulibrary/princeton_ansible/blob/94d57aa32f694a40e69e775dc2493a5dddcf0ff5/roles/lib_jobs/tasks/main.yml#L59 and the playbook successfully created the mount point.  So something is wrong with this check or with the `register` in the previous task.
2. @maxkadel found this: https://docs.ansible.com/ansible/latest/collections/ansible/posix/mount_module.html#parameter-state

**Comment by acozine** [comment]
It's possible that the `ansible.posix.mount` module reads the `fstab` - I believe that running `umount` only removes the mount, without updating `fstab`. If that's true, then on the second run, the `mount.info` variable would not have reported changed.
