### ISSUE TITLE
Set some postgres configs that will give us more performance assessment info

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#3699]
For consideration. I saw these recommendations in this article https://www.crunchydata.com/blog/exposing-postgres-performance-secrets

- [x] activate postgres pg_stat_statements extension 
- [ ] log explain plans for slow queries (log for any query that takes longer than 60 seconds, so that it matches the datadog alert)

what do you think @tpendragon @kayiwa

**Comment by tpendragon** [comment]
I don't think I wanna kill long running queries, but more info sounds awesome to me.

**Comment by hackartisan** [comment]
yeah I agree that would be bad. I'll add the 2 recommendations as checkboxes in the description.

**Comment by kayiwa** [comment]
https://docs.ansible.com/ansible/latest/collections/community/postgresql/postgresql_ext_module.html

**Comment by sandbergja** [comment]
See also this config file: https://github.com/pulibrary/princeton_ansible/blob/main/roles/postgresql/templates/postgresql.conf.j2

**Comment by sandbergja** [comment]
Here is the [alert we got for bibdata](https://app.datadoghq.com/monitors/4727581?source=monitor_notif&q=application%3Abibdata&from_ts=1694292181000&to_ts=1694293381000&eval_ts=1694293381000).  After this work is done, it would be great to update the alert to include information about how to troubleshoot the alert using these new logs/tools.

**Comment by kayiwa** [comment]
the following steps are enabled on `lib-postgres-prod1`

```sql
ALTER SYSTEM SET auto_explain.log_min_duration = 60000;
ALTER SYSTEM SET auto_explain.log_analyze = on;
ALTER SYSTEM SET auto_explain.log_triggers = on;
ALTER SYSTEM SET auto_explain.log_nested_statements = on;
```

These should be added to the `/etc/postgresql/{version}/main/postgresql.conf`
