### ISSUE TITLE
Create Playbook for Byzantine Translations Project

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3704]
- Locally, using the Lando installation, ensure that the site will run on PHP 8
- Drupal 7 installation
- Can be modeled after the one for special collections. 

Project repo: https://github.com/pulibrary/byzantine_translations

VMs for the staging/prod installs requested here: https://github.com/pulibrary/ops-catchall/issues/27. 

Database dump can be obtained from current production system on libphp-prod. Install directory is /var/www/apps/byzantine

Site will need entries in the load balancer updated to proxy the path /byzantine at https://library.princeton.edu/byzantine and https://library-staging.princeton.edu/byzantine to the new staging and production databases. 

### Implementation notes
* Can use Special Collections Role & Playbook as example, but Byzantine does not require file mount. 
* Lives at a non-root location
* Site is located in /var/www/apps/byzantine on the server libphp-prod. The unix user that is the owner of the directory is called "drupal" not deploy.

**Comment by kevinreiss** [comment]
- [ ] Obtain database dump from libphp-prod
- [ ] Test site locally on Drupal 8 https://github.com/pulibrary/byzantine_translations/issues/18
- [ ] Add new proxy rule to lib-adc for new staging staging server
- [ ] Test playbook on new staging environment
- [ ] Load database in staging environment
- [ ] Test playbook on new production environment
- [ ] Load database in production environment
- [ ] Preview Site in new production environment
- [ ] Update existing proxy pass rule for production URL in lib-adc to point new production server.

**Comment by sandbergja** [comment]
To get a db dump:

- @kevinreiss will add @maxkadel 's key to the pulsys user on the legacy server
- ssh into the legacy server
- run the drush command `drush sql-dump`

**Comment by maxkadel** [comment]
I'm struggling to get the "verify" test passing (copy-pasted from the Special Collections role) 

```
  PLAY [Verify] ******************************************************************
  
  TASK [test for presence byzantine sudoer commands] *****************************
  ok: [instance] => (item=deploy ALL=(ALL) NOPASSWD: /usr/sbin/service apache2 *)
  ok: [instance] => (item=Runas_Alias WWW = www-data)
  ok: [instance] => (item=deploy ALL = (WWW) NOPASSWD: ALL)
  failed: [instance] (item=deploy ALL=(ALL) NOPASSWD: /bin/chown -R www-data /var/www/byzantine*) => {"ansible_loop_var": "item", "backup": "", "changed": true, "failed_when_result": true, "item": "deploy ALL=(ALL) NOPASSWD: /bin/chown -R www-data /var/www/byzantine*", "msg": "line added"}
  failed: [instance] (item=deploy ALL=(ALL) NOPASSWD: /bin/chown -R deploy /var/www/byzantine*) => {"ansible_loop_var": "item", "backup": "", "changed": true, "failed_when_result": true, "item": "deploy ALL=(ALL) NOPASSWD: /bin/chown -R deploy /var/www/byzantine*", "msg": "line added"}
```

It looks like these are connected to the changes made in the Capistrano role - see https://github.com/pulibrary/princeton_ansible/blob/1b8729d23ea8a607ff47212961280eccfafd4669/roles/capistrano/tasks/main.yml#L55-L74

**Comment by maxkadel** [comment]
Still struggling with the tests not passing. 

Also, how should we get the logos on the servers? For the staging server, I copied them into the `/var/www/byzantine/shared` directory and changed their owner and permissions to:

```
-rw-rw---- 1 www-data deploy  1438 Feb 23 17:32 favicon_0_0.ico
-rw-rw---- 1 www-data deploy 25860 Feb 23 17:32 firestone-small.png
-rw-rw---- 1 www-data deploy  5830 Feb 23 17:32 hp_logo.jpg
-rw-rw---- 1 www-data deploy   527 Feb 23 17:32 pul-logo.gif
```

**Comment by kevinreiss** [comment]
I think using the shared directory for the images makes sense. These are the only file assets this site will need to use. Having them available in Drupal's sites/default/files directory in this fashion is less involved than setting up a mount point on a fileshare (which is what we've done for sites that that all for the uploading of file assets).

**Comment by maxkadel** [comment]
Is it ok if we put them in the byzantine translations github repository? It looks like that's how the library site does it.
