### ISSUE TITLE
adding new site to loadbalancers fails

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#3714]
When adding the byzantine project to the load balancer, we ran into a blocker where the nginx config check failed for lack of a `proxy_cache_path` directory. This directory should exist on the load balancer(s) at `/data/nginx/<project_name>/` and include a sub-directory called `NGINX_cache`. The ansible error output was:

```
TASK [../roles/nginxplus : nginxplus | make sure nginx configs are valid] **********************************************************************************************
fatal: [lib-adc2.princeton.edu]: FAILED! => {"changed": false, "cmd": ["/usr/sbin/nginx", "-t"], "delta": "0:00:00.677829", "end": "2023-02-23 19:52:36.724533", "msg": "non-zero return code", "rc": 1, "start": "2023-02-23 19:52:36.046704", "stderr": "nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size\nnginx: [warn] conflicting server name \"cdh-test-derrida.princeton.edu\" on 0.0.0.0:443, ignored\nnginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size\nnginx: the configuration file /etc/nginx/nginx.conf syntax is ok\nnginx: [emerg] mkdir() \"/data/nginx/byzantine-prod/NGINX_cache/\" failed (2: No such file or directory)\nnginx: configuration file /etc/nginx/nginx.conf test failed", "stderr_lines": ["nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size", "nginx: [warn] conflicting server name \"cdh-test-derrida.princeton.edu\" on 0.0.0.0:443, ignored", "nginx: [warn] could not build optimal server_names_hash, you should increase either server_names_hash_max_size: 512 or server_names_hash_bucket_size: 64; ignoring server_names_hash_bucket_size", "nginx: the configuration file /etc/nginx/nginx.conf syntax is ok", "nginx: [emerg] mkdir() \"/data/nginx/byzantine-prod/NGINX_cache/\" failed (2: No such file or directory)", "nginx: configuration file /etc/nginx/nginx.conf test failed"], "stdout": "", "stdout_lines": []}
```

We ran the `nginxplus.yml` playbook (with no tags added) to add the byzantine project, but this directory was not created. A quick look at the nginxplus role did not reveal where this step should happen, so we are ticketing the issue lest we forget. Hoping there's an easy fix.

Related to #3710.

**Comment by maxkadel** [comment]
It looks like there is an "Ensure NGINX Proxy Cache Directories Exists" task, but that it was skipped, even when the files didn't exist on the server. See https://github.com/pulibrary/princeton_ansible/blob/7aea93d9da020c1ec4739e62bf5368f6ef3bfdab/roles/nginxplus/tasks/conf/template-config.yml#L36-L46

**Comment by acozine** [comment]
We're not currently using the template capacity of the nginx role. But we could, potentially.

I am curious how the directories at `/data/nginx/<project_name>/` have been created in the past.

Related to #2776.

**Comment by kayiwa** [comment]
can we change this to `/var/cache/nginx`
