### ISSUE TITLE
Main is consistently failing CI 

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#3717]
For the last 6 CI runs (as of Monday morning, February 27, 2023), either the ojs or oaiwaiver role has failed. 

The last successful CI run sha - f0167ce4ac0a5b0bc92bf261b53ee863d0cd7648 

Links to failed tests, from oldest to newest:
* https://github.com/pulibrary/princeton_ansible/actions/runs/4195346475/jobs/7275789869 - failed idempotence on ruby_s for oaiwaiver role
* https://github.com/pulibrary/princeton_ansible/actions/runs/4196184979/jobs/7276808322 - failed idempotence on ruby_s for oaiwaiver role
* https://github.com/pulibrary/princeton_ansible/actions/runs/4196184979/jobs/7276808322 - failed idempotence on ruby_s for oaiwaiver role
* https://github.com/pulibrary/princeton_ansible/actions/runs/4207088963/jobs/7301435406 - failed converge ("copy translations to running server") on ojs role
* https://github.com/pulibrary/princeton_ansible/actions/runs/4263496046/jobs/7420314376 - failed converge ("copy translations to running server") on ojs role
* https://github.com/pulibrary/princeton_ansible/actions/runs/4265081140/jobs/7434180994 - failed converge ("copy translations to running server") on ojs role

**Comment by kayiwa** [comment]
This is closed by this PR https://github.com/pulibrary/princeton_ansible/pull/3705
