### ISSUE TITLE
san certs for incommon

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#3745]
We have a playbook that can create certificates for domain names.

We will need to improve this to create multi domain certificates [SAN] by possibly passing more than one variable to the creation process.

**Comment by acozine** [comment]
This work should update https://github.com/pulibrary/princeton_ansible/blob/4ce3c14a821471132589298d65cdfbbb1caccf73/playbooks/incommon_certbot.yml.

Once it's done, we should also delete https://github.com/pulibrary/princeton_ansible/blob/4ce3c14a821471132589298d65cdfbbb1caccf73/playbooks/cert_renewal.yml.

**Comment by acozine** [comment]
Closed by #3777
