### ISSUE TITLE
Test Tower deploy on DACS projects

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#3775]
Ensure that we can deploy to all DACS projects using the Pulbot replacement template on Ansible Tower. Testing against staging environments is fine.

- [x] https://github.com/pulibrary/orangelight
- [x] https://github.com/pulibrary/bibdata
- [x] https://github.com/pulibrary/lib_jobs
- [x] https://github.com/pulibrary/dss
- [x] https://github.com/pulibrary/lockers_and_study_spaces
- [x] https://github.com/pulibrary/approvals
- [x] https://github.com/pulibrary/repecwp
- [x] https://github.com/pulibrary/mudd-dbs
- [x] https://github.com/pulibrary/aspace_helpers
- [x] https://github.com/pulibrary/geaccirc
- [x] https://github.com/pulibrary/pul_library_drupal/
- [x] https://github.com/pulibrary/special_collections
- [x] https://github.com/pulibrary/discoveryutils
  - Needs capistrano-composer gem installed on box
- [x] https://github.com/pulibrary/friends_of_pul
- [x] https://github.com/pulibrary/byzantine_translations
- [x] https://github.com/pulibrary/recap
- [x] https://github.com/pulibrary/researchdata
- [x] https://github.com/pulibrary/firestone_locator

Private repos - cannot test
-  https://github.com/PrincetonUniversityLibrary/pas-craft3
-  https://github.com/PrincetonUniversityLibrary/video_reserves
-  https://github.com/PrincetonUniversityLibrary/ezproxy_conf

**Comment by maxkadel** [comment]
Max's wish list, based on this experience:
* That the deploys went into their own channel, rather than the general server-alerts channel
* That it were easier in Tower to see the most relevant info for these jobs - that is, the project, branch, and environment.
* A way to link to specific output in Tower, especially standard error

**Comment by kevinreiss** [comment]
These deploys have all been testing on staging.
