### ISSUE TITLE
dpul fails to deploy

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#3824]
https://ansible-tower.princeton.edu/#/jobs/playbook/664/output

- Add the ActiveSupport gem to the app deploy server.

https://github.com/pulibrary/dpul/blob/main/config/deploy.rb#L95

**Comment by carolyncole** [comment]
Here is a link to the gem https://rubygems.org/gems/activesupport

**Comment by eliotjordan** [comment]
Add the ActiveSupport gem to the app deploy server.

https://github.com/pulibrary/dpul/blob/main/config/deploy.rb#L95
