### ISSUE TITLE
Manage *.ezproxy-test.princeton.edu through certbot

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3825]
This PR added support to automatically manage this for the *.ezproxy.princeton.edu. Also add this for the test domain *.ezproxy-test.princeton.edu.

https://github.com/pulibrary/princeton_ansible/pull/3817/files

related documentation: https://github.com/pulibrary/dacs_handbook/blob/main/ezproxy_tls.md

**Comment by kayiwa** [comment]
closed by this https://github.com/pulibrary/princeton_ansible/pull/3822
