### ISSUE TITLE
[PDC-Describe] Create worker VMs for running Redis and Sidekiq

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#3827]
## **Do not work this ticket yet...**

Create a box for staging and prod to run rails, redis and sidekiq on. 

This will need to have port 6379 open to the rest of the pdc-describe boxes.

What other information is needed?

**Comment by kayiwa** [comment]
I'm terrible with names @carolyncole would appreciate a name for these

**Comment by carolyncole** [comment]
We would like to keep each Redis/Sidekiq independent, so we are going to not create an external worker box.
