### ISSUE TITLE
Can not SSH on to EC2 connection

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#3841]
![Screenshot 2023-04-28 at 2 03 37 PM](https://user-images.githubusercontent.com/1599081/235221183-655b3de8-343d-4651-94f7-794676038100.png)

**Comment by carolyncole** [comment]
I connected and disconnected from VPN and was able to ssh on.  There is some weirdness.

**Comment by kayiwa** [comment]
heya @carolyncole https://github.com/pulibrary/pul-it-handbook/blob/main/services/aws.md (the Troubleshooting part)

**Comment by acozine** [comment]
Next time this happens, let's try `ssh -vvvv` to see if we can get more diagnostic info.

**Comment by carolyncole** [comment]
@acozine @hectorcorrea had the error and this is what showed in the ssh
```
$ ssh -vvvv pulsys@44.197.15.236
OpenSSH_9.4p1, LibreSSL 3.3.6
debug1: Reading configuration data /Users/correah/.ssh/config
debug1: /Users/correah/.ssh/config line 1: Applying options for *
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: include /etc/ssh/ssh_config.d/* matched no files
debug1: /etc/ssh/ssh_config line 54: Applying options for *
debug2: resolve_canonicalize: hostname 44.197.15.236 is address
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts' -> '/Users/correah/.ssh/known_hosts'
debug3: expanded UserKnownHostsFile '~/.ssh/known_hosts2' -> '/Users/correah/.ssh/known_hosts2'
debug1: Authenticator provider $SSH_SK_PROVIDER did not resolve; disabling
debug3: ssh_connect_direct: entering
debug1: Connecting to 44.197.15.236 [44.197.15.236] port 22.
debug3: set_sock_tos: set socket 3 IP_TOS 0x48
```

**Comment by hectorcorrea** [comment]
In this particular case the issue was that my IP address while on the VPN was not covered in the ranges that the security group in AWS for this machine allows. I added my IP address as indicated in these instructions https://github.com/pulibrary/pul-it-handbook/blob/main/services/aws.md#trouble-shooting (thanks @carolyncole) and I am able to SSH again.

**Comment by carolyncole** [comment]
I have not seen this recently, so I am closing for now...
