### ISSUE TITLE
Block deploying from Tower if a branch is failing CI in GitHub

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#3868]
@hackartisan has asked that the tower deployment git hub pr check status (CI, rubocop ect.).  

`"required_contexts": []` disables the status check.  '  Added by https://github.com/pulibrary/princeton_ansible/pull/3867

We need a way to optionally add this back in via the tower deploy.

**Comment by acozine** [comment]
Currently [this line](https://github.com/pulibrary/princeton_ansible/blob/dd079eda1613729aab5eed750d4173e9fce54dc9/playbooks/deploy_code.yml#L19) sets `required_contexts` to `[]` - in other words, no contexts required. If we set this to a variable, we should be able to require passing CI by default in Tower while allowing an override. Need to find out what values do the thing we want.

**Comment by carolyncole** [comment]
@acozine should we just close this?

**Comment by carolyncole** [comment]
If this becomes a priority then we should reopen, but for now we have enough work.
