### ISSUE TITLE
Default DNS nameserver creates problems for Vagrant

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#389]
By default, `127.0.0.53` (or something similar) is set when using Vagrant to provision a new environment.  As a consequence, `/usr/bin/apt-key adv --keyserver keyserver.ubuntu.com --recv 561F9B9CAC40B2F7` can fail when provisioning using the Role `pulibrary.passenger`

Please let me know if this is better suited for a request for the base VM image.

**Comment by kayiwa** [comment]
hmmm. Can you try the following? (apologies if you have) after you ssh into the vagrant box?

```
/usr/bin/apt-key adv --keyserver keyserver.ubuntu.com --recv 561F9B9CAC40B2F7
```
without modifying anything and see what happens?

**Comment by acozine** [comment]
We're not using Vagrant these days. Obsolete.
