### ISSUE TITLE
Add Cicognara Static Site to lib-static role

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3914]
- [x] Add https://github.com/pulibrary/cicognara-static to the list of static repos
- [x] Make the "_site" sub-directory the website root.
- [x] Have the site served up at the domain cicognara-staging.princeton.edu on lib-static-staging1
- [x] Preview staging site with Cliff and Esme. 

### Implementation Notes

Both domains are already on the load balancer so can be repointed to their new backend without too much trouble.

**Comment by sandbergja** [comment]
A few questions:

- [ ] The CSS and JS needed for this site are outside of the /catalogo subdirectory.  Can we change the repo to move these around?
- [ ] We can ignore the cicognara-catalogo repository for the purposes of this ticket, right?
- [ ] What is the best way to coordinate work on this ticket?

**Comment by sandbergja** [comment]
FYI for anybody who picks this up: https://github.com/pulibrary/princeton_ansible/pull/3975 is a draft PR that accomplishes the first two tasks on this checklist.

**Comment by escowles** [comment]
@sandbergja I don't think `/catalogo/` should be the root — the site needs to be built into the `/_site/` directory and that used as the root. That will include the CSS/JS and blog posts in addition to the `/catalogo/` directory. We've talked about removing `_site` from `.gitignore` and commiting the static output, or setting up Jekyll and building the static output in Ansible — either one of those would be fine with me.

And cicognara-catalogo can be ignored — the data in there gets processed by scripts in cicognara-static and written as pages in the `/catalogo/` directory.

**Comment by escowles** [comment]
@sandbergja I have a PR to update the README to make it clearer what's needed to run the Jekyll site vs. updating the content: https://github.com/pulibrary/cicognara-static/pull/56

**Comment by kevinreiss** [comment]
Let's put moving forward on this on hold until this one is worked through https://github.com/pulibrary/cicognara-static/issues/57. For this to be a truly "static" site in the lib-static state the HTML would exist in the repository so the server doesn't need ruby, etc.

**Comment by escowles** [comment]
I've merged https://github.com/pulibrary/cicognara-static/pull/58 so there is now a fully-static copy of the site in the `/_site/` directory that can be used without needing to setup and run Jekyll.

**Comment by sandbergja** [comment]
lib-static-staging1 has been inaccessible due to the Forrestal host failures -- we will need to wait until it is accessible again.

**Comment by maxkadel** [comment]
Once the site static site is available at cicognara.org, should we remove the cicognara playbook, etc.?

**Comment by maxkadel** [comment]
Proposed time on 7/6/2023 to preview site with Esmé and Cliff.

**Comment by maxkadel** [comment]
https://cicognara-staging.princeton.edu/ is now the static site hosted on lib-static-staging1

**Comment by maxkadel** [comment]
It looks like on the static site, even when there is no item to display, the Mirador viewer shows. 

- [No scan on staging](https://cicognara-staging.princeton.edu/catalogo/itempages/2420.html)
![page for work with no scan on staging showing empty mirador viewer](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/c2d7122a-b00b-4bed-9971-b7c746a8c24f)
- [Same item with no scan on production](https://cicognara.org/catalog/2420)
![page for work with no scan on production, with no Mirador viewer](https://images.zenhubusercontent.com/5d51624a5b89150001ae0b03/0807982d-7db0-42ca-8592-eec7fae9f0f5)

**Comment by maxkadel** [comment]
Apparently above is a known problem.

**Comment by maxkadel** [comment]
Work to put site into production moved to #4053.
