### ISSUE TITLE
[orangelight] Add Redis

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#3935]
Orangelight needs Redis in order to use the rack-mini-profiler gem. See [pulibrary/orangelight/3573](https://github.com/pulibrary/orangelight/issues/3573). 

Since the data stored should be shared across servers, a centralized Redis is the best option. 

The redis gem is currently tested against redis 5 through 7. Our current version on the shared server is 4.0.9 (not supported by the gem). For discussion of this issue, see https://github.com/pulibrary/princeton_ansible/issues/2799

**Comment by maxkadel** [comment]
@kayiwa has built lib-redis-staging1.princeton.edu with Jammy and Redis 6 and lib-redis-prod1.princeton.edu  is in the wings. See https://github.com/pulibrary/princeton_ansible/pull/3939/files

**Comment by sandbergja** [comment]
This has been run on all the environments
