### ISSUE TITLE
Switch Alma SFTP Prod and Staging to use Public Key Auth

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#3961]
We continue to have timeout issues using password authentication and almasftp@pu.win.princeton.edu within the Alma environment and lib-sftp-prod1 and lib-sftp-staging1. Alma can give us a public key we can register on each box to use key-based auth instead when connected from the Alma environment. @mzelesky and I gave key-based authentication from Alma a manual test in staging and prod using both the Alma Sandbox and Alma Production environments and it worked much faster. 

## Implementation notes
These keys would only be used with the almasftp@pu.win.princeton.edu that is configured to be the user that Alma connects  with to lib-sftp-prod1 and lib-sftp-staging1. 

@kayiwa @acozine a couple of questions?

1. Alma can give keys as RSA or ECDSA, should we go with the latter? 
2. Is there a pattern in princeton ansible for managing a public key that we only want to be in the user's authorized_keys files on certain boxes? 
3. Are there any concerns with having a user utilize password based authentications in certain contexts (i.e. bibdata/lib-jobs using almasftp@pu.win.princeton.edu with a password), but also have the same user configured in the external Alma environment to utilize a public key?

**Comment by kayiwa** [comment]
> We continue to have timeout issues using password authentication and [almasftp@pu.win.princeton.edu](mailto:almasftp@pu.win.princeton.edu) within the Alma environment and lib-sftp-prod1 and lib-sftp-staging1. Alma can give us a public key we can register on each box to use key-based auth instead when connected from the Alma environment. @mzelesky and I gave key-based authentication from Alma a manual test in staging using the Alma sandbox and it worked much faster.
> 
> @kayiwa @acozine a couple of questions?
> 
> 1. Alma can give keys as RSA or ECDSA, should we go with the latter?

the latter.

> 2. Is there a pattern in princeton ansible for managing a public key that we only want to be in the user's authorized_keys files on certain boxes?

look at how we use cdh (that can be expanded)

> 3. Are there any concerns with having a user utilize password based authentications in certain contexts (i.e. bibdata/lib-jobs using [almasftp@pu.win.princeton.edu](mailto:almasftp@pu.win.princeton.edu) with a password), but also have the same user configured in the external Alma environment to utilize a public key?

No there aren't.

**Comment by kevinreiss** [comment]
ECDSA key generated on Alma tested successfully on lib-sftp-staging1 with the almasftp@pu.win.princeton.edu SFTP user. I placed the key in the authorized file manually.

**Comment by kevinreiss** [comment]
Added keys in this PR: https://github.com/pulibrary/princeton_ansible/pull/3967.

**Comment by acozine** [comment]
Next step is to update the `sftp` role so these keys get added for the correct user any time we rebuild this infrastructure.
