### ISSUE TITLE
Library-staging should be connected to mailcatcher, and not lib-ponyexpress

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#3978]
I just filled out a form on library-staging.princeton.edu, and it sent real emails!  We should disconnect lib-ponyexpress, and point to mailcatcher instead, so that we can more safely experiment!

**Comment by sandbergja** [comment]
@ishasinha1 and I looked at this briefly today.  I submitted an lsupport ticket to just not let library-staging send email to lib-ponyexpr.  We also looked at configuring the sendmail path in php.ini to `catchmail`, but it was unsuccessful, since the library website uses [this module that bypasses that setting](https://www.drupal.org/project/smtp).

- tried overriding the `smtp_host`

**Comment by kayiwa** [comment]
Library staging is no longer supported.
