### ISSUE TITLE
Vagrant boxes for Zookeeper and Solr fail to provision system services

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#399]
These initially worked for https://github.com/pulibrary/princeton_ansible/pull/314, but the Vagrantfiles now no longer seem to provision either the pulibrary.zookeeper or pulibrary.solr Roles:

```
pulsys@lib-zk1:~$ sudo service --status-all
...
 [ + ]  rsyslog
 [ - ]  screen-cleanup
 [ - ]  sendsigs
 [ + ]  ssh
 [ + ]  udev
 [ + ]  ufw
 [ - ]  umountfs
 [ - ]  umountnfs.sh
 [ - ]  umountroot
 [ + ]  unattended-upgrades
 [ + ]  urandom
 [ - ]  uuidd
 [ - ]  x11-common
pulsys@lib-zk1:~$
```

```
pulsys@lib-solr1:~$ sudo service --status-all
...
 [ + ]  rsyslog
 [ - ]  screen-cleanup
 [ - ]  sendsigs
 [ + ]  ssh
 [ + ]  udev
 [ + ]  ufw
 [ - ]  umountfs
 [ - ]  umountnfs.sh
 [ - ]  umountroot
 [ + ]  unattended-upgrades
 [ + ]  urandom
 [ - ]  uuidd
pulsys@lib-solr1:~$
```

**Comment by jrgriffiniii** [comment]
`SOLR_HEAP` was far too high, and needed to be adjusted to `4G`:
https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.solrcloud/defaults/main.yml#L42

Further, `ZK_HOST` values do not resolve, as `/etc/hosts` has entries for `lib-zk{1,2,3}.princeton.edu` (and the Vagrantfile does not provision more than one by default):
```
pulsys@lib-solr1:~$ cat /etc/hosts
...
10.0.15.11 lib-zk1.princeton.edu
10.0.15.12 lib-zk2.princeton.edu
10.0.15.13 lib-zk3.princeton.edu
```

https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.solrcloud/templates/solr.in.sh.j2#L38

**Comment by jrgriffiniii** [comment]
There seems to be some configuration issue between the Zookeeper node (lib-zk1) and Solr (lib-solr1).  Attempting to work with the `zkCli` yields failures which I cannot immediately trace:
```
pulsys@lib-solr1:~$ sudo /opt/solr/server/scripts/cloud-scripts/zkcli.sh -zkhost lib-zk1.princeton.edu:2181 -cmd list /solr
Exception in thread "main" org.apache.solr.common.SolrException: java.util.concurrent.TimeoutException: Could not connect to ZooKeeper lib-zk1.princeton.edu within 30000 ms
```

However, the service itself on the node is functioning and responsive over the specified port:
```
pulsys@lib-solr1:~$ telnet lib-zk1.princeton.edu 2181
Trying 10.0.15.11...
Connected to lib-zk1.princeton.edu.
Escape character is '^]'.
```

**Comment by jrgriffiniii** [comment]
While I have not made progress regarding this issue, I have found a suitable alternative for providing a development environment in which SolrCloud is deployed using a cluster of three Zookeeper server nodes, provisioned instead using Docker: https://github.com/freedev/solrcloud-zookeeper-docker

**Comment by acozine** [comment]
We're not using Vagrant any more. Obsolete.
