### ISSUE TITLE
Update nginx configuration for the new Marquand catalogs site

### ISSUE THREAD

**Issue by rladdusaw** [pulibrary/princeton_ansible#3993]
Nginx should point to the new catalog page for **https://library.princeton.edu/libraries/marquand/resources/sale**

**Comment by rladdusaw** [comment]
There are two separate urls that display the current sales catalogs:

Table only: https://library.princeton.edu/marquand/resources/sales-catalogs
Table embedded in site page: https://library.princeton.edu/libraries/marquand/resources/sale

One is just the table of catalogs, but the other has two other columns of information.

Should we forward both to the new site, or do we need to do something different with the page containing the embedded table?

**Comment by kevinreiss** [comment]
Both URLs can be redirected to the new site.
