### ISSUE TITLE
Add aws client to imagecat servers

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#3996]
We want to be able to run https://github.com/pulibrary/imagecat-rails/blob/main/data/copy_images.rb from the server. 

The copy on the server from the windows machine to the server is oodles faster than on @leefaisonr's machine. We believe the transfer could happen in a day or two vs a week or more.

We should also get a larger disk on imagecat-staging1 (or production to facilitate the transfer.

```
imagecat-staging1% rsync -a --info=progress2 systems@imagecat2:/var/www/html/imagecat/disk2 /tmp/disk2
systems@imagecat2's password: 
  4,285,188,837  93%    4.79MB/s    0:14:13 (xfr#608364, ir-chk=1186/656025)
rsync: [receiver] write failed on "/tmp/disk2/disk2/2736/A3989/0000.0139.tiff_to.gif": No space left on device (28)
rsync error: error in file IO (code 11) at receiver.c(380) [receiver=3.2.7]

```

**Comment by carolyncole** [comment]
We should really use:
```
rsync -a --include=*.tiff --info=progress2 systems@imagecat2:/var/www/html/imagecat/disk2 /tmp/disk2
```

**Comment by carolyncole** [comment]
tmux:
```
tmux new -s transfer
```

**Comment by leefaisonr** [comment]
This worked! Total turnaround time: ~11 minutes 🎉
```
pulsys@imagecat-staging1:~$ rsync -a --include=*.tiff --info=progress2 systems@imagecat2:/var/www/html/imagecat/disk2 /var/tmp/imagecat
systems@imagecat2's password:
  5,778,275,262 100%    8.42MB/s    **0:10:54** (xfr#826776, to-chk=0/829323)
```

**Comment by carolyncole** [comment]
- [ ] Update transfer documentation to include the server and tmux
- [ ] Deploy New  Imagecat Code to server
- [ ] Run script on server and verify the file transfer
- [ ] Update script running documentation to indicate running the script on the server
- [ ] Rinse and repeat for disks 2-28(?)
