### ISSUE TITLE
Move libwww prod to lib-redis-prod1.princeton.edu

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#4023]
Currently the prod environment is still pointing at lib-redis.princeton.edu. We did this in staging here: https://github.com/pulibrary/princeton_ansible/commit/b74194a19b13e6dba1dfa94d34b91671a662ef42

### Implementation notes
After running this playbook one should run the cache clear action in the production drupal site. The success/failure of this will confirm if the connection is working. Also check the drupal status page for any errors/warnings related to redis: https://library.princeton.edu/admin/reports/status

**Comment by kevinreiss** [comment]
After running this playbook on should run the cache clear action in the production drupal site. The success/failure of this will confirm if the conneciton is working. Also check the drupal for any errors/warnings related to redis: https://library.princeton.edu/admin/reports/status

**Comment by kayiwa** [comment]
closed by this PR https://github.com/pulibrary/princeton_ansible/pull/4539
