### ISSUE TITLE
Tower reports 404s on /websocket

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#4043]
When we deploy code from Ansible Tower, we see a lot of requests to the `/websocket` path that result in 404s. We see these in the nginxplus dashboard (in the entry for Ansible Tower) and in the browser (when looking at the network tab in devtools). 

These errors may reflect attempts to update the playbook in progress. If we can fix these, therefore, we might see real-time updates to our Tower jobs.

Investigation today with @ishasinha1 @lizgarciao @sandbergja @christinach suggests that the problem is in the nginx config. 

Resources:
https://github.com/ansible/awx/issues/1861
https://github.com/ansible/awx/blob/devel/docs/websockets.md
https://stackoverflow.com/questions/76441962/authentication-to-awx-websocket
https://docs.ansible.com/ansible-tower/3.1.0/html/administration/troubleshooting.html#websockets-port-for-live-events-not-working (though we do see requests reaching the server, so this is less likely to be a firewall issue)

Nginx-specific resources:
https://www.nginx.com/resources/wiki/start/topics/examples/forwarded/
https://datatracker.ietf.org/doc/html/rfc7239
https://stackoverflow.com/questions/72557636/difference-between-x-forwarded-for-and-x-real-ip-headers

Possibly related:
https://github.com/ansible/awx/issues/1850

**Comment by sandbergja** [comment]
@ishasinha1 had a good idea of something we could try next: open an SSH tunnel and try accessing the /websocket path through the tunnel

**Comment by jrgriffiniii** [comment]
I am sorry, I am not certain why, but this has suddenly started breaking my attempts to deploy using Ansible Tower for Chrome-based browsers. I am going to attempt to use Firefox in order to address this and do not mean to impose; I just wished to confirm that I too experience this.

**Comment by jrgriffiniii** [comment]
I can also confirm now that using Firefox 118.0.1 does ensure that the web UI function as expected. I apologize again (and hope that this information in some way assists in diagnosing this)

**Comment by acozine** [comment]
Current problems with Tower are caused by the recent update of Ansible Galaxy to a new codebase. We must upgrade our Tower instance to fix that.

**Comment by acozine** [comment]
This could be an nginx configuration issue, see https://github.com/ansible/awx/issues/1861

**Comment by acozine** [comment]
Logs have this error message:

```
2024-01-25 21:00:29,108 DEBUG    [647e0089444c4bef99edbba8d4a74347] awx.analytics.performance request: <AsgiRequest: GET '/websocket/'>, response_time: 0.084s
2024-01-25 21:00:29,109 WARNING  [647e0089444c4bef99edbba8d4a74347] django.request Not Found: /websocket/
2024-01-25 21:00:29,823 DEBUG    [-] awx.main.commands.run_callback_receiver ProjectUpdateEvent.objects.bulk_create(1)
2024-01-25 21:00:32,293 DEBUG    [94ef6cf7497e4c75954ed193112f2de2] awx.analytics.performance request: <AsgiRequest: GET '/websocket/'>, response_time: 0.092s
2024-01-25 21:00:32,294 WARNING  [94ef6cf7497e4c75954ed193112f2de2] django.request Not Found: /websocket/
2024-01-25 21:00:33,254 DEBUG    [c2e6c9dedebc44fba69b6ab8806d041c] awx.analytics.performance request: <WSGIRequest: GET '/api/v2/project_updates/56/events/?not__stdout=&order_by=counter&page=1&page_size=50'>, response_time: 0.158s
2024-01-25 21:00:34,529 DEBUG    [f869d5b5365f46f79a26350c066508f5] awx.analytics.performance request: <AsgiRequest: GET '/websocket/'>, response_time: 0.083s
2024-01-25 21:00:34,530 WARNING  [f869d5b5365f46f79a26350c066508f5] django.request Not Found: /websocket/
```

**Comment by acozine** [comment]
In the Nginx access logs, I see:

```
73.xxx.xxx.xxx - - [26/Jan/2024:14:36:58 +0000] "GET /websocket/ HTTP/1.1" 404 2502 "-" 128.112.IP-of-ansible-control-node:443, 404, 0.091, 0.091"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36" "-"
```
for the IPs of both control nodes.

**Comment by acozine** [comment]
@VickieKarasic found some resources for nginx config for websockets:

https://www.nginx.com/blog/websocket-nginx/
https://nginx.org/en/docs/http/websocket.html

**Comment by acozine** [comment]
@sandbergja filled in a vital piece of the puzzle. These lines:
```
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "Upgrade";
```
mean that the incoming request should be handled by a different protocol (not HTTP/S). Those directives should only be applied to `/websocket/` and not to any other URLs (especially not to `/`, which would alter the protocol for all incoming requests to the site). With a nested definition for `/websocket/` that applied those directives only to the one URL, live updates started working.
