### ISSUE TITLE
Redis DB numbering scheme

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#4046]
Many of our group vars files have an [app]_REDIS_DB environment variable. There are a couple of central redis instances and guidance on what number to use when spinning up new infrastructure would be helpful. Should we maintain or maybe be able to generate a list of numbers already in use?

Running `redis-cli INFO keyspace` will list info about databases that currently have keys, but it's not clear whether this would be sufficient.

**Comment by hackartisan** [comment]
Currently orangelight production and qa are configured to use the new lib-redis-prod1 box. It's not clear from ansible which db number each is using. @maxkadel do you know where I can find this info so I can identify a db number for use on new pulfalight qa infrastructure?

**Comment by maxkadel** [comment]
From the config it looks like it's using named DBs, but maybe that setup is wrong? But it appears to be working? (it's only used for the profiler gem for Orangelight)

See https://github.com/pulibrary/orangelight/blob/main/config/redis.yml

**Comment by hackartisan** [comment]
@maxkadel is it possible they're both just using the default db0? I can't find evidence to support a named db feature.

**Comment by hackartisan** [comment]
I think for now I'll use 3 for pulfalight-qa.

**Comment by maxkadel** [comment]
@hackartisan  - thanks, that's probably what it's doing, I've added a pair of issues to use an environment variable in Princeton Ansible and Orangelight for this - see https://github.com/pulibrary/princeton_ansible/issues/4055 and https://github.com/pulibrary/orangelight/issues/3629
