### ISSUE TITLE
Put libstatic playbook into Ansible Tower

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#4054]
The static sites do not have (or really need) Capistrano, and to deploy updates right now you need to run the libstatic playbook. Some folks who do not have an Ansible environment (such as Esmé) want to be able to deploy updates to these sites, so this would be a good playbook to put into Ansible Tower.

**Comment by acozine** [comment]
The playbook is in [this Tower template](https://ansible-tower.princeton.edu/#/templates/job_template/26/details). I'll leave the ticket open for now, in case it doesn't work correctly. Could you test deploying static sites using the template?

**Comment by maxkadel** [comment]
Thanks @acozine!! 🎉 

I was able to find the template and run it successfully, but for some reason the link wasn't working for me? But it's the same link as far as I can tell when I navigate to the page? Weird. Anyway, I think we're good to close.
