### ISSUE TITLE
[Lib-jobs] Create and vault a new Alma API key

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#4075]
- [x] If you don't have access to the Ex Libris Developer portal, pair with somebody who does so you can get an account.
- [x] Create two new Alma API keys that can POST to the Alma "config" API (we can do this at https://developers.exlibrisgroup.com/manage/keys/).
  - A production key that will talk to alma production
  - A staging key that will talk to alma-psb
- [x] Let @mzelesky know that this has been done.
- [x] Add both API keys to princeton_ansible vault for lib_jobs, set the environment variables appropriately (production key on lib-jobs-prod, staging key on lib-jobs-staging)

**Comment by maxkadel** [comment]
Added to environment variable `ALMA_CONFIG_API_KEY`
