### ISSUE TITLE
[lib_jobs] Check out working copy of SVN EADs repo

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#4113]
Connected to https://github.com/pulibrary/lib_jobs/issues/509
See also some notes on svn credentials at https://github.com/pulibrary/lib_jobs/issues/516

### Approval criteria
- Check out latest copy onto the server `svn checkout svn://lib-svn-prod1.princeton.edu/libsvn/trunk/eads` [pass credentials, which we believe should be in the vault]
- Ensure credentials are not output to command line when running (can use `no_log: true`)

**Comment by regineheberlein** [comment]
Of possible relevance:

The red-bean SVN book has helpful information on credentials caching here: https://svnbook.red-bean.com/en/1.4/svn.serverconfig.netmodel.html#svn.serverconfig.netmodel.credcache

More expansive draft version for 1.8: https://svnbook.red-bean.com/en/1.8/svn.serverconfig.netmodel.html#svn.serverconfig.netmodel.creds

This blog explains the use of a config file with `ssh`: https://highlevelbits.com/2007/04/svn-over-ssh-prompts-for-wrong-username.html

**Comment by maxkadel** [comment]
- Where should these files end up? 
- Should we check out from different servers based on the environment? (i.e. on prod use `svn://lib-svn-prod1.princeton.edu/libsvn/trunk` and on staging use `svn://lib-svn-staging1.princeton.edu/libsvn/trunk`)
- Are we sure that we only need to do this once per server? Should we just check that there's a "trunk" directory in whatever directory we want to put it, and if there's already one, skip the task?
