### ISSUE TITLE
Create playbook & role for allsearch_api 

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#4243]
### Dependencies
Currently does not have a database and does not need Node. Check whether default Rails role adds these, and if so, if you can add some kind of "skip if api_only" tag to those tasks / roles. 
- [x] Ruby 3.2.0
- [x] Bundler 2.4.19
- [x] Passenger
- [x] Postgres
- [x] Datadog (base on Orangelight production setup)

### Playbook
- Can base on Orangelight playbook
  - Do not need mailcatcher
  - Question: Do we need to use the meta/main.yml for role dependencies, or can we put them directly in the playbook?
    - This is something we've discussed recently, to limit the amount of duplicated role running (e.g. the Common role running several times when running a single playbook)
    - I don't know what impact this would have on the Molecule tests in the Role
- Will only have two environments for now, production and staging
- Can we add datadog to the staging server for now, until the production server is up? Or is it hard to remove?

### Role
See [Create a new role instructions in Readme](https://github.com/pulibrary/princeton_ansible#create-a-new-role)
- [ ] Molecule tests
- [ ] Put variables required to get tests to pass in 
  - roles/allsearch_api/default/main.yml 
  - group_vars/allsearch_api/[common | production | staging]
- [ ] Can base scaffold on a simple app, such as [roles/dss](https://github.com/pulibrary/princeton_ansible/tree/main/roles/dss)
- [ ] Right now I don't think we need anything in the tasks/main.yml, but want it available for if / when we need to add things.

### Future work
There will be environment variables we will need to add, including
- [x] Honeybadger API key for app
- [ ] Secrets for Summon
- [ ] Secrets for LibJobs API
- [ ] LibGuldes API

**Comment by sandbergja** [comment]
I didn't realize this ticket existed -- apologies.  #4266 should address most of this ticket.  The rails_role alone, without creating a new role for allsearch_api, was sufficient to get the app deployable to staging.
