### ISSUE TITLE
Adjust Error Handling for the All Search API 

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#4396]
The allsearch api returns 400s with useful JSON data when an empty query is passed, and 500s if it encounters an error, but in both cases, it returns the generic PUL error page (see, e.g., https://allsearch-api.princeton.edu/search/catalog?query=). This may be an issue of needing to change behavior on the load balancer (in the Princeton Ansible NGINX config, probably something to do with the [errors.conf template](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/allsearch-api_prod.conf#L52)). We'd like to return a meaningful error message to client applications.

**Comment by kevinreiss** [comment]
related to #126.

**Comment by kevinreiss** [comment]
Jane will check in with operations on how this change fits in with wider Ansible template re-factor.

**Comment by sandbergja** [comment]
We should wait to adjust the error handling until the allsearch_api nginx config is generated by an ansible template (#4397 )
