### ISSUE TITLE
Update the pulibrary.ruby role to use 2.6 releases

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#442]
The Brightbox package repository now supports Ruby 2.6 releases: https://www.brightbox.com/docs/ruby/ubuntu/

**Comment by kayiwa** [comment]
Only took us a little under a year.  @jrgriffiniii  https://github.com/pulibrary/princeton_ansible/commit/7b1ab374e784087f08ea9757f3a8621da19c6122
