### ISSUE TITLE
Revert configuration changes to solr garbage collection

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#4483]
We made some changes in response to an incident which turned out to have had a cause unrelated to GC / heap settings. Configuration changes were checked in to this repo and deployed to staging, but not to prod. We want to bring this repository and the staging machines back in line with the current state of the production machines.

A complicating factor is that the playbook currently fails.

Acceptance criteria:
- [ ] Revert changes made in https://github.com/pulibrary/princeton_ansible/pull/4067/files
- [ ] Ensure both staging and production have the right configuration

**Comment by hackartisan** [comment]
Additional earlier work in this area:
- https://github.com/pulibrary/pul_solr/blob/main/architecture-decisions/0003-remove-memory-tuning.md
- https://github.com/pulibrary/pul_solr/blob/main/architecture-decisions/0004-revert-memory-tuning.md

**Comment by hackartisan** [comment]
Since we have ADRs for earlier GC / heap changes, it might be nice to have one for whatever state we end up in here. It could summarize the supporting research and ensure that documentation stays current.
