### ISSUE TITLE
EZproxy Geolite DB download should go to a stable directory

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#452]
Current Step: https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.ezproxy/tasks/main.yml#L120

Unpacks to last updated date ```GeoLite2-City_YYYYMMDD``` right now. Create a symlink with a stable name to the current directory name.

**Comment by acozine** [comment]
@kevinreiss the file has changed - now we're doing: https://github.com/pulibrary/princeton_ansible/blob/main/roles/ezproxy/tasks/main.yml#L121

Is this ticket still needed?

**Comment by acozine** [comment]
Closing per Kevin's comment.
