### ISSUE TITLE
Move Friends of PUL Asset files to Drupalweb share

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#4525]
Currently assets are in /var/www/friends_of_pul/shared/files.

Move these to /mnt/diglibdata/drupalweb. 

- [ ] On the mount create a fpul_production directory
- [ ] On the mount create a fpul_production directory
- [ ] the www-data user needs to be able to write to both these directories
- [ ] Move files from /var/www/friends_of_pul/shared/files on fpul-prod to the directories created in the first two steps. 
- [ ] Update the capistrano routine in friends_of_pul to include a task like this one from pul_library_drupal to make a symlink to the new fileshare directory.

**Comment by kayiwa** [comment]
Migrated to OIT infrastructure
