### ISSUE TITLE
Allow apache to handle very large cookie headers

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#4532]
#4530 fixed this issue for applications that use passenger, but we also observed this behavior on the library website, which uses apache.

Steps to recreate this issue in your browser are here: https://docs.google.com/document/d/1irv4XN10Ttzs162kbnM7wgJOHyhIeUrtml_Sf9SXrQw/edit#heading=h.knk2u3ipv034

**Comment by acozine** [comment]
Setting `LimitRequestFieldSize 16380` (up from the default of 8190) on the staging server fixed the problem. It would still be nice to know where this enormous cookie originates.

**Comment by sandbergja** [comment]
Closed by #4533
