### ISSUE TITLE
Introduce a role for a local cloud storage service (used for testing purposes)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#454]
This is derived from discussions relating to https://github.com/pulibrary/figgy/issues/2556, where Amazon Web Services might be used as a scalable storage solution for Figgy.  What is proposed here is that there be a local service deployed supporting the AWS S3 API (assuming that Amazon Web Services is accepted as a solution for these cases).  This could be used for testing the storage and retrieval of assets, and would be deployed using projects such as https://github.com/minio/minio

**Comment by jrgriffiniii** [comment]
I've also found that Google Cloud Storage clients are using minio for testing purposes: https://github.com/googleapis/google-cloud-python/issues/7336. 
 However, the discussion surrounding storage emulation still seems to be ongoing: https://github.com/googleapis/google-cloud-python/issues/4840

**Comment by acozine** [comment]
If we decide to do this, let's open a ticket in the figgy repo.
