### ISSUE TITLE
Point OCLC Pinyin rules at Github URLs

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#4553]
Current proxy pass rules for the oclc pinyin project to rewrite statements to new Github locations. Updates that need to happen:

- [ ] Remove location rule in [staging](https://github.com/pulibrary/princeton_ansible/blob/644d708a4545086bda5dc77ccc7b0ca8bd6a2b01/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf#L90-L95). 
- [ ] Remove location in [production](https://github.com/pulibrary/princeton_ansible/blob/644d708a4545086bda5dc77ccc7b0ca8bd6a2b01/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf#L90-L95).
- [ ] Add rewrite rule in main [libwww web config](https://github.com/pulibrary/princeton_ansible/blob/644d708a4545086bda5dc77ccc7b0ca8bd6a2b01/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf) that sends https://library.princeton.edu/eastasian/oclcpinyin/ to https://github.com/pulibrary/oclcpinyin
- [ ] Add rewrite rule in main [libwww web config](https://github.com/pulibrary/princeton_ansible/blob/644d708a4545086bda5dc77ccc7b0ca8bd6a2b01/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass.conf) that sends https://library.princeton.edu/eastasian/addpinyin-plugin-marcedit to https://github.com/pulibrary/addpinyin-marcedit
- [ ] Follow [instructions](https://github.com/pulibrary/pul-it-handbook/blob/main/services/nginxplus.md#only-upload-the-new-config-files) to deploy new ngnix plus playbook config

**Comment by tventimi** [comment]
Implemented steps 1-4 in PR #4555
