### ISSUE TITLE
Redirect PUDL viewer URLs

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#4566]
We redirected most of the PUDL URLs that contain ARK IDs so the old URLs will get users to the new location of the content. But we just had a report from a user that this URL wasn't working:

`https://pudl.princeton.edu/viewer.php?obj=2801pg40q#page/143/mode/2up`

we should redirect that pattern:

`pudl.princeton.edu/viwer?obj=[X]` -> `arks.princeton.edu/ark:/88435/[X]`

**Comment by acozine** [comment]
I think this needs to be added to https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/pudl_proxy_pass.conf.

**Comment by escowles** [comment]
@acozine I don't think we need to handle the part of the URL after the "#" — we have a ticket to support linking to individual pages (https://github.com/pulibrary/figgy/issues/5151) but it is not been implemented. Getting the user to the digital object would be a much better experience, even if they have to navigate to the correct page themselves.
