### ISSUE TITLE
Drupal installation fails with `php extensions: Disabled` when testing on Travis CI

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#459]
This was encountered when running tests using Python 3.7 on Ubuntu 16.04 LTS.  Please see the following:

<img width="993" alt="princeton_ansible_issues_drupal" src="https://user-images.githubusercontent.com/1443986/53763201-1d5b8900-3e98-11e9-9382-d58e1a8617d5.png">

(https://travis-ci.org/pulibrary/princeton_ansible/jobs/501642791#L156)

**Comment by jrgriffiniii** [comment]
This is also affecting builds for Python 2.7 also.

**Comment by jrgriffiniii** [comment]
This seems to be affecting https://travis-ci.org/pulibrary/princeton_ansible/builds/501642789 pretty consistently, it might block https://github.com/pulibrary/princeton_ansible/pull/458 from passing.

**Comment by kayiwa** [comment]
Fixed by simplexml 🙄 https://travis-ci.org/pulibrary/princeton_ansible/builds/516180961
