### ISSUE TITLE
Nginx load balancer deploys break existing solr connections

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#4596]
Why does the load balancer affects that since it's managed through zookeeper?

See [@tpendragon  slack comment](https://pulibrary.slack.com/archives/CL8F616KV/p1699043179121879)

See [Orangelight ticket and @rladdusaw comment](https://github.com/pulibrary/orangelight/issues/3911#issuecomment-1896328782)

**Comment by tpendragon** [comment]
Because we connect to solr through the load balancer, which then connects to a solr node, which then connects to zookeeper, which then connects to a solr node.

**Comment by kayiwa** [comment]
heya @christinach this is how we connect to the solr https://github.com/pulibrary/princeton_ansible/blob/5649d65a9ad7cce1d5aa6bd034828628d6861d11/group_vars/bibdata/production.yml#L65
