### ISSUE TITLE
Do we have a universal way to purge AWS logs?

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#4603]
https://github.com/pulibrary/pdc_describe/issues/1658

**Comment by carolyncole** [comment]
I would suggest [a lifecycle rule](https://github.com/pulibrary/pdc_describe/pull/1972/files?short_path=651f358#diff-fcb644846a9114e8c6aa730bf17067f2eeaffcdc9bad84d16002bf8b3a36b2dc) that expires the files after 60 days like outlined in the linked PR.  @kayiwa @acozine how does that sound?

**Comment by acozine** [comment]
When changes happen in an S3 bucket, the changes are logged to another bucket. We had 100s of GB of logs. Setting a lifecycle rule automatically cleans these up, and also reduces our bill (because even if the files are not immediately removed, AWS stops billing us for them on the date of our rule).

**Comment by acozine** [comment]
We looked in AWS and do not see other log buckets. We think this is solved, and if we do something similar in future, 60 days seems like a great limit.
