### ISSUE TITLE
Add playbook for adding CheckMk agent to pdc_describe machines

### ISSUE THREAD

**Issue by leefaisonr** [pulibrary/princeton_ansible#4648]
Instructions for adding the agent can be found here: https://github.com/Checkmk/ansible-collection-checkmk.general/tree/main/roles/agent

Acceptance criteria: 
- [x] we can ssh into the box
- [ ] ~~`sudo service checkmk-agent status` returns something other than "service not found/is off"~~
- [x] `sudo cmk-agent-ctl status` returns something other than `cmk-agent-ctl: command not found`
- [x] we can replicate this on multiple machines

**Comment by acozine** [comment]
Closed by #4652
