### ISSUE TITLE
Bundler miss match with passenger

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#4663]
When you install a new ruby and a new passenger gem gets installed.  That gem likes a certain version of bundler to be available.

I have outlined a manual process for reconciling the bundler version here https://github.com/pulibrary/pul-it-handbook/pull/248

What should really be done with passenger.  @hackartisan mentioned that the latest bundler will just download and install the correct version.  Maybe we should stop installing different versions of bundler and just use what gets installed with ruby?

**Comment by hackartisan** [comment]
Here's documentation of how that works in bundler: https://bundler.io/blog/2022/01/23/bundler-v2-3.html

**Comment by hackartisan** [comment]
The passenger error you get looks like `can't find gem bundler (= 2.5.6) with executable bundle (Gem::GemNotFoundException)`

**Comment by hackartisan** [comment]
Can we avoid a world where we have to have a million PRs that look like https://github.com/pulibrary/princeton_ansible/pull/4661/files ?

**Comment by carolyncole** [comment]
I just noticed... `- name: ruby_s | remove installed bundler if default` should happen before `- name: ruby_s | uninstall wrong version of bundler` for the uninstall to work correctly

Maybe passenger would be happy if there was not two versions of bundler installed??

**Comment by carolyncole** [comment]
We just decided in cross team that we should start removing the version from projects as we run the playbooks.  Leave the code for now, with the knowledge that is doesn't work without manual intervention
https://docs.google.com/document/d/1AllskD7tY3mGIc7qVqqs46zSVDGHXckFSl_G1BFJiUg/edit#heading=h.3ejetkruiwxz
