### ISSUE TITLE
[openbooks] Add OpenBooks to Pony Express

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#4679]
Add OpenBooks [openbooks-prod1 and openbooks-prod2](https://github.com/pulibrary/princeton_ansible/blob/22c1045e0fba4e0527765ebc9ea00c2ddeb3a988/inventory/all_projects/openbooks#L4) to Pony Express so the service can send email.

**Comment by kayiwa** [comment]
servers added to the allow list and postfix was configured with a `smarthost`
