### ISSUE TITLE
Shut down annotations servers

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#4745]
Please shut down https://annotations.princeton.edu/ and https://annotations-staging.princeton.edu/ according to standard Ops procedures. Let me know if I can add any additional information to this ticket.

**Comment by VickieKarasic** [comment]
Hi @kelynch, I'll be working on this one. We will decommission the servers according to [standard procedures](https://github.com/pulibrary/pul-it-handbook/blob/main/services/decommissioning.md). Usually, we wait 30 days after turning off a server to start the deletion process. Would you like 30 days or would shorter (say, 14 days/2 weeks) suffice in this case? Happy to proceed however you think is best. Thanks!

**Comment by VickieKarasic** [comment]
We will wait the 30 days per Kate's request and will begin decommissioning the week of April 8, 2024.

**Comment by VickieKarasic** [comment]
Decommissioning complete and closed by #4839
