### ISSUE TITLE
add oawaiver back to full capacity

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#4790]
with the increased capacity we can now add oawaiver-staging1 and oawaiver-prod1 
Get old [MAC addresses](https://networkregistration.princeton.edu)

- [x] oawaiver-staging1
- [x] oawaiver-prod1
- [x] Uncomment names on inventory oawaiver-staging1
- [x] run playbook (for staging)
- [x] Uncomment names on inventory oawaiver-prod1
- [x] run playbook (for production)

**Comment by acozine** [comment]
The current oawaiver-prod1 is a Bionic box. Decommission that one, and build a new one on Jammy.

**Comment by VickieKarasic** [comment]
Closed by #4802 and #4803. See #3897 for decommissioning the bionic oawaiver-prod1 VM.
