### ISSUE TITLE
Upgrade redis for bibdata

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#4795]
Make sure that bibdata is pointing toward redis that is compatible with sidekiq pro 7.  It can be local, or the shared redis.

See also:

- https://github.com/pulibrary/princeton_ansible/issues/2799
- https://github.com/pulibrary/bibdata/pull/2143

**Comment by maxkadel** [comment]
Sidekiq pro 7 requires redis Redis 6.2 or higher, the bibdata servers now have Redis 7.2.4, so this should be fine. Bibdata currently uses local redis.

I will create a branch that updates Sidekiq-pro and confirm that it works on bibdata staging.
