### ISSUE TITLE
Set open file limit to be higher on Solr boxes

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/princeton_ansible#480]

**Comment by tampakis** [comment]
Interestingly lib-solr1 and lib-solr3 still had the high ulimit. It didn't appear on lib-solr2

**Comment by kayiwa** [comment]
what user are you looking at the ulimits for?

**Comment by tampakis** [comment]
Hey btw i'm working on a PR for this to add to the solrcloud. I checked out the /etc/security/limits.conf file

**Comment by tampakis** [comment]
I figured I would add a new template

**Comment by kayiwa** [comment]
> Hey btw i'm working on a PR for this to add to the solrcloud. I checked out the /etc/security/limits.conf file

place that in /etc/limits/limits.d/ please.

**Comment by tampakis** [comment]
ok!
