### ISSUE TITLE
[central Redis] Upgrade to Redis 6.2.0 or higher

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#4841]
When I tried to point bibdata production workers to the lib-redis-prod1 central redis server, I got the error "You are connecting to Redis 6.0.16, Sidekiq requires Redis 6.2.0 or greater" - since the central Redis servers are mainly used for Sidekiq, we should upgrade them. 

```
Apr 10 09:27:02 bibdata-alma-worker1 sidekiq[374594]: 2024-04-10T13:27:02.236Z pid=374594 tid=7wiq INFO: Sidekiq 7.2.2 connecting to Redis with options {:size=>10, :p>
Apr 10 09:27:02 bibdata-alma-worker1 sidekiq[374594]: You are connecting to Redis 6.0.16, Sidekiq requires Redis 6.2.0 or greater
```

In addition, the redis staging and qa servers are v.7.2.4, so we should make staging and production match. 

```bash
pulsys@lib-redis-staging1:~$ redis-server --version
Redis server v=7.2.4 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=f3f64f8946d94cb2
```

```bash
pulsys@lib-redis-qa1:~$ redis-server --version
Redis server v=7.2.4 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=f3f64f8946d94cb2
```

```bash
lib-redis-prod1% redis-server --version
Redis server v=6.0.16 sha=00000000:0 malloc=jemalloc-5.2.1 bits=64 build=a3fdef44459b3ad6
```

### Implementation notes
- [Documentation on upgrading Redis without downtime](https://redis.io/docs/latest/operate/oss_and_stack/management/admin/)
- It looks like there is a [playbook to upgrade Redis](https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/redis_upgrade.yml), but I don't know if that is how the other central redis servers were upgraded, or how it might impact live services

**Comment by tpendragon** [comment]
Running the upgrade Redis playbook resulted in:

`redis-server` wouldn't successfully start
No logs were upgraded
`dump.rdb` got upgraded to the newer format.

I suspect it's close to working, there must just be some config problem or something.

**Comment by acozine** [comment]
Could we build a box with Redis 7 installed, then migrate? That would give us an easy rollback option and the ability to troubleshoot any config issues without interrupting production.

**Comment by acozine** [comment]
Guess as to the config issue - if you don't enable IPv6, redis fails to start. See [this issue](https://github.com/geerlingguy/ansible-role-redis/issues/39).

**Comment by acozine** [comment]
Alternatively, @kayiwa could try this again in the maintenance window, first backing up the redis DB in case we need to rollback.

**Comment by kayiwa** [comment]
```bash
pulsys@lib-redis-prod1:~$ dpkg -l | grep redis-server
ii  redis-server                           6:7.2.4-1rl1~jammy1                     amd64        Persistent key-value database with network interface
pulsys@lib-redis-prod1:~$ redis-server --version
Redis server v=7.2.4 sha=00000000:0 malloc=jemalloc-5.3.0 bits=64 build=f3f64f8946d94cb2
```
