### ISSUE TITLE
Make sure logrotate is enabled on pdc-describe

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#4871]
### Expected behavior
log rotate should be an enabled service and running on PDC describe.  It is currently disabled.

### Actual behavior
logrotate is currently disabled on pdc-describe-staging1 & pdc-describe-staging2

### Steps to replicate
ssh pulsys@pdc-describe-staging1
systemctl status logrotate

### Impact of this bug
logs are just getting larger

## Acceptance criteria
- [ ] The ansible playbook is updated to ensure log rotation is enable
- [ ] The playbook has been run on all instances

**Comment by bess** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/princeton_ansible/4871?planning-poker) with Zenhub @carolyncole @hectorcorrea @JaymeeH @jrgriffiniii

**Comment by bess** [comment]
Logrotate DOES appear to be enabled for this system, as it is enabled by default. It runs via cron, so a systemctl call might appear as if it is not running. We need to think about how to monitor this, and that's blocked until we know how to write a custom checkmk check.
