### ISSUE TITLE
[bibdata] Create new bibdata-qa VMs

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#4882]
I missed that I left a duplicate SQS poller role in the bibdata playbook, and ran the playbook, and now the service is on all the bibdata-qa boxes, which was exactly what we were re-building the box to avoid. [Made a PR to fix that](https://github.com/pulibrary/princeton_ansible/pull/4881).

DNS names - can blow away the old boxes and I'll rebuild them once they're ready.

- [x] bibdata-qa1.princeton.edu
- [x] bibdata-qa2.princeton.edu
- [x] bibdata-worker-qa1.princeton.edu
- [x] bibdata-worker-qa2.princeton.edu

**Comment by kayiwa** [comment]
VMs are ready.
