### ISSUE TITLE
remove deny001 -> 091 from PanOS

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#4888]
### What maintenance needs to be done?

Remove all the Deny Rules on the PanOS and add them to the AWS managed drop list.

Please use [IPInfo](https://ipinfo.io/) for labels to distinguish which IPs are blocked for future audit use

### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Acceptance criteria
 - [x] All Denied IPs are listed in a single place
 - [x] Document the process for add an IP to the Drop List

### Implementation notes, if any

When you delete a handful, update panOS and SNOW which deletion rules. 
Each Service Now ticket will include link to PR on Prancible

**Comment by Beck-Davis** [comment]
Documentation for process of adding an IP to the Drop List : https://github.com/pulibrary/pul-it-handbook/pull/284
