### ISSUE TITLE
Decommission denylist.pulcloud.io

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#4890]
### What maintenance needs to be done?

Decommission the GCP ban-list server.

### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Why is this maintenance needed?

When we first created the consolidated deny list, we built an OpenBSD server in GCP, installed nginx, and served the denylist file out of it. #4872 updated the implementation to serve the denylist out of an s3 bucket. When we are confident that the s3 solution meets all our needs, we can decommission the GCP server.

**Comment by kayiwa** [comment]
deleted TLS cert `doas acme-client -r denylist.pulcloud.io` 
shutdown server `doas /sbin/halt -p` 
deleted DNS name
