### ISSUE TITLE
Firewall playbook sometimes returns the wrong object

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#4892]
### Expected behavior

When I run the firewall playbook and pass any FQDN, it retrieves the IP for that FQDN and finds the matching object in the firewall.

### Actual behavior

With certain IP addresses, the playbook displays the wrong object. See https://ansible-tower.princeton.edu/#/jobs/playbook/1493/output.

This happens when the last segment of the IP address is short. The task that queries the firewall is retrieving a list of matches (for example, if it's searching for `111.222.33.4` it matches `111.222.33.40` and `111.222.33.487` as well as the exact match) and our display is only presenting the first item in the list. 

This happens because we are using `value contains` plus the IP as our filter [here](https://github.com/pulibrary/princeton_ansible/blob/833abec2f664b314ce08372ad0bbb846c26a6345/playbooks/utils/firewall_update.yml#L34). In the example above, any IP with `.4x` or `.4xx` as the last segment will match, because they all contain `.4`. We used `value contains` because not all objects in the firewall have `/32` at the end of the IP definition.

### Steps to replicate

Run the firewall playbook and pass `pulcheck-staging1.princeton.edu` as the VM you're curious about. 

### Impact of this bug

We can't trust the output of the firewall playbook in all cases.

### Implementation notes, if any

We can change the playbook to display all matches. Or we can clean up our firewall data so all entries have `/32` and we can filter more exactly. If we want to do the latter, we can write a playbook that pulls all object data out of the firewall, then go through it to generate a list of IPs that need `/32` added to the end. We might even try automating that update as our first non-read-only firewall task.

**Comment by kayiwa** [comment]
We tested three candidate IPs. 

In all cases. The results will prioritize the older device on the palo alto database. For example. Search for the 

lib-adc-staging.princeton.edu (with the ***.***.203.5) IP results in something similar but wrong result of Lib-TripW (with the ***.***.203.51) 

All these IP's have CIDR notation in their entries suggesting that we will need to find a way to manipulate the PanOS filter rules.
