### ISSUE TITLE
[tower-deploy] Update known_hosts file when new machines are built

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#4899]
### What maintenance needs to be done?
When a new server is built using a pre-existing FQDN name, we want to be able to deploy to it using Tower without manually updating the known_hosts file.

As an example of what the failure looks like, see this [Ansible Tower deploy to bibdata-qa](https://ansible-tower.princeton.edu/#/jobs/playbook/1546/output) after the servers were re-built.

### Level of urgency
- [ ] High
- [x] Moderate - 
- [ ] Low

### Why is this maintenance needed?
This will be needed to make automatically provisioning new VMs sufficiently cheap to do it all the time, which will allow us to iterate on and improve our infrastructure much faster.

### Acceptance criteria
 - [x] When a server is built with the same FQDN, I can deploy to it without ssh'ing into the tower deploy server and doing anything manual there

### Implementation notes, if any
There is an [Ansible known_hosts module](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/known_hosts_module.html), not sure yet if it matches our use case.

**Comment by kayiwa** [comment]
This is not an ansible problem (certainly not the process of ssh connection)

Rather this is the deploy user from tower connecting to the remote VM to run capistrano.

**Comment by kayiwa** [comment]
Does capistrano have a ignore ssh

**Comment by acozine** [comment]
If we can get the deploy playbook to run in an EE on Tower itself, we will solve this problem, because the EE is always "fresh". So far I have not gotten the EE to work, though - see https://github.com/pulibrary/princeton_ansible/pull/4744.

**Comment by acozine** [comment]
Closed by #5215. That PR adds a task that updates the `known_hosts` file on the `tower-deploy1` VM.
