### ISSUE TITLE
Investigate the usage of SolrCloud for archivesspace Playbooks

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#491]
Currently ArchivesSpace installations are monolithic, and run the Solr server locally on a single server node.

**Comment by jrgriffiniii** [comment]
Please see http://archivesspace.github.io/archivesspace/user/running-archivesspace-with-external-solr/ for reference.

**Comment by acozine** [comment]
@jrgriffiniii is this still relevant?

**Comment by eliotjordan** [comment]
ArchivesSpace is now hosted and we are planning on deleting the playbook.
