### ISSUE TITLE
allow new aspace-staging IP to connect to lib-sftp-staging1

### ISSUE THREAD

**Issue by regineheberlein** [pulibrary/princeton_ansible#4922]
Allow aspace-staging (44.225.143.31) to connect to lib-sftp-staging1.

### Background 

ArchivesSpace is being bumped to v3.5. We're skipping two versions. It is on us to make sure that all our plugins still work with the new version, so we've had aspace-staging upgraded first.

We now need to make sure that the as_marcao plugin still works with the new version. 

Also see https://github.com/pulibrary/aspace_helpers/issues/546

**Comment by regineheberlein** [comment]
Related to https://github.com/pulibrary/princeton_ansible/issues/4879

**Comment by kayiwa** [comment]
FW rules are updated.
