### ISSUE TITLE
mislabeled names

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#4992]
### Expected behavior

In adding new hosts on the allow list the following machines do not have a label that matches DNS. The list was generated from the current relay server that uses IP addresses. When trying to use DNS we get unexpected results

### Actual behavior

The table below has:

 current relay name - ip address - DNS

- [x] Lib-Screen01a - 128.112.201.243 - lib-dssproc04.princeton.edu
- [x] Lib-Screen02a - 128.112.201.254 - lib-staff996.princeton.edu
- [x] Lib-Screen01b  - 128.112.202.37 - lib-pubsa130.princeton.edu
- [x] Lib-Screen02b - 128.112.202.48 - lib-dstation08.princeton.edu
- [x] Lib-VDP01-61 - 128.112.203.11 - lib-imr04zp.princeton.edu
- [x] Lib-VDP02-61 - 128.112.203.13 - lib-vrestwin.princeton.edu

### Impact of this bug

Adding names to the relay that we are unsure of seems like trouble.

### Implementation notes, if any

Change the hostnames of these to match the relay label

**Comment by VickieKarasic** [comment]
Lib-VDP01-61 and Lib-VDP02-61 are non-operational according to the CMDB. The first four machines have been addressed and that closes this ticket.
