### ISSUE TITLE
[CHECK_MK] Add monday maintenance window for staging monitor

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#5012]
We got a ton of noise when the staging servers were upgraded on Monday June 3 in the RDSS team channel.  I would like us to look into how to add a maintenance for the staging servers.  

If this ticket is being worked after the production servers are configured we should also look at putting in a window for the Tuesday patch of production.

**Comment by acozine** [comment]
We set up a time period in staging CheckMK to match our official maintenance window, which is weekdays from 6:30 to 8:00 Eastern time. Then we added a time period for "all the times that are not  the maintenance window" and set notifications to be active only in that time period. 

We also tested backup/restore and discovered that all configuration, including time periods, gets transferred with a backup/restore.
