### ISSUE TITLE
[loadtest] Cannot create sufficient load to stress Solr

### ISSUE THREAD

**Issue by maxkadel** [pulibrary/princeton_ansible#5019]
### Expected behavior
We can ramp up the number of threads and requests to Solr using JMeter to start hitting Solr-related errors, to see when we are genuinely stressing Solr.

### Actual behavior
Before we start getting Solr errors, we get the JMeter error below:

```
Non HTTP response code: java.net.BindException/Non HTTP response message: Cannot assign requested address
```

See, for example, the errors on the [test run on June 3, 2024](https://loadtest.lib.princeton.edu/solr_tests/test_results-2024-06-03%3A19%3A12%3A43/)

### Steps to replicate
Follow the steps in the [solr_load_testing README](https://github.com/pulibrary/solr_load_testing?tab=readme-ov-file#running-from-loadtest1libprincetonedu) for testing reads.

### Impact of this bug
We cannot truly stress the system, making our load tests less meaningful

### Implementation notes
I am not actually sure whether the error stems from the loadtest machine or the Solr machine.

**Comment by kayiwa** [comment]
I bumped the memory and CPU (the error seems to suggest this is the problem) on the VM. Could you please test this @maxkadel

**Comment by maxkadel** [comment]
I tried testing this and am still seeing the same error (See [today's test report](https://loadtest.lib.princeton.edu/solr_tests/test_results-2024-06-26%3A18%3A33%3A59/)).

I'm going to try prefacing the command with the `JVM_ARGS` from @sandbergja's PR to see if they help (`JVM_ARGS="-Xms2048m -Xmx2048m"`)

**Comment by acozine** [comment]
We got rid of the error by hitting an individual Solr VM instead of the load-balanced URL, after updating the firewall to allow the private .lib subnet to access the Solr port.
