### ISSUE TITLE
new cdh-prodigy vms

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#5026]
### What maintenance needs to be done?
Can we please create vms for the following project.

### Level of urgency
- [x] High
- [ ] Moderate
- [ ] Low

### Why is this maintenance needed?
- CDH needs to set up infrastracture for prodigy.cdh.princeton.edu

### Acceptance criteria
 - [x] a staging environment with cdh-test-prodigy{1,2}
 - [x] a production environment with cdh-prodigy{1,2}
 - [x] TLS name for prodigy.cdh.princeton.edu

**Comment by rlskoeser** [comment]
test site public name test-prodigy.cdh.princeton.edu
