### ISSUE TITLE
Turn off/delete the locator VMs

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#5051]
### What maintenance needs to be done?

- [x] Decommissioning [these vms](https://github.com/pulibrary/princeton_ansible/blob/main/inventory/all_projects/locator)
- [ ] Removing all the locator stuff from princeton_ansible

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
This application is no longer used (we use stackmaps instead).

### Implementation notes, if any

- [x] delete nginx locator-staging and prod configuration
  - [x] delete aliases on lib-adc 
- [x] delete ansible locator role
- [x] delete locator-staging1 and locator-prod1 vms
- [x] delete DNS for VMS
- [x] delete firewall rules

**Comment by VickieKarasic** [comment]
We network disconnected these on 6/28/24. We will power down on 7/2/24, and start decommissioning process on 7/9/24.

**Comment by Beck-Davis** [comment]
locator-staging1 and locator-prod1 were powered off on 7/2/24

**Comment by acozine** [comment]
You can also follow the documentation for [decommissioning](https://github.com/pulibrary/pul-it-handbook/blob/main/services/decommissioning.md) - and improve it if necessary!

**Comment by acozine** [comment]
We had added locator-staging1 to our staging CheckMK installation - I've removed it manually but we should add a step for removing servers as part of decommissioning.
