### ISSUE TITLE
Retire library.princeton.edu Proxy pass rules for lib-static-prod/staging domains.

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#5075]
All current rules to this domain should be converted to redirects.

- [x] #5146
- [x] Update NGINX config for the staging domain to proxy pass back to all the sites on lib-static-staging.princeton.edu. 
- [x] Test proxy pass rules on staging
- [x] All current proxy pass rules for library-staging.princeton.edu back to the lib-static-staging domain should be converted to global redirect rules to the same path on static-staging.lib.princeton.edu. Test that the redirect rules work.
- [x] Update NGINX config for the new production domain to proxy pass back to all the sites on lib-static-prod.princeton.edu. 
- [x] Test proxy pass rules on production
- [x] All current proxy pass rules for  library.princeton.edu back to the lib-static-prod domain should be converted to global redirect rules to the same path on lib-static-prod. Test that the redirect rules work.
- [x] Purge [Current Staging proxy rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf#L14-L51) and https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-staging.conf#L103-L109
- [x] Purge [Current Production proxy rules](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf#L19-L52) and https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/templates/libwww-proxy-pass-prod.conf#L61-L67
- [x] delete lib-static-staging1.princeton.edu firewall rules
- [x] delete lib-static-prod1.princeton.edu firewall rules

**Comment by VickieKarasic** [comment]
Closed by #5250
