### ISSUE TITLE
hostnames for cdh-prodigy1 and cdh-prodigy2 show as lib-vm

### ISSUE THREAD

**Issue by rlskoeser** [pulibrary/princeton_ansible#5086]
### What maintenance needs to be done?

When I ssh to cdh-prodigy1 and cdh-prodigy2, the hostname shows up as "lib-vm" instead of the expected cdh-prodigy{1,2}

### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Why is this maintenance needed?
It's confusing to ssh in and not know what machine I'm on.  I'm not sure if this affects anything else.

### Acceptance criteria
 - [ ] When I ssh into the VM I should see the expected hostname

**Comment by kayiwa** [comment]
manually run

`sudo perl -pi -e s/lib-vm/cdh-prodigy2/g /etc/hosts`
`sudo perl -pi -e s/lib-vm/cdh-prodigy2/g /etc/hostname`

and

`sudo perl -pi -e s/lib-vm/cdh-prodigy1/g /etc/hosts`
`sudo perl -pi -e s/lib-vm/cdh-prodigy1/g /etc/hostname`
