### ISSUE TITLE
[openpublishing] Redirect OJS URL to Manifold

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#5087]
Redirect traffic to [https://openpublishing.princeton.edu/](https://openpublishing.princeton.edu/) to go to [https://princeton-manifold-production.softserv.cloud/](https://princeton-manifold-production.softserv.cloud/).

I'll make separate tickets to decommission the OJS and OMP servers later once I've confirmed the timeline with our PO.

**Comment by kayiwa** [comment]
1. Deleted DNS name
2. Created new CNAME by way of [OIT](https://princeton.service-now.com/service?sys_id=abc63c584717c6d0af3bb099126d4373&view=sp&id=ticket&table=sc_req_item)
