### ISSUE TITLE
remove delete manifold infrastructure

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#5092]
### What maintenance needs to be done?

- [ ] Decommissioning [these vms](https://github.com/pulibrary/princeton_ansible/blob/main/inventory/all_projects/manifold)
- [ ] Removing all the manifold stuff from princeton_ansible

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?

This app will live under a different [openbooks](openbooks.princeton.edu) name

### Implementation notes, if any

- [x] delete nginx manifold-staging and prod configuration
  - [x] delete aliases on lib-adc 
- [ ] delete ansible manifold role
- [x] delete manifold-staging1 and manifold-prod1 vms
- [x] delete DNS for VMS
- [x] delete firewall rules

**Comment by Beck-Davis** [comment]
@kayiwa your link under What maintenance needs to be done is broken.  Was there information necessary to complete the ticket in it?

**Comment by Beck-Davis** [comment]
- disconnected manifold-staging1 from network in vsphere on 7/11/24.
- could not find manifold-prod1 in vsphere.

Will power off manifold-staging1 on 7/18/24

**Comment by Beck-Davis** [comment]
manifold-staging 1 powered off on 7/18/2024. Will complete VM decommission on 7/25/2024.

**Comment by Beck-Davis** [comment]
manifold-staging1
- deleted from disk
- deleted network registration
- Hardware Firewall changes
  - removed rules
  - removed object
- removed alias from loadbalancer
