### ISSUE TITLE
[RePec] Use health.json for health checks

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#5111]
### What maintenance needs to be done?

When RePec's health checks are failing (health.json), it should not serve that application to the public.

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?

This will make it easier and safer to deploy to only some of the machines, because we won't have to adjust the nginx configuration to take things off the load balancer just in case it breaks.

### Acceptance criteria
 - [ ] When one node is broken it does not get traffic diverted to it.
 - [ ] It checks `/health.json`

### Implementation notes, if any

Nginx Documentation: https://docs.nginx.com/nginx/admin-guide/load-balancer/http-health-check/
Existing health check configuration: https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/lib-jobs-staging.conf

### First Step

Add the health check URL to the staging configuration.

**Comment by tpendragon** [comment]
This is at http://repec-prod.princeton.edu and repec-staging.princeton.edu
