### ISSUE TITLE
Decommission Lib-monitor1

### ISSUE THREAD

**Issue by dphillips-39** [pulibrary/princeton_ansible#5118]
### What maintenance needs to be done?
We are not using Lib-monitor1 any more. Let's decommission it.

### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Relevant deadlines
If this maintenance relates to an End of Life date or other deadline, please enter it here.
- [x] None

### Why is this maintenance needed?
- We would like to make efficient use of our resources and we do not want to maintain machines that are no longer in use. 

### Acceptance criteria
 
- [x]  delete nginx lib-monitor1 [configuration](https://github.com/pulibrary/princeton_ansible/blob/b6e4b9c032fba8c32638857860ec9acacd744537/roles/nginxplus/files/conf/http/lib-monitor.conf#L6)
- [x]  delete aliases on lib-adc
- [x]  delete lib-monitor1 vm
- [x]  delete lib-monitor1 from [inventory](https://github.com/pulibrary/princeton_ansible/blob/b6e4b9c032fba8c32638857860ec9acacd744537/inventory/all_projects/_orphans#L8)
- [x]  delete DNS for the VM
- [x]  delete firewall rules

**Comment by acozine** [comment]
We disconnected the lib-monitor1 VM from the network on July 5, 2024.
