### ISSUE TITLE
Create 2 VMs for Mediaflux ansible build

### ISSUE THREAD

**Issue by bess** [pulibrary/princeton_ansible#5124]
We need two virtual machines for creating a mediaflux ansible build. One will be for running automated CI on tiger data app, the other will be for testing our front end against. 

We don't have much information yet about how beefy the boxes need to be. The license keys we will get are tied to a mac address. Hopefully we can add resources to the box and keep the same mac address if we need to. 

The boxes should be called:

- [x] mediaflux-ci.princeton.edu
- [x] mediaflux-staging.princeton.edu
- [x] Ports 22 (ssh) and 443 (https) should be open behind the VPN

**Comment by kayiwa** [comment]
Instructions are on [Ops Catchall KVM](https://github.com/pulibrary/ops-catchall/blob/main/projects/vsphere_hypervisor.md)

**Comment by kayiwa** [comment]
Any ports you expect opened of the Firewall? @bess

**Comment by bess** [comment]
mediaflux-staging [00:50:56:ac:6b:e8]
Mediaflux-ci [00:50:56:b4:5e:94]
