### ISSUE TITLE
Remove/delete openbooks VMs

### ISSUE THREAD

**Issue by kelynch** [pulibrary/princeton_ansible#5140]
### What maintenance needs to be done?
- [x] Decommissioning vms
- [x] Removing all openbooks stuff from princeton_ansible

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
- These are no longer needed.  We are moving the service to Manifold hosted.

### Implementation notes
- [x]  delete nginx openbooks-staging [configuration](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/openbooks-staging.conf)
- [x] delete nginx openbooks [configuration](https://github.com/pulibrary/princeton_ansible/blob/main/roles/nginxplus/files/conf/http/openbooks.conf)
- [x]  delete aliases on [lib-adc](https://princeton.service-now.com/service?id=sc_cat_item&sys_id=b28546e14f09ab4818ddd48e5210c756&sysparm_category=0c0591f14f9d270c18ddd48e5210c79c)
- [x]  delete vms
  - [x] openbooks-prod1
  - [x] openbooks-prod2
  - [x] openbooks-staging1
  - [x] openbooks-staging2 
- [x]  delete openbooks from [inventory](https://github.com/pulibrary/princeton_ansible/blob/main/inventory/all_projects/openbooks)
- [x]  delete DNS for the VM
- [x]  delete firewall rules
- [x] delete openbooks ansible role

**Comment by Beck-Davis** [comment]
Disconnected from network. Will power down on 7/31/24
openbooks-staging2
openbooks-prod1
openbooks-prod2

Did not see openbooks-staging1 in vSphere

**Comment by Beck-Davis** [comment]
Deleted from disk:
openbooks-staging2
openbooks-prod1
openbooks-prod2

removed firewall rules for :
openbooks-staging1
openbooks-staging2
openbooks-prod1
openbooks-prod2
