### ISSUE TITLE
Obtain new staging and production domains for static sites managed by the lib-static role

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#5146]
- [x] Staging Domain: static-staging.lib.princeton.edu
- [x] Production Domain: static.lib.princeton.edu
- [x] Assign both domains to the load balancer

**Comment by VickieKarasic** [comment]
lib-static-staging1: ```1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: ens32: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 00:50:56:b4:21:79 brd ff:ff:ff:ff:ff:ff
    altname enp2s0
    inet 128.112.200.89/21 metric 100 brd 128.112.207.255 scope global dynamic ens32
       valid_lft 56575sec preferred_lft 56575sec
    inet6 fe80::250:56ff:feb4:2179/64 scope link
       valid_lft forever preferred_lft forever```

**Comment by VickieKarasic** [comment]
Notes from Kevin about `firestone-rennovations-staging`, `milberg-staging`, `cicognara-staging`, `daviesproject-staging`: 

- none of these domains are impacted here by this ticket. It's only for static content that currently has proxy rules under paths that reside within the [library.princeton.edu](http://library.princeton.edu/) domain.
- whatever content is available under those hostnames should continue to remain available under those names in prod and staging.
- an example of a proxy rule that will change is we currently have this site https://library.princeton.edu/versailles/, that should be available at https://static.lib.princeton.edu/versailles after we complete this up.
- and we should input a redirect from the old URL to the new one

**Comment by kevinreiss** [comment]
I believe this is done both domain exist and serve up the lib-static playbook content.
