### ISSUE TITLE
Add disk space to catalog-qa1.princeton.edu

### ISSUE THREAD

**Issue by VickieKarasic** [pulibrary/princeton_ansible#5155]
### What maintenance needs to be done?

The hard disk we added a few weeks ago has filled up already. We need to investigate why this is happening but also add more space so that this machine gets updated with security tools. 

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
This machine is not getting reached by our security_theater playbook due to a full disk. This happened several weeks ago, we added a new 30GB hard disk, but this new disk has filled up already. 

### Acceptance criteria
 - [ ] Figure out why the disk is filling up so quickly 
 - [ ] Add more disk space to this machine

**Comment by VickieKarasic** [comment]
Before adding more disk space, we tried a restart of this machine to clear the `/tmp` directory, and that freed up space on the full disk and is now at 22% usage. We will monitor this when we run the `security_theater` playbook next week, and take further action if it happens again.

**Comment by acozine** [comment]
This might be a good first use case for Event-Driven Ansible. We could set up a CheckMK warning for disk space on the QA box, and have a playbook that rebooted the VM when the level reached a certain threshold.

**Comment by VickieKarasic** [comment]
I will close this issue now that catalog-qa1 has sufficient disk space to run security updates. I will create a new ticket to use this machine as a test case for Event Driven Ansible.
