### ISSUE TITLE
ansible tower does not get the new ssh key when a box is rebuilt

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#5166]
### User story
pdc-describe-staging1 was rebuilt and now we can not deploy to the box via tower

### Acceptance criteria

- [ ] a box can be fully rebuilt and I can deploy to it from tower without having to manually ssh onto the tower box and update the ssh key

### Concrete example

https://ansible-tower.princeton.edu/#/jobs/playbook/3177/output

**Comment by acozine** [comment]
Closed by #5215 - @carolyncole added a task that removes the old host from ansible tower known hosts when we rebuild a VM.
