### ISSUE TITLE
PRDS machines should mount NFS for drupal files

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#5172]
### Expected behavior
When we rebuild a VM for the PRDS site, it should have all images and other files available.

### Actual behavior
We rebuilt the PRDS (ResearchData) VMs as part of #5131, and a lot of styling and images were missing.

### Steps to replicate
Don't replicate this, but you could by building a new `prds-<env>` VM, deploying the code, and running the website.

### Impact of this bug
Original impact was that the PRDS production site was broken. Ongoing impact is the inability to rebuild this site as needed.

### Implementation notes, if any
The files still exist on the `prds-prod2-nginxplus` VM, which we resuscitated. We rsynced them to the new production VMs but that is a stopgap fix. The path is `/var/www/researchdata/shared/files`. 

### Acceptance criteria
- [ ] Mount a drive from NFS for this directory for researchdata so the files are persistent and shared across all VMs. We do this for the library website, see the two tasks starting at [this line](https://github.com/pulibrary/princeton_ansible/blob/494ac94125916dbad6407754cdf9c27dfd2215bc/roles/libwww/tasks/main.yml#L99).

**Comment by kayiwa** [comment]
Closed by #5484
