### ISSUE TITLE
[static-tables] add the static tables staging vms to checkmk

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#5181]
### What maintenance needs to be done?

Add the static tables vms to checkmk

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
So that we can see information about these VMs nicely collected into our monitoring platform

### Acceptance criteria
 - [x] all static tables staging vms are in the hosts list of https://pulcheck-staging.princeton.edu/
 - [x] there are no "false positive" warnings for these vms in checkmk

**Comment by christinach** [comment]
We ran `ansible-playbook playbooks/utils/checkmk_agent.yml --limit=static_tables_staging -e checkmk_folder=linux/dacs` and added both staging vms on checkm
