### ISSUE TITLE
[bibdata] add a healthcheck monitor to checkmk

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#5197]
### What maintenance needs to be done?

- Add the health url to the bibdata inventory
- Run the playbooks/utils/checkmk_add_local_checks.yml playbook limited to each bibdata box

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?

So that we can quickly understand the health of our VMs from our CheckMK monitoring platform

### Acceptance criteria
 - [ ] When bibdata is healthy, the status displays as OK in https://pulcheck-staging.princeton.edu
 - [ ] When bibdata is not healthy, the status displays as Critical in https://pulcheck-staging.princeton.edu

### Implementation notes, if any

Example PRs:
* [pdc](https://github.com/pulibrary/princeton_ansible/pull/4946/files)
* [allsearch-api](https://github.com/pulibrary/princeton_ansible/pull/5191/files)

Note that after running the playbook, you also have to manually "Run service discovery" in the checkmk UI.

**Comment by acozine** [comment]
We worked on this for orangelight today and ran into some roadblocks. Putting notes here for now - eventually we need to improve the documentation.

To add a Rails Health Check, you need to run the `playbooks/utils/checkmk_add_local_checks.yml` playbook after you add a value for `check_mk_health_url` to your group vars. When we did this for a group of servers, only one immediately showed pending checks. We re-ran the playbook individually on the other two servers in the group, but it's possible that a little more patience would have allowed CheckMK to add the local checks to the other two servers . . . testing is indicated.

**Comment by christinach** [comment]
To add the agent:
- `ansible-playbook playbooks/utils/checkmk_agent.yml --limit bibdata_staging -e checkmk_folder=linux/dacs` 
To add the healthcheck rule:
- `ansible-playbook playbooks/utils/checkmk_add_local_checks.yml --limit bibdata-staging2.lib.princeton.edu`
@acozine  when I ran the playbook to add the local checks using the host group I waited and gave it enough time but nothing changed. So I went ahead and ran the `checkmk_add_local_checks.yml` playbook for each host.separately.
