### ISSUE TITLE
[orangelight] add a healthcheck monitor to checkmk

### ISSUE THREAD

**Issue by sandbergja** [pulibrary/princeton_ansible#5198]
### What maintenance needs to be done?

- Add a script to check the rails healthcheck for orangelight
- Configure checkmk to use and alert on that script

### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?

So that we can quickly understand the health of our VMs from our CheckMK monitoring platform

### Acceptance criteria
 - [x] When orangelight is healthy, the status displays as OK in https://pulcheck-staging.princeton.edu
 - [x] When orangelight is not healthy, the status displays as Critical in https://pulcheck-staging.princeton.edu

### Implementation notes, if any

Example PRs:
* [pdc](https://github.com/pulibrary/princeton_ansible/pull/4946/files)
* [allsearch-api](https://github.com/pulibrary/princeton_ansible/pull/5191/files)

Note that after running the playbook, you also have to manually "Run service discovery" in the checkmk UI.

To add the check run: `ansible-playbook playbooks/utils/checkmk_add_local_checks.yml --limit catalog-indexer-staging1.princeton.edu`

**Comment by christinach** [comment]
Orangelight was already added in the checkmk

**Comment by christinach** [comment]
Thank you @acozine @sandbergja @dphillips-39 @christinach
