### ISSUE TITLE
Create a new RHEL capable image

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#5221]
### Level of urgency
- [ ] High
- [x] Moderate
- [ ] Low

### Why is this maintenance needed?
We are starting to use roles that expect a RHEL based image. We will need to create a image that can be used for prancible

### Acceptance criteria
 - [ ] If my role is used on RHEL I can successfully test it with molecule

**Comment by leefaisonr** [comment]
This works! See reference issue: https://github.com/pulibrary/tiger-data-app/issues/874
