### ISSUE TITLE
Systemd should check frequently whether log rotation needs to happen

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#5256]
### Expected behavior
When we configure log rotation, the system should rotate logs when they reach the size or age we define.

### Actual behavior
When using systemd for log rotation, a timer defines how often the system checks the log files to see if log rotation is needed. If this timer is set to a long interval, then logs can reach a much larger size without rotating.

### Steps to replicate
Set postgresql logging to `all`, set log rotation to happen when the log file reaches 1GB, and watch the disk fill up.
SSH to the machine and run `sudo systemctl list-timers` to see how long the machine will wait before even checking to see if maybe log rotation would be a good idea.

### Impact of this bug
Log rotation does not happen as expected, disks fill up, systems go down.

### Relevant links and code snippets, if applicable
Incident [notes](https://docs.google.com/document/d/1lSDs0JxeGLzP8dW8z9WTv-BLEfDJeP_YsVDb1qf_ty4/edit)

### Implementation notes, if any
Confirm that we are using systemd for logrotate across our fleet of VMs. Some VMs may be using cron instead.
Create a template for `/etc/systemd/system/logrotate.timer.d/override.conf`.
The next task after creating or updating `override.conf` should run `sudo systemctl daemon-reload` to pick up the new timer settings.
The template and tasks should go into the `common` role.

**Comment by acozine** [comment]
According to the incident notes, we should also change the [logrotate config](https://github.com/pulibrary/princeton_ansible/blob/b144fd9a90dc31427e9b603f5bd55e761dd5f259/roles/postgresql/templates/logrotate.d.postgresql.j2#L4) to use `size` instead of `maxsize`.

**Comment by maxkadel** [comment]
> According to the incident notes, we should also change the [logrotate config](https://github.com/pulibrary/princeton_ansible/blob/b144fd9a90dc31427e9b603f5bd55e761dd5f259/roles/postgresql/templates/logrotate.d.postgresql.j2#L4) to use `size` instead of `maxsize`.

I've updated the notes - we realized we were incorrect and `maxsize` is the correct term to use

**Comment by acozine** [comment]
Investigate whether we could write logs to a different drive. Would postgres keep running if the dedicated drive for logs filled up? That could be a way to protect the database from this kind of problem. This would require not adding the "log drive" to the logical volume on the VM.

**Comment by acozine** [comment]
Today I ran this change against all the postgresql servers and all the servers in the `rdss` and `dacs` groups.
