### ISSUE TITLE
lae-staging2

### ISSUE THREAD

**Issue by Beck-Davis** [pulibrary/princeton_ansible#5302]
### What maintenance needs to be done?
lae-staging2 vm is has no disk space to receive OS and security updates

### Level of urgency
- [ ] High
- [ ] Moderate
- [ ] Low

### Relevant deadlines
If this maintenance relates to an End of Life date or other deadline, please enter it here.
- [ ] EOL Date MM/DD/YYYY

### Why is this maintenance needed?
- A clear description of why this is needed.

### Acceptance criteria
 - [ ]
 - [ ]
 - [ ]

**Comment by dphillips-39** [comment]
We took a look and this machine currently does not have a full disk: 
```
pulsys@lae-staging2:~$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
tmpfs                              791M  1.6M  789M   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv   28G   12G   15G  44% /
tmpfs                              3.9G   36K  3.9G   1% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
/dev/sda2                          2.0G  254M  1.6G  14% /boot
tmpfs                              791M  4.0K  791M   1% /run/user/1000
```
