### ISSUE TITLE
Can not reboot mflux-ci1.lib.princeton.edu with anisble tower

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#5314]
Launch the ansible  tower `Utils: view VM details, reboot if needed`. 
Choose staging or production, put mflux-ci1 or mflux-ci1.lib in the box.  

Run the template to view the information and you get the same result: https://ansible-tower.princeton.edu/#/jobs/playbook/5316/output
`"msg": "Failed to find virtual machine mflux-ci1.lib"`

**Comment by acozine** [comment]
No such VM exists now. If I look in our dev environment, I only see `mflux-staging` and `mflux-ci`. 
![Screenshot 2024-09-09 at 5 10 37 PM](https://github.com/user-attachments/assets/0b450af6-b64a-4f29-b977-da2f989e4280)

Eventually the vSphere audit playbook will let you look up VM names; that will help in situations like this.

**Comment by acozine** [comment]
With the right name, rebooting works - see [this Tower job](https://ansible-tower.princeton.edu/#/jobs/playbook/5372/output).

**Comment by acozine** [comment]
I think we can close this. Best practice is to SSH into the VM if you can, to confirm the exact VM name.
