### ISSUE TITLE
[PDC-DISCOVERY] Could not rebuild with a clean machine

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#5325]
### Expected behavior
When I ran the playbook on a newly created machine it errored on `common : common | Add apt HTTPS capabilities.`

I had to ssh onto the machine and run `sudo apt-get update  --fix-missing` on the system

### Actual behavior
![Screenshot 2024-09-11 at 8 21 38 AM](https://github.com/user-attachments/assets/e02679a9-b526-423c-af56-6b71c3907093)

### Error messages
```
failed: [pdc-discovery-prod1.princeton.edu] (item=apt-transport-https) => {"ansible_loop_var": "item", "cache_update_time": 1725634098, "cache_updated": false, "changed": false, "item": "apt-transport-https", "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'apt-transport-https=2.4.12'' failed: E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_2.4.12_all.deb  404  Not Found [IP: 91.189.91.81 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_2.4.12_all.deb  404  Not Found [IP: 91.189.91.81 80]\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://us.archive.ubuntu.com/ubuntu/pool/universe/a/apt/apt-transport-https_2.4.12_all.deb  404  Not Found [IP: 91.189.91.81 80]", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following NEW packages will be installed:\n  apt-transport-https\n0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.\nNeed to get 1510 B of archives.\nAfter this operation, 170 kB of additional disk space will be used.\nErr:1 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.12\n  404  Not Found [IP: 91.189.91.81 80]\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following NEW packages will be installed:", "  apt-transport-https", "0 upgraded, 1 newly installed, 0 to remove and 2 not upgraded.", "Need to get 1510 B of archives.", "After this operation, 170 kB of additional disk space will be used.", "Err:1 http://us.archive.ubuntu.com/ubuntu jammy-updates/universe amd64 apt-transport-https all 2.4.12", "  404  Not Found [IP: 91.189.91.81 80]"]}
```

### Steps to replicate
Rebuild the machine utilizing the tower rebuild template.
Apply the pulsys keys in tower
Run the playbook

### Impact of this bug
I ran the command suggested by hand

Acceptance criteria:

- [x] Run the ansible tower playbook to create a clean VM on `pdc-discovery-staging2`. (note this should be on the public network so change the drop down)
- [x] Run the ansible tower pulsys playbook on `pdc-discovery-staging2.princeton.edu`
- [x] Run the pdc-discovery playbook on your local machine
- [x] It should error with the above issue
- [x] Run the [fix-apt](https://github.com/pulibrary/princeton_ansible/blob/main/playbooks/fix_apt_issues.yml)
- [x] Rerun the pdc-discovery playbook and make sure it finishes

**Comment by carolyncole** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/RDSS-61a4f1a12a399b001730f65a/issues/pulibrary/princeton_ansible/5325?planning-poker) with Zenhub @bess @hectorcorrea @JaymeeH @leefaisonr

**Comment by dphillips-39** [comment]
Hey Team :-) We followed the acceptance criteria and ran the pdc-discovery playbook successfully on a new VM with @sandbergja
