### ISSUE TITLE
datacommons-staging name should exist for testing

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#5330]
### User story
I would like to test changes to the datacommons load balancer without having to do it during the maintenance window

### Acceptance criteria

- [x] datacommons-staging.princeton.edu/describe exists
- [x] datacommons-staging.princeton.edu/discovery exists

**Comment by VickieKarasic** [comment]
@carolyncole These seem to be working as described in your issue. Please let us know if we're missing anything!
