### ISSUE TITLE
[PDC_DESCRIBE] Machines for PDC Describe Redis

### ISSUE THREAD

**Issue by hectorcorrea** [pulibrary/princeton_ansible#5342]
### Describe the VM(s) you need

We need a couple of new VMs to host Redis for PDC Describe.

Which project are these VMs for?
- [x] Project: PDC Describe

How many VMs do you need?
- [x] Number of VMs: 2 (one for production and one for staging)

What should the FQDN(s) be? (for example, our-new-project-staging1.princeton.edu):
- [x] FQDN: pdc-describe-redis-staging1.lib.princeton.edu
- [x] FQDN: pdc-describe-redis-prod1.lib.princeton.edu

What virtual resources does each VM need?
- [x] Number of CPUs per VM: 2
- [x] Amount of memory per VM (in GB): 16
- [x] Amount of storage/disk space per VM (in GB): 30

What firewall changes should be made? (for example, port 22 for SSH, etc.)
Please put them in the private network (I understand that means something to Francis :)

What else should we add to each VM? (for example, mount Isilon drives, add NFS server access)
- [ ] Additional resources:

**Comment by dphillips-39** [comment]
@hectorcorrea these VM's are ready, please let us know if you need anything. 


Closed by #5351

**Comment by hectorcorrea** [comment]
Thank you @dphillips-39
