### ISSUE TITLE
NGINX on Load Balancer should restart when it crashes

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/princeton_ansible#5382]
We recently had an incident where nginx segfaulted after a reload and never came back up. It should come back up when it crashes.

Related incident: https://docs.google.com/document/d/1mSh4babVNaUfKs6V9NszJ2jYLdwKXJM68UbMdKv4Wv0/edit

## Acceptance Criteria

- [ ] When nginx crashes it should automatically restart.

**Comment by acozine** [comment]
Related to #4893.

**Comment by tpendragon** [comment]
systemd file: `/lib/systemd/system/nginx.service`

In there there's no `Restart=always` which would restart it automatically.

Contents of that file:

```
[Unit]
Description=NGINX Plus - high performance web server
Documentation=https://www.nginx.com/resources/
After=network-online.target remote-fs.target nss-lookup.target
Wants=network-online.target

[Service]
Type=forking
PIDFile=/var/run/nginx.pid
ExecStartPre=/usr/lib/nginx-plus/check-subscription
ExecStart=/usr/sbin/nginx -c /etc/nginx/nginx.conf
ExecReload=/bin/sh -c "/bin/kill -s HUP $(/bin/cat /var/run/nginx.pid)"
ExecStop=/bin/sh -c "/bin/kill -s TERM $(/bin/cat /var/run/nginx.pid)"

[Install]
WantedBy=multi-user.target
```

**Comment by acozine** [comment]
@kayiwa is trying to crash the dev LB to generate error messages so we can open a ticket with Nginx.

**Comment by acozine** [comment]
Discussed today. We have an open ticket with F5 and will follow up.
