### ISSUE TITLE
[LAE] lae-staging2 failing to reboot

### ISSUE THREAD

**Issue by VickieKarasic** [pulibrary/princeton_ansible#5390]
### Expected behavior
The machine should be able to receive weekly os_updates. A reboot of the machine should successfully restart the VM. 

### Actual behavior
os_updates failed on this machine today. From watching the reboot process in vSphere, the machine is hanging on the step: "A stop job is running for Advanced key-value store." This has run for as long as 10 minutes before cancelling the restart. 

### Error messages
"A stop job is running for Advanced key-value store."

### Steps to replicate
ssh into the machine and do a `sudo /sbin/reboot` and watch behavior in vSphere

### Impact of this bug
This machine is not receiving weekly os_updates. 

### Relevant links and code snippets, if applicable

```
```

**Comment by acozine** [comment]
We're also seeing regular notifications from CheckMK about this box. The error is from the `systemd` service check - `man-db` static service failed.

**Comment by VickieKarasic** [comment]
It did come back eventually after a reboot (and a forced restart of `systemd` and `redis`), but it is still showing a full disk. We could try expanding the disk and/or explore the CheckMK failures.

**Comment by VickieKarasic** [comment]
Adding a new hard disk seems to have helped -- the machine received os_updates and rebooted quickly.
