### ISSUE TITLE
[catalog-staging][catalog-qa] Mailcatcher doesn't catch mail on qa and staging

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#5410]
### Expected behavior
When I submit a request through the request form in catalog-qa or catalog-staging I expect mailcatcher to catch the mail.

### Actual behavior
Mailcatcher does not catch the mail. 

### Steps to replicate:
- Tunnel to the catalog-staging mailcatcher:
`ssh -L 1082:localhost:1080 pulsys@catalog-staging1`

- Go to https://catalog-staging.princeton.edu/catalog/99118269913506421
- Click on the 'Request' button. Login through CAS
- Select 'Physical Item Delivery'
- Click on 'Request this item'

- Go to the [Orangelight project in honeybadger](https://app.honeybadger.io/projects/54399/faults?q=-is%3Aresolved+-is%3Aignored&sort=last_seen_desc)
You will see the same error like the ones below, login your email . It means that mailacatcher didn't catch the email and staging tried to send an email to Relay and Relay denied as expected. 

- Go to localhost:1082 (it's the mailcatcher on staging). You can see that your request is not in the mailcatcher.

### Honeybadger link and code snippet, if applicable
Related honeybadger errors: 
https://app.honeybadger.io/projects/54399/faults/113222384
https://app.honeybadger.io/projects/54399/faults/111757571
https://app.honeybadger.io/projects/54399/faults/113222385

**Comment by maxkadel** [comment]
Closed by #4533 and https://github.com/pulibrary/orangelight/pull/4549
