### ISSUE TITLE
Replace-a-vm playbook should keep the new VM in the same network

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#5423]
### Expected behavior
If I replace an existing VM, the new VM should come up in the same network space as the old VM.

### Actual behavior
You must choose which network you want to put your replacement VM on, and the output about the old VM does not include any information about the network or the IP.

### Impact of this bug
If we replace a VM and the new VM comes up in the wrong network space, it will not get an IP address.

### Acceptance criteria
- [x] The `old_vm_info` variable should, if possible, show which network the old VM was on.
- [x] The default should be `keep the new VM in the same network space as the old VM.`
- [x] The Survey should make it clear that it's possible to override the previous setting. We do want to keep this functionality for the network migration, but we should make the template safe to run for VMs that are not being migrated.

**Comment by VickieKarasic** [comment]
vSphere won't give us the name of the network, only the IP address. We will have to parse "if it starts with 172.20..." it's the private network; if it starts with 128.112..." it's the public network.
