### ISSUE TITLE
[catalog] catalog-qa1 disk full fails to receive security updates

### ISSUE THREAD

**Issue by VickieKarasic** [pulibrary/princeton_ansible#5426]
### Expected behavior
The machine should be able to receive weekly `security_theater` updates. A reboot of the machine reduces the disk size and this should let `security_theater` updates run/install. 

### Actual behavior
`security_theater` updates fail; a reboot of the machine takes a very long time due to "A stop job is running for Advanced key-value store." Once the machine does reboot, the disk size is back to normal but `security_theater` updates do not install on the machine. 

### Error messages
"A stop job is running for Advanced key-value store." Mostly all steps skipped in the `security_theater` playbook. 

### Steps to replicate

- ssh into the machine and do a `sudo /sbin/reboot` and watch behavior in vSphere
- once the machine comes back up, run `security_theater` on this machine in Tower; it will run successfully but almost all tasks are skipped
- check the `/tmp` directory on the machine and see that no security agents are installed (e.g. BESClient, falcon-sensor, ir_agent). 

### Impact of this bug
This machine is not receiving weekly security updates.

### Relevant links and code snippets, if applicable
Example of files in `/tmp` folder: 
```
-rw-------  1 root root   253729 Oct  7 12:29 passenger-error-RBmmNq.html
```

**Comment by acozine** [comment]
The disk is filling up due to passenger errors that get written as `.html` files in `/tmp`. If we can figure out what's causing those, and fix whatever it is, the problem should go away.

**Comment by VickieKarasic** [comment]
@sandbergja did a PR #5429 to remove this machine from the load balancer since it’s not serving any traffic, and that will stop the disk from filling up with errors every time it runs a health check at least. We will create a new VM to see if this stops the issue, since catalog-qa2 isn't having the same problem.

**Comment by VickieKarasic** [comment]
Created an issue to make a new VM #5431, which blocked by #5430

**Comment by VickieKarasic** [comment]
New machine has been created and security tools installed successfully. We will add this back to the loadbalancer and then close this ticket.
