### ISSUE TITLE
Whack an environment VM 

### ISSUE THREAD

**Issue by VickieKarasic** [pulibrary/princeton_ansible#5430]
### Expected behavior
If I want to replace a VM in qa, CI, or dev environment, I should be able to run a template from Ansible Tower 

### Actual behavior
Nothing exists at the moment to do this. We are only left with staging or prod. 

### Impact of this bug
We have to manually create qa, CI, and dev VMs. 

### Relevant links and code snippets, if applicable

```
```

**Comment by acozine** [comment]
There's confusion here between our inventory and our vsphere setup. In our inventory, we have things we call `qa` (and maybe `dev`) as well as `staging` and `production`. In vsphere we only have two options - staging (which has all staging & dev VMs) and and production (which has all production and most, if not all, QA VMs).

The current templates in Tower should work to replace any VM, regardless of its inventory location/category/name. If you select the correct vSphere environment, the playbook should replace any `*_qa*` or `*_dev*` VM we have. The playbook runs against `localhost`, and the `runtime_env` variable is only used in the name of the `group_vars/*.yml` file we load and the play name / message in slack.

We should test by attempting to complete #5431 - leaving this open until we have a definite answer.

**Comment by VickieKarasic** [comment]
Thanks @acozine! I'm going to attempt #5431 early next week and will report any issues.

**Comment by VickieKarasic** [comment]
Completed #5431 and can now close this as well.
