### ISSUE TITLE
Decommission abid1

### ISSUE THREAD

**Issue by acozine** [pulibrary/princeton_ansible#5439]
### What maintenance needs to be done?
Although we are only using 2 VMs for abid in production, there is a third, stray VM left over from our old naming convention. This VM is called `abid1` and it's live in vSphere, has an IP address, firewall rules, etc.

### Level of urgency
- [ ] High
- [ ] Moderate
- [x] Low

### Relevant deadlines
N/A

### Why is this maintenance needed?
We want to reduce our overhead on vSphere, clean up the firewall, and release unneeded IP addresses wherever we can.

### Implementation notes, if any
Follow our decommissioning [checklist](https://github.com/pulibrary/pul-it-handbook/blob/main/services/decommissioning.md).

**Comment by dphillips-39** [comment]
Powered down abid1 as this machine has been decommissioned see ticket TASK0340527
