### ISSUE TITLE
reboot or boot a windows VM

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#5448]
### User story

As a user I am unable to access my VM. I would like to either start or restart it. 

### Acceptance criteria

- [ ] When I do my vm is hanging, I am able to "kick it"

**Comment by acozine** [comment]
I put part of this work on this branch: https://github.com/pulibrary/princeton_ansible/tree/power-on-or-off. The changes to the playbook will require changes to the Tower template. Also, I'm not sure how Windows VMs work in vSphere. So this isn't at the PR stage yet.

**Comment by acozine** [comment]
I forgot that this ticket was assigned to @Beck-Davis. My bad.

**Comment by acozine** [comment]
Looks like Windows VMs cannot use the `restart guest OS` option in vSphere:
![Screenshot 2024-10-23 at 11 13 17 AM](https://github.com/user-attachments/assets/1fd99e1e-0d38-4438-a2f5-f05af567a8a4)
So maybe we want a separate playbook for Windows?

**Comment by acozine** [comment]
We tested rebooting a Windows VM using the existing playbook, and it worked. A few caveats:
- the Windows VM must have VMware Tools installed
- you must know which environment it's in (the Lib-Staff machines are in production)
- the VM name is case sensitive (passing `lib-staff996` failed, only `Lib-Staff996` succeeded)
If we want to add power-on and power-off (yank the power cord), we can open a separate ticket.
