### ISSUE TITLE
Setup SVN for Figgy

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#547]
Integration with PULFA will require setting up SVN (see https://github.com/pulibrary/figgy/pull/3170).  The plan is to run this on a single machine every Monday morning, so we'll only need this on figgy1.

The URL and credentials are already present in Figgy (SVN_USER, SVN_PASS, and SVN_URL), so this issue requires two things:
1. Checkout `$SVN_URL/pulfa/trunk` to `/opt/svn/pulfa`
2. Set the `SVN_DIR` environment variable pointing at `/opt/svn`

**Comment by escowles** [comment]
Should also configure the location of the PULFA SVN repository on disk in the `PULFA` environment variable.

**Comment by hackmastera** [comment]
At least some of this was done in https://github.com/pulibrary/princeton_ansible/pull/419

**Comment by escowles** [comment]
@hackmastera Thanks for reminding me of that — I think this use needs a local copy instead of talking to the HTTP service directly, but I was duplicating some of what is already there and I'll stop doing that now.

**Comment by acozine** [comment]
Obsolete since we moved to ASpace.
