### ISSUE TITLE
Don't send SolrCloud distrib queries to DataDog

### ISSUE THREAD

**Issue by tampakis** [pulibrary/princeton_ansible#555]
Each time a query is sent to a sharded Solr collection an extra 2 queries get logged. 2/3 of the Solr log events come from this.

Detect for the `distrib=false` string in the log message and exempt them from DataDog.

**Comment by tpendragon** [comment]
https://docs.datadoghq.com/agent/logs/advanced_log_collection/?tab=exclude_at_match

**Comment by hackmastera** [comment]
@tampakis where is the `distrib=false` coming from?

**Comment by escowles** [comment]
@hackmastera `distrib=false` is added by SolrCloud to the queries it farms out to the various shards.
