### ISSUE TITLE
[catalog-staging] Add new VM for catalog-indexer-staging2

### ISSUE THREAD

**Issue by christinach** [pulibrary/princeton_ansible#5578]
### What maintenance needs to be done?
Create a second VM for catalog-indexer-staging2
We have only one for [catalog-indexer-staging1](https://github.com/pulibrary/princeton_ansible/main/inventory/all_projects/orangelight#L38)

**Comment by dphillips-39** [comment]
There's very little information regarding the requirements for the new vm so I will create the second vm similar to catalog-indexer-staging1
