### ISSUE TITLE
Permit the customization of ArchivesSpace plugins within the pulibrary.archivesspace Role

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#560]
https://github.com/pulibrary/aspace_locales/pull/13/files required that an ArchivesSpace plugin (specifically, https://github.com/hudmol/user_defined_in_basic) have its configuration modified (the `config/config.rb` file).

These overrides should be introduced into the `pulibrary.archivesspace` Role.

**Comment by acozine** [comment]
ArchivesSpace is now hosted, and plugins are working.
