### ISSUE TITLE
deploy user .ssh directory permissions getting messed up

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#562]
We've seen a problem recently where running a playbook results in the permissions on the deploy user's `.ssh` directory are messed up — in particular, the execute bit is turned off so the deploy user can't list the contents of the directory.

**Comment by carolyncole** [comment]
I believe it is this line: https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.deploy-user/tasks/main.yml#L58.  I wonder if it would work without the create directory.  The previous lines should create that directory.
