### ISSUE TITLE
Add circle ci to database roles

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#577]
- [x] Mariadb

- [ ] MariadbServer

- [x] Percona

- [x] Postgres

- [x] Redis

**Comment by kayiwa** [comment]
https://www.percona.com/blog/2016/03/16/change-user-password-in-mysql-5-7-with-plugin-auth_socket/

**Comment by acozine** [comment]
We deleted the Mariadbserver role, so that is irrelevant now.

Remaining work is listed in #2720.
