### ISSUE TITLE
Add molecule to Bibdata

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#588]
Add circleci job

**Comment by jrgriffiniii** [comment]
I can work to continue progress on this using the previous work in the branch https://github.com/pulibrary/princeton_ansible/tree/588_bibdata_role

**Comment by jrgriffiniii** [comment]
I've encountered some problems with the `pulibrary.oracle.client` Role for this, and please note that I believe that I have followed the instructions on https://github.com/pulibrary/princeton_ansible/blob/master/roles/pulibrary.bibdata/README.md.

**Comment by jrgriffiniii** [comment]
Roles which use MariaDB seem to be passing on https://github.com/pulibrary/princeton_ansible/runs/220535810 (`pulibrary.pas`, as an example), however I am also finding local failures within the `local_mariadb` Task.
