### ISSUE TITLE
Permissions on shared files in libwww role

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#616]
In the libwww role the deploy user cannot delete temporary files using drush commands in the mounted drupal file system root that the playbook provisions.

**Comment by kayiwa** [comment]
ping @kevinreiss anything I can do here?

**Comment by acozine** [comment]
@kevinreiss is this still relevant? Looks like we've refactored the libwww role a bunch since this was opened.

**Comment by eliotjordan** [comment]
Kevin says we can close.
