### ISSUE TITLE
Figure out PR Zenhub Automation

### ISSUE THREAD

**Issue by tpendragon** [pulibrary/princeton_ansible#623]

**Comment by hackmastera** [comment]
Looked around some more, didn't find it. Emailed zenhub support.

**Comment by escowles** [comment]
How strange — I would swear there was a column configuration view before where you could drag the "put new PRs here" and "put new issues here" to different columns.  Maybe that was Zube?

**Comment by hackmastera** [comment]
You have to do it when opening an actual PR.

![unnamed.png](https://images.zenhubusercontent.com/5cba1f45fec3b63424e0f761/b968ea77-2db5-4b46-bd2e-a984c8ec5b9f)
