### ISSUE TITLE
deprecation: static

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#628]
when running the figgy playbook I get the following; looks like `static` is used in the solr playbook

[DEPRECATION WARNING]: The use of 'static' has been deprecated. Use          
'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. 
This feature will be removed in version 2.12. Deprecation warnings can be       
disabled by setting deprecation_warnings=False in ansible.cfg.

**Comment by acozine** [comment]
Believed to be obsolete.
