### ISSUE TITLE
deprecation: apt loops

### ISSUE THREAD

**Issue by hackartisan** [pulibrary/princeton_ansible#629]
[DEPRECATION WARNING]: Invoking "apt" only once while using a loop via 
squash_actions is deprecated. Instead of using a loop to supply multiple items 
and specifying `name: "{{ item }}"`, please use `name: ['libpq-dev', 'python-
psycopg2']` and remove the loop. This feature will be removed in version 2.11. 
Deprecation warnings can be disabled by setting deprecation_warnings=False in 
ansible.cfg.

**Comment by acozine** [comment]
We don't have `squash_actions` anywhere. Addressed.
