### ISSUE TITLE
Upgrade to OpenJDK 11?

### ISSUE THREAD

**Issue by escowles** [pulibrary/princeton_ansible#698]
To work around uncertainty and restrictions of Oracle's JDK release roadmap, Fedora recently announced they will target OpenJDK 11:
https://groups.google.com/d/msg/fedora-tech/m3wXyarxRJY/I1PtYzvaDAAJ

Should we upgrade to OpenJDK 11?

**Comment by kayiwa** [comment]
in the past we've had `pulibrary.oracle.jdk8` I'll create a role named `pulibrary.openjdk11` and devs can chose whichever role their application can use. I imagine most of these decisions are determined upstream. Does that work?

**Comment by escowles** [comment]
@kayiwa Yes, that sounds perfect.  Thanks!

**Comment by kayiwa** [comment]
it is named `pulibrary.openjdk` and you can elect to install 11
