### ISSUE TITLE
Update bibdata IP trusted IP list

### ISSUE THREAD

**Issue by kevinreiss** [pulibrary/princeton_ansible#705]
Add lib-adc server IPs to the ```BIBDATA_IP_WHITELIST``` environment variable in bibdata-prod and bibdata-staging. 

Or for bibdata’s nginx block

```proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for; ```
```proxy_set_header X-Real-IP         $remote_addr;```

**Comment by kayiwa** [comment]
include a custom log format
```
log_format custom '$remote_addr ($http_x_real_ip) - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
```
