### ISSUE TITLE
Princeton data proxied 

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#711]
pulmap is not honoring restrictions

**Comment by kayiwa** [comment]
include a custom log format
```
log_format custom '$remote_addr ($http_x_real_ip) - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"';
```

**Comment by acozine** [comment]
Closing because we have no idea what was intended and pulmap is under active development. If we still need changes, let's open a new ticket with more details.
