### ISSUE TITLE
`molecularize` invoke Task is erroneously generating `*-e` files

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#716]
Please see https://github.com/pulibrary/princeton_ansible/pull/635 for an example of this.  I suspect that there is an error in the syntax for BSD/macOS invocations for `sed` in https://github.com/pulibrary/princeton_ansible/blob/master/tasks.py#L38

**Comment by acozine** [comment]
We cannot find recent examples of this problem. If it recurs, please open a new issue.
