### ISSUE TITLE
certificates for locator-prod

### ISSUE THREAD

**Issue by carolyncole** [pulibrary/princeton_ansible#796]
We are going to need certificates for the new locator-prod server.

We will need certificates for both locator-prod.princeton.edu and locator.princeton.edu.

For the moment we will just be using the locator-prod certificates until the new site is ready to go live.

This is the WIP PR for the certificates: https://github.com/pulibrary/princeton_ansible/pull/795

**Comment by kayiwa** [comment]
closed by this commit https://github.com/pulibrary/princeton_ansible/commit/eaba7407e0fb13ce850ed9f0a2440da39f39a596
