### ISSUE TITLE
Upgrade PHP instead of using the latest

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/princeton_ansible#843]
This line is causing many problems with the linter; preventing CI from passing despite the skip instructions in `.ansible-lint`.

https://github.com/pulibrary/princeton_ansible/commit/a1fe374dbd8e5b612fc930ead5ae3ebd199261aa

Maybe we could add a step to upgrade PHP instead? Perhaps use `upgrade` option?

**Comment by kayiwa** [comment]
hmmm, the problem that is trying to fix sadly will only be solved AFAICT via `latest`
