### ISSUE TITLE
move staging mysql off prod

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#880]

**Comment by kayiwa** [comment]
- [ ] recap-staging

- [ ] library-staging

- [ ] archivesspace-staging

- [ ]

**Comment by carolyncole** [comment]
Locator was moved with this PR: https://github.com/pulibrary/princeton_ansible/pull/911/files#diff-edb6235875f93679a3e8b701902a44a8R8

**Comment by acozine** [comment]
All items checked. Closing as complete.
