### ISSUE TITLE
FreeTDS package is not available on some (older?) figgy servers

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/princeton_ansible#891]
Provisioning fails because of:

`{"changed": false, "msg": "No package matching 'freetds-dependencies' is available"}`

- figgy-staging1
- lib-proc4
- lib-proc5
- lib-proc6
- Not sure about figgy1 and figgy2

**Comment by hackmastera** [comment]
@eliotjordan so the machines you listed are the xenial machines. This means the freetds role needs to be updated to install on xenial. Or the boxes need to be moved to bionic. (figgy1 and 2 are also xenial).

**Comment by kayiwa** [comment]
hey @hackmastera this suggests that it should build on them 

https://github.com/pulibrary/princeton_ansible/blob/b9468cd80c26baac491fa0a19d78b3aed94df48f/roles/pulibrary.freetds/tasks/main.yml#L11

**Comment by kayiwa** [comment]
I do think update to bionic (scales better) FWIW.

**Comment by hackmastera** [comment]
closing in favor of #903
