### ISSUE TITLE
create a VM for dataspace environment

### ISSUE THREAD

**Issue by kayiwa** [pulibrary/princeton_ansible#892]

**Comment by kayiwa** [comment]
- [ ] Find mount for 1.5 TB Assetstore

- [ ] Get DB dump of Oracle

- [ ] convert Oracle to Postgres (idempotently)

**Comment by jrgriffiniii** [comment]
With regards to the Oracle to Postgres conversion, there did not seem to be anyone within the DSpace community who has undertaken this approach successfully between two DSpace installations of the same version.  Tim Donahue provided the following guidance:

> Unfortunately, the only way I'm aware of to use DSpace to help you migrate from Oracle to Postgres would be to export all your content & reimport it again (into a different DSpace with the new DB backend)...using something like AIP Backup & Restore: https://wiki.duraspace.org/display/DSDOC6x/AIP+Backup+and+Restore

> Keep in mind though that AIP Backup & Restore cannot restore configurations (stuff in [dspace]/config/) or usage statistics.  There are some other limitations listed here too: https://wiki.duraspace.org/display/DSDOC6x/AIP+Backup+and+Restore#AIPBackupandRestore-HowdoesthisdifferfromtraditionalDSpaceBackups?WhichBackuprouteisbetter?

I don't believe that this prevents us from undertaking this approach, it just requires the usage of this Backup and Restore utility.
