### ISSUE TITLE
Create a Role for pulibrary.pulfa

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#923]
This should be a new Role which can be used to provision the following PULFA web app. environments:
- production
- staging
- local

Where `local` should be used for Vagrant-based provisioning on a MacBook or personal development environment.

**Comment by jrgriffiniii** [comment]
In order to address `sed`-like operations one is faced with two options:
- https://docs.ansible.com/ansible/latest/modules/replace_module.html#replace-module
- https://docs.ansible.com/ansible/latest/modules/shell_module.html?highlight=shell

There may be some limitations to using `replace`, but it seems to provide enough support for RegExp that this could suffice for porting the `sed` operations found in the Vagrantfile.

**Comment by jrgriffiniii** [comment]
The Ansible documentation on variables can be found here: https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html

Specifically, the variable precedence follows this scheme:

- command line values (eg “-u user”)
- `role` defaults
- inventory file or script group vars
- inventory `group_vars/all`
- playbook `group_vars/all`
- inventory `group_vars/*`
- playbook `group_vars/*`
- inventory file or script host vars
- inventory `host_vars/*`
- playbook `host_vars/*`
- host facts / cached set_facts
- play `vars`
- play `vars_prompt`
- play `vars_files`
- role vars (defined in `role/vars/main.yml`)
- block vars (only for tasks in block)
- task vars (only for the task)
- include_vars
- set_facts / registered vars
- role (and include_role) params
- include params
- extra vars (always win precedence)

(please see the section https://docs.ansible.com/ansible/latest/user_guide/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable)

**Comment by jrgriffiniii** [comment]
@cwulfman I have scaffolded a new role, playbook, and Vagrantfile with https://github.com/pulibrary/princeton_ansible/tree/prototype-pulfa-jrgriffiniii.  I am testing this now, and will offer some more instructions for running the Vagrantfile before proceeding with integrating SVN for checking out the EADs.

**Comment by jrgriffiniii** [comment]
https://github.com/pulibrary/princeton_ansible/commit/43f4ffeff19278229659e7f3eaddf4a407a68724 advances this with Solr and eXistdb on the Vagrant Box.

**Comment by jrgriffiniii** [comment]
This should just duplicate Subversion checkouts between this new Role and that of `plantain`.

**Comment by acozine** [comment]
Obsolete. The PULFA site has been replaced by Pulfalight, which has its own playbook and role.
