### ISSUE TITLE
ImageMagick resource limit values are not respected

### ISSUE THREAD

**Issue by eliotjordan** [pulibrary/princeton_ansible#924]
https://github.com/pulibrary/princeton_ansible/blob/master/group_vars/figgy_production.yml#L149-L154

The values for ImageMagick resource limits set as environment variables are superseded by values in `/etc/ImageMagick-6/policy.xml`. The values in policy.xml are quite small and this is causing an issue with processing scanned map derivatives. The suggestion is to comment out the policymap settings in policy.xml. This allows the values to be set in env variables. I tried this out and it works. Solves the issue with derivative processing.

https://github.com/ImageMagick/ImageMagick/issues/396#issuecomment-319569255

**Comment by tpendragon** [comment]
I manually adjusted the XML file and I'm testing it now on the scroll.

**Comment by tpendragon** [comment]
The larger resource limits worked.

**Comment by tpendragon** [comment]
Working on an imagemagick role which includes a policy.xml.
