### ISSUE TITLE
plantain_staging Playbook should install a local version of Solr 8.2.0

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#930]
This is necessary given that the latest changes to ArcLight utilized nested documents for indexing.

**Comment by jrgriffiniii** [comment]
https://github.com/projectblacklight/arclight/pull/565 is where the change was introduced requiring this.

**Comment by kayiwa** [comment]
doesn't this scale better to upgrade the solr cluster to 8.2.0? certainly the lib-solr-staging can? no? @tampakis ?

**Comment by jrgriffiniii** [comment]
I defer to @tampakis and @christinach here, but Vagrant is breaking in my local development environment. I'll work to troubleshoot my Vagrantfile while testing the Playbook adjustments.

**Comment by jrgriffiniii** [comment]
Resolved by #960
