### ISSUE TITLE
Deprecate lib-aspace-test1 (or lib-aspace-dev1)

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#935]
`lib-aspace-test1` was provided in April 2019 in order to support the evaluation of ArchivesSpace as a candidate for replacing the Princeton University Library Finding Aids platform by the Archival Access and Discovery Working Group.  As this group as concluded its chartered work, this installation is no longer necessary to serve these needs.

It seems to me that it is now redundant with the installation deployed to lib-aspace-dev1.  Should this (or lib-aspace-dev1) be retired?

**Comment by kayiwa** [comment]
Sadly I actually needed. It is useful because lib-aspace-dev1 is used in a production capacity.
