### ISSUE TITLE
Improve integration with Datadog for DataSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#936]
This requires that the DSpace deployment for https://dataspace.princeton.edu use Ansible first, but I can see that HTTP monitoring support was accomplished for Cantaloupe: https://github.com/pulibrary/princeton_ansible/blob/master/group_vars/cantaloupe/production.yml#L50

**Comment by acozine** [comment]
We have no Ansible builds for DSpace. If this is still needed, let's open a new issue.
