### ISSUE TITLE
Improve integration with Datadog for ArchivesSpace

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#938]
Datadog indicates that only the `system` and `ntp` levels of monitoring are available: https://app.datadoghq.com/infrastructure?filter=aspace&hostname=lib-aspace-prod1.  Perhaps HTTP checks should be introduced.

**Comment by acozine** [comment]
We are now using a hosted ArchivesSpace installation. Closing this ticket as obsolete.
