### ISSUE TITLE
Under certain conditions the `molecularize` invoke task deletes role directories

### ISSUE THREAD

**Issue by jrgriffiniii** [pulibrary/princeton_ansible#959]
This was discovered when attempting to implement tests for the existing `pulibrary.solr` Role.

**Comment by hackmastera** [comment]
I think i was inside the directory for the role I was trying to molecularize. but yeah sort of weird!

**Comment by acozine** [comment]
If this happens again in future, let's open a new ticket and list the conditions/more details.
